import { Level } from "@/types/level";
import { challengeBossMastery } from "./challenges";

export const level6: Level = {
  id: "primes-level-6",
  index: 6,
  tier: 3,
  title: "Boss Level: Ujian Modul Faktorisasi Prima & Koprima",
  description: "Ujian menyeluruh menguji atom prima, saringan Eratosthenes, relasi koprima, dan fungsi Euler.",
  ahaMoment: "Bilangan prima adalah fondasi kekal yang menopang seluruh struktur matematika modern!",
  steps: [
    {
      id: "p6-s1",
      type: "provoke",
      title: "Ujian Akhir Modul Teori Bilangan",
      naiExpression: "thinking",
      naiDialogue: "Kamu telah menyelesaikan kisi balok, saringan Eratosthenes, garis pandang koprima, fungsi Euler, hingga Teorema Fermat. Buktikan keahlianmu!",
      provoke: {
        hookTitle: "Ujian Akhir Teori Bilangan & Kriptografi",
        hookText: "Boss Level ini menguji seluruh penguasaan konsep faktorisasi prima dan koprima dari Level 1 sampai Level 5.",
        interactiveComponentSlug: "math-primes-coprime",
        initialVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
        question: "Jika N = 2³ × 3² × 5, berapa banyak total faktor pembagi positif dari bilangan N?",
        options: [
          {
            id: "opt-24-factors",
            text: "24 faktor pembagi (karena (3+1) × (2+1) × (1+1) = 4 × 3 × 2 = 24)",
            responseText: "Brilian! Rumus kombinatorika kisi faktor (e_1 + 1)(e_2 + 1)...(e_k + 1) langsung menghitung seluruh faktor tanpa perlu mendaftar satu per satu!",
          },
          {
            id: "opt-6-factors",
            text: "Hanya 6 faktor",
            responseText: "Kurang tepat. 6 hanyalah jumlah eksponennya, bukan kombinasi faktornya.",
          },
        ],
      },
    },
    {
      id: "p6-s2",
      type: "predict",
      title: "Verifikasi Pasangan Koprima Master",
      naiExpression: "thinking",
      naiDialogue: "Apakah pasangan A = 9 dan B = 7 saling koprima?",
      predict: {
        scenarioTitle: "Uji Koprima Cepat",
        scenarioText: "9 = 3² dan 7 adalah bilangan prima.",
        question: "Berapakah FPB(9, 7)?",
        options: [
          {
            id: "pred-1-boss",
            text: "1 (keduanya saling koprima, garis pandang bebas hambatan)",
            isCorrect: true,
            feedback: "Benar! FPB(9, 7) = 1, sehingga garis pandang berwarna hijau terang.",
          },
          {
            id: "pred-3-boss",
            text: "3",
            isCorrect: false,
            feedback: "7 tidak habis dibagi 3.",
          },
        ],
        simulationLabel: "Buktikan Garis Pandang (9, 7)!",
        interactiveComponentSlug: "math-primes-coprime",
        initialVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
        simulationVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
      },
    },
    {
      id: "p6-s3",
      type: "guided",
      title: "Simulator Penuh Prima & Koprima",
      naiExpression: "happy",
      naiDialogue: "Eksplorasi hubungan antara bilangan prima N = 37 dan pasangan koprima (9, 7) di kanvas!",
      guided: {
        instructionTitle: "Laboratorium Terpadu Teori Bilangan",
        instructionText: "Atur N ke 37, koordinat A ke 9, dan koordinat B ke 7.",
        interactiveComponentSlug: "math-primes-coprime",
        initialVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
        observationTable: {
          headers: ["Parameter", "Nilai", "Verifikasi Teorema"],
          rows: [
            { parameter: "N = 37", expectedValue: "Prima", unit: "φ(37) = 36" },
            { parameter: "A = 9, B = 7", expectedValue: "FPB = 1", unit: "Koprima Murni" },
          ],
        },
        discoveryQuestion: {
          prompt: "Berapakah nilai dari 2³⁶ mod 37 menurut Teorema Fermat?",
          options: [
            "Tepat bernilai 1",
            "Bernilai 2",
            "Bernilai 36",
          ],
          correctOption: "Tepat bernilai 1",
          insight: "Karena 37 prima, maka a^(37-1) = a^36 ≡ 1 (mod 37).",
        },
      },
    },
    {
      id: "p6-s4",
      type: "formalize",
      title: "Hukum Agung Semesta Aritmetika",
      naiExpression: "neutral",
      naiDialogue: "Mari kita tuangkan rangkuman universal teori bilangan prima ke dalam KaTeX.",
      formalize: {
        title: "Pondasi Abadi Aritmetika",
        prompt: "Lengkapi identitas teorema dasar bilangan:",
        formulaTemplate: "\\forall n > 1, \\quad n = \\prod_{i} p_i^{[blank1]} \\quad \\text{dan} \\quad a^{\\phi(n)} \\equiv [blank2] \\pmod n",
        blanks: [
          { id: "blank1", label: "Eksponen Prima", options: ["a_i", "1", "n"], correctOption: "a_i" },
          { id: "blank2", label: "Teorema Euler-Fermat", options: ["1", "0", "a"], correctOption: "1" },
        ],
        resolvedFormulaKaTeX: "\\forall n > 1, \\quad n = \\prod_{i} p_i^{a_i} \\quad \\text{dan} \\quad a^{\\phi(n)} \\equiv 1 \\pmod n",
        explanation: "Teorema Euler menggeneralisasi Teorema Fermat untuk sembarang modulus n: jika FPB(a, n) = 1, maka a^φ(n) ≡ 1 (mod n).",
      },
    },
    {
      id: "p6-s5",
      type: "check",
      title: "Cek Evaluasi Komprehensif",
      naiExpression: "thinking",
      naiDialogue: "Pertanyaan evaluasi terakhir sebelum mengeksekusi misi penutupan!",
      check: {
        question: "Manakah dari bilangan berikut yang merupakan bilangan prima?",
        checkType: "multiple_choice",
        options: [
          { id: "opt-127-prime", text: "127 (tidak habis dibagi 2, 3, 5, 7, 11 karena √127 ≈ 11.27)", isCorrect: true, explanation: "Tepat sekali! 119 = 7 × 17, 133 = 7 × 19, 143 = 11 × 13. Hanya 127 yang prima murni!" },
          { id: "opt-119-prime", text: "119", isCorrect: false, explanation: "119 = 7 × 17, adalah bilangan komposit." },
          { id: "opt-143-prime", text: "143", isCorrect: false, explanation: "143 = 11 × 13, adalah bilangan komposit." },
        ],
        explanation: "Uji prima sampai √N membuktikan hanya 127 yang tidak memiliki faktor pembagi.",
      },
    },
    {
      id: "p6-s6",
      type: "sandbox",
      title: "Playground Boss Level",
      naiExpression: "happy",
      naiDialogue: "Uji coba konfigurasi parameter sebelum menyelesaikan misi akhir.",
      sandbox: {
        title: "Simulasi Bebas Boss Level",
        instructions: "Eksplorasi hubungan antara N, koordinat A, dan koordinat B.",
        interactiveComponentSlug: "math-primes-coprime",
        initialVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
      },
    },
    {
      id: "p6-s7",
      type: "challenge",
      title: "Misi Terakhir: Konfigurasi Prima & Koprima Master",
      naiExpression: "neutral",
      naiDialogue: "Atur N ke bilangan prima 37, koordinat A = 9, dan koordinat B = 7 (keduanya saling koprima dengan FPB = 1)!",
      challenge: challengeBossMastery,
    },
    {
      id: "p6-s8",
      type: "reflect",
      title: "Kelulusan Modul Faktorisasi Prima",
      naiExpression: "celebrating",
      naiDialogue: "Luar biasa! Kamu telah resmi menguasai Faktorisasi Prima & Bilangan Koprima hingga ke arsitektur kriptografi modern!",
      reflect: {
        title: "Modul Selesai: Master Bilangan Prima & Kriptografi",
        takeaways: [
          "Bilangan prima adalah partikel atom penyusun semesta aritmetika.",
          "Saringan Eratosthenes dan batas √N menyaring prima secara efisien.",
          "Koprima adalah relasi nir-faktor sekutu yang membentuk garis pandang bebas kisi koordinat.",
          "Fungsi Euler φ(n) dan Teorema Fermat adalah pilar pertahanan enkripsi informasi dunia.",
        ],
        connectionText: "Selamat! Kamu telah menuntaskan seluruh Fondasi Matematika 1A: Bilangan & Aritmetika!",
        badgeToUnlock: "prime-grandmaster",
        xpReward: 100,
        formulaKaTeX: "\\forall n > 1, \\quad n = \\prod_{i} p_i^{a_i}",
      },
    },
  ],
};
