import { Level } from "@/types/level";
import { challengeSieve29 } from "./challenges";

export const level2: Level = {
  id: "primes-level-2",
  index: 2,
  tier: 1,
  title: "Saringan Eratosthenes & Batas Akar Kuadrat",
  description: "Menyaring kelipatan secara berirama hingga batas √N tanpa perlu menguji satu per satu.",
  ahaMoment: "Kita tidak perlu menguji keprimaan satu per satu: cukup eliminasi kelipatan secara ritmis sampai batas √N!",
  steps: [
    {
      id: "p2-s1",
      type: "provoke",
      title: "Mencari Jarum di Tumpukan Jerami",
      naiExpression: "curious",
      naiDialogue: "Bagaimana cara ilmuwan Yunani Kuno 2200 tahun lalu menemukan semua bilangan prima di bawah 100 tanpa kalkulator?",
      provoke: {
        hookTitle: "Saringan Ritmis 2200 Tahun Lalu",
        hookText: "Jika kita harus menguji pembagian satu per satu untuk 100 angka, itu sangat melelahkan. Eratosthenes memiliki ide brilian: menyaring kelipatannya!",
        interactiveComponentSlug: "math-primes-coprime",
        initialVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
        question: "Ketika kita mencoret semua kelipatan 2 (4, 6, 8, 10...), berapa persen angka di tabel yang langsung gugur?",
        options: [
          {
            id: "opt-half-drop",
            text: "50% dari tabel langsung gugur dalam satu langkah!",
            responseText: "Tepat sekali! Setengah dari seluruh angka di tabel langsung tereliminasi hanya dengan satu ritme kelipatan 2.",
          },
          {
            id: "opt-ten-drop",
            text: "Hanya 10% saja.",
            responseText: "Kurang tepat. Setiap angka kedua adalah bilangan genap, jadi separuh tabel langsung tereliminasi.",
          },
        ],
      },
    },
    {
      id: "p2-s2",
      type: "predict",
      title: "Batas Penyaringan: Kapan Kita Berhenti?",
      naiExpression: "thinking",
      naiDialogue: "Untuk tabel 1 sampai 100, apakah kita perlu mencoret kelipatan 11?",
      predict: {
        scenarioTitle: "Menentukan Batas √N",
        scenarioText: "Kelipatan terkecil dari 11 yang belum dicoret oleh angka sebelumnya (2, 3, 5, 7) adalah 11 × 11.",
        question: "Berapakah 11 × 11, dan apakah ia melebihi batas tabel 100?",
        options: [
          {
            id: "pred-121-over",
            text: "11 × 11 = 121 > 100, sehingga kelipatan 11 tidak perlu disaring lagi!",
            isCorrect: true,
            feedback: "Brilian! Untuk menguji angka hingga N = 100, kita CUKUP menyaring sampai prima ≤ √100 = 10 (hanya 2, 3, 5, dan 7)!",
          },
          {
            id: "pred-need-11",
            text: "Tetap harus diuji sampai angka 99",
            isCorrect: false,
            feedback: "Semua kelipatan 11 di bawah 100 (seperti 22, 33, 44...) sudah otomatis tercoret oleh faktor yang lebih kecil!",
          },
        ],
        simulationLabel: "Buktikan Batas Saringan!",
        interactiveComponentSlug: "math-primes-coprime",
        initialVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
        simulationVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
      },
    },
    {
      id: "p2-s3",
      type: "guided",
      title: "Eksplorasi Saringan Eratosthenes",
      naiExpression: "happy",
      naiDialogue: "Pilih tab Saringan Eratosthenes di kanvas untuk mengamati pola prima hijau terang!",
      guided: {
        instructionTitle: "Tabel Saringan Prima 1-60",
        instructionText: "Amati bagaimana kelipatan 2, 3, dan 5 disaring bertahap hingga menyisakan bilangan prima.",
        interactiveComponentSlug: "math-primes-coprime",
        initialVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
        observationTable: {
          headers: ["Gelombang Saringan", "Prima Aktif", "Batas Kelipatan"],
          rows: [
            { parameter: "Gelombang 1", expectedValue: "Kelipatan 2", unit: "setengah gugur" },
            { parameter: "Gelombang 2", expectedValue: "Kelipatan 3", unit: "diagonal ritmis" },
            { parameter: "Gelombang 3", expectedValue: "Kelipatan 5 & 7", unit: "tabel bersih" },
          ],
        },
        discoveryQuestion: {
          prompt: "Mengapa bilangan komposit pasti memiliki faktor prima pembagi ≤ √N?",
          options: [
            "Karena jika kedua faktornya > √N, hasil kalinya akan melebihi N",
            "Karena akar kuadrat selalu bernilai bulat",
            "Hanya kebetulan aritmetika",
          ],
          correctOption: "Karena jika kedua faktornya > √N, hasil kalinya akan melebihi N",
          insight: "Jika N = a · b dan a > √N serta b > √N, maka a · b > N (kontradiksi). Maka salah satu faktor pasti ≤ √N!",
        },
      },
    },
    {
      id: "p2-s4",
      type: "formalize",
      title: "Batas Akar Kuadrat Uji Prima",
      naiExpression: "neutral",
      naiDialogue: "Mari tuangkan teorema batas akar kuadrat keprimaan ke dalam KaTeX.",
      formalize: {
        title: "Batas Uji Keprimaan √N",
        prompt: "Lengkapi teorema pengujian keprimaan berikut:",
        formulaTemplate: "N \\text{ komposit} \\implies \\exists p \\text{ prima sedemikian sehingga } p \\mid N \\text{ dan } p \\le [blank1]",
        blanks: [
          { id: "blank1", label: "Batas Atas", options: ["\\sqrt{N}", "N / 2", "N - 1"], correctOption: "\\sqrt{N}" },
        ],
        resolvedFormulaKaTeX: "N \\text{ komposit} \\implies \\exists p \\in \\mathbb{P}, \\quad p \\mid N \\quad \\text{dengan } p \\le \\sqrt{N}",
        explanation: "Untuk menguji apakah N prima, kita hanya perlu membagi dengan bilangan prima sampai batas √N. Ini menghemat 90% waktu komputasi.",
      },
    },
    {
      id: "p2-s5",
      type: "check",
      title: "Cek Batas Uji Prima 173",
      naiExpression: "thinking",
      naiDialogue: "Berapakah bilangan prima terbesar yang perlu kita uji untuk memeriksa keprimaan 173?",
      check: {
        question: "Untuk memeriksa apakah 173 adalah bilangan prima, prima terbesar apa yang perlu kita coba bagi?",
        checkType: "multiple_choice",
        options: [
          { id: "opt-13-prime", text: "13 (karena 13² = 169 ≤ 173 dan 14² = 196 > 173)", isCorrect: true, explanation: "Tepat sekali! √173 ≈ 13.15. Kita hanya perlu menguji prima 2, 3, 5, 7, 11, dan 13." },
          { id: "opt-17-prime", text: "17", isCorrect: false, explanation: "17² = 289 > 173, terlalu besar." },
          { id: "opt-86-prime", text: "86 (separuh dari 173)", isCorrect: false, explanation: "Menguji sampai separuh sangat boros waktu; batas √N jauh lebih efisien." },
        ],
        explanation: "Batas prima terbesar adalah p ≤ √173 ≈ 13.15, yaitu prima 13.",
      },
    },
    {
      id: "p2-s6",
      type: "sandbox",
      title: "Playground Saringan Eratosthenes",
      naiExpression: "happy",
      naiDialogue: "Amati tampilan kisi saringan prima 1 sampai 60 secara langsung di kanvas.",
      sandbox: {
        title: "Simulasi Saringan Eratosthenes",
        instructions: "Pilih tab Saringan Eratosthenes di kanvas untuk mengamati pola prima hijau terang.",
        interactiveComponentSlug: "math-primes-coprime",
        initialVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
      },
    },
    {
      id: "p2-s7",
      type: "challenge",
      title: "Misi: Deteksi Prima Kembar 29",
      naiExpression: "neutral",
      naiDialogue: "Atur slider N ke bilangan prima terbesar di bawah 30 yang membentuk pasangan prima kembar dengan 31 (Target: N = 29)!",
      challenge: challengeSieve29,
    },
    {
      id: "p2-s8",
      type: "reflect",
      title: "Refleksi Level 2: Ritme Saringan",
      naiExpression: "celebrating",
      naiDialogue: "Hebat! Dengan saringan Eratosthenes, mencari ratusan bilangan prima menjadi sangat ritmis dan cepat!",
      reflect: {
        title: "Level 2 Tuntas: Saringan Eratosthenes & Batas √N",
        takeaways: [
          "Kita tidak perlu menguji keprimaan satu per satu, cukup eliminasi kelipatan secara ritmis.",
          "Batas pengujian keprimaan bilangan N selalu dibatasi oleh √N.",
          "Pasangan prima kembar seperti (29, 31) adalah prima yang berselisih tepat 2.",
        ],
        connectionText: "Di Level 3, kita akan mempelajari hubungan antara dua bilangan yang tidak berbagi faktor persekutuan: BILANGAN KOPRIMA!",
        nextLevelTitle: "Level 3: Bilangan Relatif Prima (Koprima)",
        badgeToUnlock: "pattern-seeker",
        xpReward: 40,
        formulaKaTeX: "d_{\\min} \\le \\sqrt{N}",
      },
    },
  ],
};
