import { CurriculumTreeData } from "./types";

export const mathTreeData: CurriculumTreeData = {
  nodes: [
    // Level 1A
    {
      id: "math-real-numbers",
      slug: "math-real-numbers",
      title: "Operasi Bilangan Riil",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Fondasi nalar bilangan bulat, pecahan, rasio, dan garis bilangan berkesinambungan.",
      xp: 50,
      isAvailable: false,
      position: { x: 120, y: 50 },
    },
    {
      id: "arithmetic-modular-clock",
      slug: "arithmetic-modular-clock",
      title: "Aritmetika Jam (Modulo)",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Modulo sebagai rotasi jam dinding, sisa bagi siklis, dan pola kurva kardioid.",
      xp: 120,
      isAvailable: true,
      route: "/topics/arithmetic-modular-clock",
      position: { x: 50, y: 200 },
    },
    {
      id: "math-euclid",
      slug: "math-euclid",
      title: "Algoritma Euclid & FPB",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Pengubinan persegi panjang dengan bujur sangkar terbesar untuk mencari faktor persekutuan.",
      xp: 75,
      isAvailable: false,
      position: { x: 260, y: 200 },
    },
    {
      id: "math-prime-factorization",
      slug: "math-prime-factorization",
      title: "Faktorisasi Prima",
      domain: "math",
      stage: "explorer",
      phase: "v1.1",
      level: 1,
      description: "Teorema dasar aritmetika, bilangan prima sebagai atom penyusun bilangan, dan fungsi Euler.",
      xp: 80,
      isAvailable: false,
      position: { x: 150, y: 350 },
    },
    // Level 1B
    {
      id: "math-elementary-algebra",
      slug: "math-elementary-algebra",
      title: "Aljabar Elementer",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Manipulasi kesetaraan variabel, sistem persamaan dua variabel, dan timbangan logika.",
      xp: 60,
      isAvailable: false,
      position: { x: 500, y: 50 },
    },
    {
      id: "math-functions-graphs",
      slug: "math-functions-graphs",
      title: "Fungsi & Grafik",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Pemetaan domain ke kodomain, transformasi translasi, dilatasi, dan kurva reaktif.",
      xp: 90,
      isAvailable: false,
      position: { x: 500, y: 200 },
    },
    // Level 1C & 1D
    {
      id: "math-euclidean-geometry",
      slug: "math-euclidean-geometry",
      title: "Geometri Euclid",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Aksioma bidang, sudut, segitiga, dan pembuktian visual Teorema Pythagoras.",
      xp: 70,
      isAvailable: false,
      position: { x: 780, y: 50 },
    },
    {
      id: "math-logic-prop",
      slug: "math-logic-prop",
      title: "Logika Proposisional",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Tabel kebenaran, implikasi logis, dan penalaran deduktif formal.",
      xp: 65,
      isAvailable: false,
      position: { x: 1040, y: 50 },
    },
    // Level 2
    {
      id: "math-limits-continuity",
      slug: "math-limits-continuity",
      title: "Limit & Kekontinuan",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Perilaku fungsi saat mendekati titik kritis dan definisi intuisi limit.",
      xp: 100,
      isAvailable: false,
      position: { x: 500, y: 350 },
    },
    {
      id: "math-differential-calculus",
      slug: "math-differential-calculus",
      title: "Kalkulus Diferensial",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Garis singgung, laju perubahan sesaat, dan optimasi nilai ekstrem fungsi.",
      xp: 120,
      isAvailable: false,
      position: { x: 500, y: 500 },
    },
    {
      id: "math-integral-calculus",
      slug: "math-integral-calculus",
      title: "Kalkulus Integral",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Akumulasi luas di bawah kurva dan teorema dasar kalkulus.",
      xp: 130,
      isAvailable: false,
      position: { x: 500, y: 650 },
    },
    // Level 3
    {
      id: "linear-algebra-determinant-2d",
      slug: "linear-algebra-determinant-2d",
      title: "Determinan Matriks 2D",
      domain: "math",
      stage: "scholar",
      phase: "mvp",
      level: 3,
      description: "Faktor skala luas spasial hasil transformasi matriks basis koordinat 2D.",
      xp: 120,
      isAvailable: true,
      route: "/topics/linear-algebra-determinant-2d",
      position: { x: 260, y: 500 },
    },
    {
      id: "math-vector-spaces",
      slug: "math-vector-spaces",
      title: "Ruang Vektor",
      domain: "math",
      stage: "scholar",
      phase: "v1.1",
      level: 3,
      description: "Kombinasi linear, kebebasan linear, basis, dan dimensi ruang dimensi-n.",
      xp: 140,
      isAvailable: false,
      position: { x: 260, y: 650 },
    },
    {
      id: "math-cryptography",
      slug: "math-cryptography",
      title: "Kriptografi Modern",
      domain: "math",
      stage: "scholar",
      phase: "v2.0",
      level: 3,
      description: "Kunci publik RSA, pertukaran Diffie-Hellman, dan kurva eliptik berbasis aritmetika modulo.",
      xp: 180,
      isAvailable: false,
      position: { x: 80, y: 650 },
    },
    {
      id: "math-multivariable-calculus",
      slug: "math-multivariable-calculus",
      title: "Kalkulus Multivariabel",
      domain: "math",
      stage: "scholar",
      phase: "v1.1",
      level: 3,
      description: "Turunan parsial, gradien medan skalar, dan integral lipat pada permukaan 3D.",
      xp: 160,
      isAvailable: false,
      position: { x: 740, y: 650 },
    },
  ],
  edges: [
    { id: "e-real-clock", source: "math-real-numbers", target: "arithmetic-modular-clock" },
    { id: "e-real-euclid", source: "math-real-numbers", target: "math-euclid" },
    { id: "e-clock-prime", source: "arithmetic-modular-clock", target: "math-prime-factorization" },
    { id: "e-euclid-prime", source: "math-euclid", target: "math-prime-factorization" },
    { id: "e-real-alg", source: "math-real-numbers", target: "math-elementary-algebra" },
    { id: "e-alg-func", source: "math-elementary-algebra", target: "math-functions-graphs" },
    { id: "e-real-geo", source: "math-real-numbers", target: "math-euclidean-geometry" },
    { id: "e-func-limits", source: "math-functions-graphs", target: "math-limits-continuity" },
    { id: "e-limits-diff", source: "math-limits-continuity", target: "math-differential-calculus" },
    { id: "e-diff-integ", source: "math-differential-calculus", target: "math-integral-calculus" },
    { id: "e-alg-det", source: "math-elementary-algebra", target: "linear-algebra-determinant-2d" },
    { id: "e-det-vectors", source: "linear-algebra-determinant-2d", target: "math-vector-spaces" },
    { id: "e-clock-crypto", source: "arithmetic-modular-clock", target: "math-cryptography" },
    { id: "e-prime-crypto", source: "math-prime-factorization", target: "math-cryptography" },
    { id: "e-integ-multi", source: "math-integral-calculus", target: "math-multivariable-calculus" },
    { id: "e-det-multi", source: "linear-algebra-determinant-2d", target: "math-multivariable-calculus" },
  ],
};
