import { CurriculumTreeData } from "./types";

export const mathTreeData: CurriculumTreeData = {
  nodes: [
    // Track 1: Aritmetika & Teori Bilangan (Number Theory & Cryptography)
    {
      id: "math-real-numbers",
      slug: "math-real-numbers-line",
      title: "Operasi Bilangan Riil",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Fondasi nalar bilangan bulat, pecahan, rasio, dan garis bilangan berkesinambungan.",
      xp: 100,
      isAvailable: true,
      route: "/topics/math-real-numbers-line",
      position: { x: 380, y: 60 },
    },
    {
      id: "arithmetic-modular-clock",
      slug: "arithmetic-modular-clock",
      title: "Aritmetika Jam (Modulo)",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Modulo sebagai rotasi jam dinding, sisa bagi siklis, dan pola kurva kardioid.",
      xp: 120,
      isAvailable: true,
      route: "/topics/arithmetic-modular-clock",
      position: { x: 60, y: 240 },
    },
    {
      id: "math-euclid",
      slug: "math-euclid",
      title: "Algoritma Euclid & FPB",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Pengubinan persegi panjang dengan bujur sangkar terbesar untuk mencari faktor persekutuan.",
      xp: 110,
      isAvailable: true,
      route: "/topics/math-euclid",
      position: { x: 380, y: 240 },
    },
    {
      id: "math-prime-factorization",
      slug: "math-primes-coprime",
      title: "Faktorisasi Prima & Koprima",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Teorema dasar aritmetika, bilangan prima sebagai atom bilangan, saringan Eratosthenes, dan pilar RSA.",
      xp: 130,
      isAvailable: true,
      route: "/topics/math-primes-coprime",
      position: { x: 220, y: 440 },
    },
    {
      id: "math-cryptography",
      slug: "math-cryptography",
      title: "Kriptografi Modern",
      domain: "math",
      stage: "scholar",
      phase: "v2.0",
      level: 3,
      description: "Kunci publik RSA, pertukaran Diffie-Hellman, dan kurva eliptik berbasis aritmetika modulo.",
      xp: 180,
      isAvailable: false,
      position: { x: 220, y: 660 },
    },

    // Track 2: Aljabar & Aljabar Linear (Algebra & Linear Algebra)
    {
      id: "math-elementary-algebra",
      slug: "math-elementary-algebra",
      title: "Aljabar Elementer",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Manipulasi kesetaraan variabel, sistem persamaan dua variabel, dan timbangan logika.",
      xp: 60,
      isAvailable: false,
      position: { x: 700, y: 240 },
    },
    {
      id: "linear-algebra-determinant-2d",
      slug: "linear-algebra-determinant-2d",
      title: "Determinan Matriks 2D",
      domain: "math",
      stage: "scholar",
      phase: "mvp",
      level: 3,
      description: "Faktor skala luas spasial hasil transformasi matriks basis koordinat 2D.",
      xp: 120,
      isAvailable: true,
      route: "/topics/linear-algebra-determinant-2d",
      position: { x: 700, y: 440 },
    },
    {
      id: "math-vector-spaces",
      slug: "math-vector-spaces",
      title: "Ruang Vektor",
      domain: "math",
      stage: "scholar",
      phase: "v1.1",
      level: 3,
      description: "Kombinasi linear, kebebasan linear, basis, dan dimensi ruang dimensi-n.",
      xp: 140,
      isAvailable: false,
      position: { x: 700, y: 660 },
    },

    // Track 3: Fungsi & Kalkulus (Functions & Calculus)
    {
      id: "math-functions-graphs",
      slug: "math-functions-graphs",
      title: "Fungsi & Grafik",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Pemetaan domain ke kodomain, transformasi translasi, dilatasi, dan kurva reaktif.",
      xp: 90,
      isAvailable: false,
      position: { x: 1020, y: 340 },
    },
    {
      id: "math-limits-continuity",
      slug: "math-limits-continuity",
      title: "Limit & Kekontinuan",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Perilaku fungsi saat mendekati titik kritis dan definisi intuisi limit.",
      xp: 100,
      isAvailable: false,
      position: { x: 1020, y: 520 },
    },
    {
      id: "math-differential-calculus",
      slug: "math-differential-calculus",
      title: "Kalkulus Diferensial",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Garis singgung, laju perubahan sesaat, dan optimasi nilai ekstrem fungsi.",
      xp: 120,
      isAvailable: true,
      route: "/topics/math-calculus-tangent",
      position: { x: 1020, y: 700 },
    },
    {
      id: "math-integral-calculus",
      slug: "math-integral-calculus",
      title: "Kalkulus Integral",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Akumulasi luas di bawah kurva dan teorema dasar kalkulus.",
      xp: 130,
      isAvailable: true,
      route: "/topics/math-calculus-riemann",
      position: { x: 1020, y: 880 },
    },
    {
      id: "math-multivariable-calculus",
      slug: "math-multivariable-calculus",
      title: "Kalkulus Multivariabel",
      domain: "math",
      stage: "scholar",
      phase: "v1.1",
      level: 3,
      description: "Turunan parsial, gradien medan skalar, dan integral lipat pada permukaan 3D.",
      xp: 160,
      isAvailable: false,
      position: { x: 860, y: 1060 },
    },

    // Track 4: Geometri & Logika Formal (Geometry & Discrete Logic)
    {
      id: "math-logic-prop",
      slug: "math-logic-prop",
      title: "Logika Proposisional",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Tabel kebenaran, implikasi logis, dan penalaran deduktif formal.",
      xp: 65,
      isAvailable: false,
      position: { x: 1360, y: 60 },
    },
    {
      id: "math-euclidean-geometry",
      slug: "math-euclidean-geometry",
      title: "Geometri Euclid",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Aksioma bidang, sudut, segitiga, dan pembuktian visual Teorema Pythagoras.",
      xp: 70,
      isAvailable: false,
      position: { x: 1360, y: 240 },
    },
    {
      id: "math-trig-unit-circle",
      slug: "math-trig-unit-circle",
      title: "Lingkaran Satuan Trigonometri",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Proyeksi spasial sinus, kosinus, tangen, dan identitas Pythagoras pada lingkaran satuan.",
      xp: 100,
      isAvailable: true,
      route: "/topics/math-trig-unit-circle",
      position: { x: 1360, y: 440 },
    },
  ],
  edges: [
    // Track 1
    { id: "e-real-clock", source: "math-real-numbers", target: "arithmetic-modular-clock" },
    { id: "e-real-euclid", source: "math-real-numbers", target: "math-euclid" },
    { id: "e-clock-prime", source: "arithmetic-modular-clock", target: "math-prime-factorization" },
    { id: "e-euclid-prime", source: "math-euclid", target: "math-prime-factorization" },
    { id: "e-prime-crypto", source: "math-prime-factorization", target: "math-cryptography" },

    // Track 2
    { id: "e-real-alg", source: "math-real-numbers", target: "math-elementary-algebra" },
    { id: "e-alg-det", source: "math-elementary-algebra", target: "linear-algebra-determinant-2d" },
    { id: "e-det-vectors", source: "linear-algebra-determinant-2d", target: "math-vector-spaces" },

    // Track 3
    { id: "e-alg-func", source: "math-elementary-algebra", target: "math-functions-graphs" },
    { id: "e-func-limits", source: "math-functions-graphs", target: "math-limits-continuity" },
    { id: "e-limits-diff", source: "math-limits-continuity", target: "math-differential-calculus" },
    { id: "e-diff-integ", source: "math-differential-calculus", target: "math-integral-calculus" },
    { id: "e-vectors-multi", source: "math-vector-spaces", target: "math-multivariable-calculus" },
    { id: "e-integ-multi", source: "math-integral-calculus", target: "math-multivariable-calculus" },

    // Track 4
    { id: "e-logic-geo", source: "math-logic-prop", target: "math-euclidean-geometry" },
    { id: "e-geo-trig", source: "math-euclidean-geometry", target: "math-trig-unit-circle" },
  ],
};
