import { CurriculumTreeData } from "./types";

export const mathTreeData: CurriculumTreeData = {
  nodes: [
    // ═══════════════════════════════════════════════════════
    // TRACK 1: Bilangan & Kriptografi (Number Theory)
    // ═══════════════════════════════════════════════════════
    {
      id: "math-real-numbers",
      slug: "math-real-numbers-line",
      title: "Operasi Bilangan Riil",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Fondasi bilangan bulat, pecahan, rasio, garis bilangan, dan operasi translasi/dilatasi.",
      xp: 100,
      isAvailable: true,
      route: "/topics/math-real-numbers-line",
      position: { x: 300, y: 60 },
    },
    {
      id: "arithmetic-modular-clock",
      slug: "arithmetic-modular-clock",
      title: "Aritmetika Jam (Modulo)",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Modulo sebagai rotasi jam dinding, sisa bagi siklis, pola kardioid, dan generator prima.",
      xp: 120,
      isAvailable: true,
      route: "/topics/arithmetic-modular-clock",
      position: { x: 120, y: 240 },
    },
    {
      id: "math-euclid",
      slug: "math-euclid",
      title: "Algoritma Euclid & FPB",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Pengubinan persegi panjang, FPB, KPK, Identitas Bézout, dan kasus terburuk Fibonacci.",
      xp: 110,
      isAvailable: true,
      route: "/topics/math-euclid",
      position: { x: 480, y: 240 },
    },
    {
      id: "math-prime-factorization",
      slug: "math-primes-coprime",
      title: "Faktorisasi Prima & Koprima",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Teorema dasar aritmetika, Eratosthenes, koprima, fungsi Euler, dan Teorema Fermat.",
      xp: 130,
      isAvailable: true,
      route: "/topics/math-primes-coprime",
      position: { x: 300, y: 420 },
    },
    {
      id: "math-cryptography",
      slug: "math-cryptography",
      title: "Kriptografi Modern",
      domain: "math",
      stage: "scholar",
      phase: "v2.0",
      level: 3,
      description: "Kunci publik RSA, pertukaran Diffie-Hellman, dan kurva eliptik.",
      xp: 180,
      isAvailable: false,
      position: { x: 300, y: 600 },
    },

    // ═══════════════════════════════════════════════════════
    // TRACK 2: Aljabar & Linear Algebra
    // ═══════════════════════════════════════════════════════
    {
      id: "math-elementary-algebra",
      slug: "math-elementary-algebra",
      title: "Aljabar Elementer",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Persamaan linear, sistem persamaan, pertidaksamaan, dan timbangan logika.",
      xp: 60,
      isAvailable: false,
      position: { x: 720, y: 240 },
    },
    {
      id: "linear-algebra-determinant-2d",
      slug: "linear-algebra-determinant-2d",
      title: "Determinan Matriks 2D",
      domain: "math",
      stage: "scholar",
      phase: "mvp",
      level: 3,
      description: "Faktor skala luas spasial, singularitas, dan orientasi transformasi matriks.",
      xp: 120,
      isAvailable: true,
      route: "/topics/linear-algebra-determinant-2d",
      position: { x: 720, y: 420 },
    },
    {
      id: "math-vector-spaces",
      slug: "math-vector-spaces",
      title: "Ruang Vektor",
      domain: "math",
      stage: "scholar",
      phase: "v1.1",
      level: 3,
      description: "Kombinasi linear, kebebasan linear, basis, dan dimensi ruang vektor.",
      xp: 140,
      isAvailable: false,
      position: { x: 720, y: 600 },
    },

    // ═══════════════════════════════════════════════════════
    // TRACK 3: Fungsi & Kalkulus
    // ═══════════════════════════════════════════════════════
    {
      id: "math-functions-graphs",
      slug: "math-functions-graphs",
      title: "Fungsi & Grafik",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Domain kodomain, transformasi fungsi, dan jenis-jenis kurva.",
      xp: 90,
      isAvailable: false,
      position: { x: 960, y: 240 },
    },
    {
      id: "math-limits-continuity",
      slug: "math-limits-continuity",
      title: "Limit & Kekontinuan",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Intuisi limit, limit tak hingga, dan titik diskontinuitas.",
      xp: 100,
      isAvailable: false,
      position: { x: 960, y: 420 },
    },
    {
      id: "math-differential-calculus",
      slug: "math-calculus-tangent",
      title: "Kalkulus Diferensial",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Garis singgung, laju perubahan sesaat, dan optimasi nilai ekstrem.",
      xp: 120,
      isAvailable: true,
      route: "/topics/math-calculus-tangent",
      position: { x: 960, y: 600 },
    },
    {
      id: "math-integral-calculus",
      slug: "math-calculus-riemann",
      title: "Kalkulus Integral",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Akumulasi luas di bawah kurva, Riemann sum, dan teorema dasar kalkulus.",
      xp: 130,
      isAvailable: true,
      route: "/topics/math-calculus-riemann",
      position: { x: 960, y: 780 },
    },
    {
      id: "math-multivariable-calculus",
      slug: "math-multivariable-calculus",
      title: "Kalkulus Multivariabel",
      domain: "math",
      stage: "scholar",
      phase: "v1.1",
      level: 3,
      description: "Turunan parsial, gradien, dan integral lipat pada permukaan 3D.",
      xp: 160,
      isAvailable: false,
      position: { x: 960, y: 960 },
    },

    // ═══════════════════════════════════════════════════════
    // TRACK 4: Geometri & Logika
    // ═══════════════════════════════════════════════════════
    {
      id: "math-logic-prop",
      slug: "math-logic-prop",
      title: "Logika Proposisional",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Tabel kebenaran, implikasi, kontraposisi, dan gerbang logika.",
      xp: 65,
      isAvailable: false,
      position: { x: 1260, y: 60 },
    },
    {
      id: "math-euclidean-geometry",
      slug: "math-euclidean-geometry",
      title: "Geometri Euclid",
      domain: "math",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Aksioma bidang, sudut, segitiga, dan pembuktian visual Pythagoras.",
      xp: 70,
      isAvailable: false,
      position: { x: 1260, y: 240 },
    },
    {
      id: "math-trig-unit-circle",
      slug: "math-trig-unit-circle",
      title: "Trigonometri Lingkaran Satuan",
      domain: "math",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Sinus, kosinus, tangen, identitas, dan proyeksi spasial pada lingkaran satuan.",
      xp: 100,
      isAvailable: true,
      route: "/topics/math-trig-unit-circle",
      position: { x: 1260, y: 420 },
    },
  ],

  edges: [
    // Track 1: Bilangan & Kriptografi
    { id: "e-real-clock", source: "math-real-numbers", target: "arithmetic-modular-clock" },
    { id: "e-real-euclid", source: "math-real-numbers", target: "math-euclid" },
    { id: "e-clock-prime", source: "arithmetic-modular-clock", target: "math-prime-factorization" },
    { id: "e-euclid-prime", source: "math-euclid", target: "math-prime-factorization" },
    { id: "e-prime-crypto", source: "math-prime-factorization", target: "math-cryptography" },

    // Track 2: Aljabar
    { id: "e-real-alg", source: "math-real-numbers", target: "math-elementary-algebra" },
    { id: "e-alg-det", source: "math-elementary-algebra", target: "linear-algebra-determinant-2d" },
    { id: "e-det-vectors", source: "linear-algebra-determinant-2d", target: "math-vector-spaces" },

    // Track 3: Kalkulus
    { id: "e-alg-func", source: "math-elementary-algebra", target: "math-functions-graphs" },
    { id: "e-func-limits", source: "math-functions-graphs", target: "math-limits-continuity" },
    { id: "e-limits-diff", source: "math-limits-continuity", target: "math-differential-calculus" },
    { id: "e-diff-integ", source: "math-differential-calculus", target: "math-integral-calculus" },
    { id: "e-integ-multi", source: "math-integral-calculus", target: "math-multivariable-calculus" },
    { id: "e-vectors-multi", source: "math-vector-spaces", target: "math-multivariable-calculus" },

    // Track 4: Geometri
    { id: "e-logic-geo", source: "math-logic-prop", target: "math-euclidean-geometry" },
    { id: "e-geo-trig", source: "math-euclidean-geometry", target: "math-trig-unit-circle" },

    // Cross-track connections
    { id: "e-prime-det", source: "math-prime-factorization", target: "linear-algebra-determinant-2d", label: "modular arithmetic" },
    { id: "e-trig-wave", source: "math-trig-unit-circle", target: "math-integral-calculus", label: "sin/cos integration" },
  ],
};
