import { CurriculumTreeData } from "./types";

export const scienceTreeData: CurriculumTreeData = {
  nodes: [
    // Root: Metode Ilmiah
    {
      id: "sci-scientific-method",
      slug: "sci-scientific-method",
      title: "Metode Ilmiah",
      domain: "physics",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Siklus observasi, perumusan hipotesis, eksperimen terkontrol, dan falsifikasi.",
      xp: 50,
      isAvailable: false,
      position: { x: 480, y: 60 },
    },

    // Track 1: Fisika Mekanika & Gelombang (Physics)
    {
      id: "sci-units-measurements",
      slug: "sci-units-measurements",
      title: "Besaran & Satuan",
      domain: "physics",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Dimensi SI, analisis ketidakpastian pengukuran, dan angka penting.",
      xp: 50,
      isAvailable: false,
      position: { x: 60, y: 220 },
    },
    {
      id: "sci-kinematics",
      slug: "sci-kinematics",
      title: "Kinematika Gerak",
      domain: "physics",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Posisi, kecepatan, percepatan, dan grafik gerak lurus beraturan dan berubah beraturan.",
      xp: 80,
      isAvailable: true,
      route: "/topics/physics-projectile-motion",
      position: { x: 60, y: 440 },
    },
    {
      id: "sci-dynamics-newton",
      slug: "sci-dynamics-newton",
      title: "Dinamika & Hukum Newton",
      domain: "physics",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Hukum I, II, III Newton, diagram benda bebas, dan gaya gesek.",
      xp: 90,
      isAvailable: false,
      position: { x: 60, y: 660 },
    },
    {
      id: "sci-work-energy",
      slug: "sci-work-energy",
      title: "Usaha & Energi Mekanik",
      domain: "physics",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Teorema usaha-energi, energi potensial gravitasi dan pegas, serta hukum kekekalan.",
      xp: 100,
      isAvailable: false,
      position: { x: 60, y: 860 },
    },
    {
      id: "sci-circuits-electricity",
      slug: "sci-circuits-electricity",
      title: "Rangkaian Listrik DC",
      domain: "physics",
      stage: "navigator",
      phase: "v1.1",
      level: 2,
      description: "Hukum Ohm, hukum Kirchhoff, hambatan seri & paralel, dan daya listrik.",
      xp: 115,
      isAvailable: false,
      position: { x: 60, y: 1060 },
    },
    {
      id: "sci-simple-harmonic",
      slug: "sci-simple-harmonic",
      title: "Osilasi & Gelombang",
      domain: "physics",
      stage: "scholar",
      phase: "v1.1",
      level: 3,
      description: "Gerak harmonik sederhana bandul dan pegas, interferensi, serta efek Doppler.",
      xp: 130,
      isAvailable: false,
      position: { x: 340, y: 1060 },
    },

    // Track 2: Kimia Struktur & Reaksi (Chemistry)
    {
      id: "sci-atomic-structure",
      slug: "sci-atomic-structure",
      title: "Struktur Atom & Periodik",
      domain: "chemistry",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Proton, neutron, elektron, orbital, dan periodisitas sifat unsur tabel periodik.",
      xp: 75,
      isAvailable: false,
      position: { x: 480, y: 220 },
    },
    {
      id: "sci-chemical-bonds",
      slug: "sci-chemical-bonds",
      title: "Ikatan Kimia",
      domain: "chemistry",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Ikatan kovalen, ionik, logam, dan gaya antarmolekul penentu wujud zat.",
      xp: 85,
      isAvailable: false,
      position: { x: 480, y: 440 },
    },
    {
      id: "sci-stoichiometry",
      slug: "sci-stoichiometry",
      title: "Stoikiometri",
      domain: "chemistry",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Konsep mol, hukum kekekalan massa Lavoisier, dan reaksi pembatas.",
      xp: 95,
      isAvailable: false,
      position: { x: 480, y: 660 },
    },

    // Track 3: Biologi Kehidupan & Genetika (Biology)
    {
      id: "sci-cells-organelles",
      slug: "sci-cells-organelles",
      title: "Sel & Organel",
      domain: "biology",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Membran sel, transport pasif & aktif, mitokondria, dan kloroplas.",
      xp: 70,
      isAvailable: false,
      position: { x: 900, y: 220 },
    },
    {
      id: "sci-biomolecules",
      slug: "sci-biomolecules",
      title: "Biomolekul & Metabolisme",
      domain: "biology",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Karbohidrat, lipid, protein, respirasi seluler, dan fotosintesis.",
      xp: 85,
      isAvailable: false,
      position: { x: 900, y: 440 },
    },
    {
      id: "sci-dna-genetics",
      slug: "sci-dna-genetics",
      title: "Genetika & DNA",
      domain: "biology",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Struktur heliks ganda DNA, hukum pemisahan Mendel, dan mutasi ekspresi gen.",
      xp: 110,
      isAvailable: false,
      position: { x: 900, y: 660 },
    },
  ],
  edges: [
    { id: "e-meth-unit", source: "sci-scientific-method", target: "sci-units-measurements" },
    { id: "e-meas-kin", source: "sci-units-measurements", target: "sci-kinematics" },
    { id: "e-kin-dyn", source: "sci-kinematics", target: "sci-dynamics-newton" },
    { id: "e-dyn-work", source: "sci-dynamics-newton", target: "sci-work-energy" },
    { id: "e-work-circ", source: "sci-work-energy", target: "sci-circuits-electricity" },
    { id: "e-work-harm", source: "sci-work-energy", target: "sci-simple-harmonic" },

    { id: "e-meth-atom", source: "sci-scientific-method", target: "sci-atomic-structure" },
    { id: "e-atom-bond", source: "sci-atomic-structure", target: "sci-chemical-bonds" },
    { id: "e-bond-stoi", source: "sci-chemical-bonds", target: "sci-stoichiometry" },

    { id: "e-meth-cell", source: "sci-scientific-method", target: "sci-cells-organelles" },
    { id: "e-cell-bio", source: "sci-cells-organelles", target: "sci-biomolecules" },
    { id: "e-bio-dna", source: "sci-biomolecules", target: "sci-dna-genetics" },

    // Biochemistry bridge: Kimia (480) -> adjacent Biologi (900)
    { id: "e-atom-bio", source: "sci-atomic-structure", target: "sci-biomolecules" },
  ],
};
