import { CurriculumTreeData } from "./types";

export const scienceTreeData: CurriculumTreeData = {
  nodes: [
    // ═══════════════════════════════════════════════════════
    // ROOT: Metode Ilmiah
    // ═══════════════════════════════════════════════════════
    {
      id: "sci-scientific-method",
      slug: "sci-scientific-method",
      title: "Metode Ilmiah",
      domain: "physics",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Siklus observasi, hipotesis, eksperimen terkontrol, dan falsifikasi.",
      xp: 50,
      isAvailable: false,
      position: { x: 480, y: 60 },
    },

    // ═══════════════════════════════════════════════════════
    // TRACK 1: Fisika — Mekanika & Gelombang
    // ═══════════════════════════════════════════════════════
    {
      id: "sci-units-measurements",
      slug: "sci-units-measurements",
      title: "Besaran & Satuan",
      domain: "physics",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Dimensi SI, analisis ketidakpastian, dan angka penting.",
      xp: 50,
      isAvailable: false,
      position: { x: 120, y: 220 },
    },
    {
      id: "sci-kinematics",
      slug: "physics-projectile-motion",
      title: "Kinematika Gerak",
      domain: "physics",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Posisi, kecepatan, percepatan, grafik gerak, dan proyektil parabola.",
      xp: 80,
      isAvailable: true,
      route: "/topics/physics-projectile-motion",
      position: { x: 120, y: 400 },
    },
    {
      id: "sci-dynamics-newton",
      slug: "physics-newton-incline",
      title: "Dinamika & Hukum Newton",
      domain: "physics",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Hukum I, II, III Newton, diagram benda bebas, dan gaya gesek bidang miring.",
      xp: 90,
      isAvailable: true,
      route: "/topics/physics-newton-incline",
      position: { x: 120, y: 580 },
    },
    {
      id: "sci-work-energy",
      slug: "physics-roller-coaster",
      title: "Usaha & Energi Mekanik",
      domain: "physics",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Teorema usaha-energi, energi potensial, kekekalan, dan loop-the-loop.",
      xp: 100,
      isAvailable: true,
      route: "/topics/physics-roller-coaster",
      position: { x: 120, y: 760 },
    },
    {
      id: "sci-electric-field",
      slug: "physics-electric-field",
      title: "Medan & Gaya Listrik",
      domain: "physics",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Hukum Coulomb, vektor medan listrik E, potensial elektrostatik, dan dipole.",
      xp: 110,
      isAvailable: true,
      route: "/topics/physics-electric-field",
      position: { x: 120, y: 940 },
    },
    {
      id: "sci-circuits-electricity",
      slug: "physics-dc-circuits",
      title: "Rangkaian Listrik DC",
      domain: "physics",
      stage: "scholar",
      phase: "mvp",
      level: 3,
      description: "Hukum Ohm, hambatan seri-paralel, daya P=VI, dan aliran arus.",
      xp: 115,
      isAvailable: true,
      route: "/topics/physics-dc-circuits",
      position: { x: 120, y: 1120 },
    },
    {
      id: "sci-simple-harmonic",
      slug: "physics-harmonic-oscillator",
      title: "Osilasi Harmonik",
      domain: "physics",
      stage: "scholar",
      phase: "mvp",
      level: 3,
      description: "Gerak harmonik bandul dan pegas, periode, frekuensi, dan energi osilasi.",
      xp: 130,
      isAvailable: true,
      route: "/topics/physics-harmonic-oscillator",
      position: { x: 400, y: 940 },
    },
    {
      id: "sci-wave-simulator",
      slug: "physics-wave-simulator",
      title: "Simulator Gelombang",
      domain: "physics",
      stage: "scholar",
      phase: "mvp",
      level: 3,
      description: "Perambatan gelombang transversal/longitudinal, v=λf, superposisi, dan interferensi.",
      xp: 125,
      isAvailable: true,
      route: "/topics/physics-wave-simulator",
      position: { x: 400, y: 1120 },
    },

    // ═══════════════════════════════════════════════════════
    // TRACK 2: Kimia — Struktur & Reaksi
    // ═══════════════════════════════════════════════════════
    {
      id: "sci-atomic-structure",
      slug: "sci-atomic-structure",
      title: "Struktur Atom & Periodik",
      domain: "chemistry",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Proton, neutron, elektron, orbital, dan periodisitas tabel periodik.",
      xp: 75,
      isAvailable: false,
      position: { x: 720, y: 220 },
    },
    {
      id: "sci-chemical-bonds",
      slug: "sci-chemical-bonds",
      title: "Ikatan Kimia",
      domain: "chemistry",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Ikatan kovalen, ionik, logam, dan gaya antarmolekul.",
      xp: 85,
      isAvailable: false,
      position: { x: 720, y: 400 },
    },
    {
      id: "sci-stoichiometry",
      slug: "sci-stoichiometry",
      title: "Stoikiometri",
      domain: "chemistry",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Konsep mol, kekekalan massa Lavoisier, dan reaksi pembatas.",
      xp: 95,
      isAvailable: false,
      position: { x: 720, y: 580 },
    },

    // ═══════════════════════════════════════════════════════
    // TRACK 3: Biologi — Kehidupan & Genetika
    // ═══════════════════════════════════════════════════════
    {
      id: "sci-cells-organelles",
      slug: "sci-cells-organelles",
      title: "Sel & Organel",
      domain: "biology",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Membran sel, transport pasif/aktif, mitokondria, dan kloroplas.",
      xp: 70,
      isAvailable: false,
      position: { x: 1020, y: 220 },
    },
    {
      id: "sci-biomolecules",
      slug: "sci-biomolecules",
      title: "Biomolekul & Metabolisme",
      domain: "biology",
      stage: "explorer",
      phase: "mvp",
      level: 1,
      description: "Karbohidrat, lipid, protein, respirasi seluler, dan fotosintesis.",
      xp: 85,
      isAvailable: false,
      position: { x: 1020, y: 400 },
    },
    {
      id: "sci-dna-genetics",
      slug: "sci-dna-genetics",
      title: "Genetika & DNA",
      domain: "biology",
      stage: "navigator",
      phase: "mvp",
      level: 2,
      description: "Heliks ganda DNA, hukum Mendel, mutasi, dan ekspresi gen.",
      xp: 110,
      isAvailable: false,
      position: { x: 1020, y: 580 },
    },
  ],

  edges: [
    // Track 1: Fisika
    { id: "e-meth-unit", source: "sci-scientific-method", target: "sci-units-measurements" },
    { id: "e-meas-kin", source: "sci-units-measurements", target: "sci-kinematics" },
    { id: "e-kin-dyn", source: "sci-kinematics", target: "sci-dynamics-newton" },
    { id: "e-dyn-work", source: "sci-dynamics-newton", target: "sci-work-energy" },
    { id: "e-work-efield", source: "sci-work-energy", target: "sci-electric-field" },
    { id: "e-efield-circ", source: "sci-electric-field", target: "sci-circuits-electricity" },
    { id: "e-work-harm", source: "sci-work-energy", target: "sci-simple-harmonic" },
    { id: "e-harm-wave", source: "sci-simple-harmonic", target: "sci-wave-simulator" },

    // Track 2: Kimia
    { id: "e-meth-atom", source: "sci-scientific-method", target: "sci-atomic-structure" },
    { id: "e-atom-bond", source: "sci-atomic-structure", target: "sci-chemical-bonds" },
    { id: "e-bond-stoi", source: "sci-chemical-bonds", target: "sci-stoichiometry" },

    // Track 3: Biologi
    { id: "e-meth-cell", source: "sci-scientific-method", target: "sci-cells-organelles" },
    { id: "e-cell-bio", source: "sci-cells-organelles", target: "sci-biomolecules" },
    { id: "e-bio-dna", source: "sci-biomolecules", target: "sci-dna-genetics" },

    // Cross-track: Kimia → Biologi
    { id: "e-atom-bio", source: "sci-atomic-structure", target: "sci-biomolecules", label: "molecular basis" },
  ],
};
