import { CurriculumTreeData } from "./types";

export const softskillsTreeData: CurriculumTreeData = {
  nodes: [
    // A: Critical Thinking
    {
      id: "soft-argument-anatomy",
      slug: "soft-argument-anatomy",
      title: "Anatomi Argumen",
      domain: "softskill",
      stage: "explorer",
      phase: "v1.1",
      level: 1,
      description: "Premis, kesimpulan, perbedaan argumen valid vs sound, dan silogisme penalaran.",
      xp: 40,
      isAvailable: false,
      position: { x: 100, y: 50 },
    },
    {
      id: "soft-fallacy-spotter",
      slug: "soft-fallacy-spotter",
      title: "Katalog Kekeliruan Logika",
      domain: "softskill",
      stage: "explorer",
      phase: "v1.1",
      level: 1,
      description: "Mengenali ad hominem, strawman, false dichotomy, dan sesat pikir argumentasi.",
      xp: 55,
      isAvailable: false,
      position: { x: 100, y: 200 },
    },
    {
      id: "soft-decomposition",
      slug: "soft-decomposition",
      title: "Dekomposisi Masalah",
      domain: "softskill",
      stage: "explorer",
      phase: "v1.1",
      level: 1,
      description: "Memecah persoalan besar menjadi sub-masalah independen yang terkelola.",
      xp: 50,
      isAvailable: false,
      position: { x: 350, y: 50 },
    },
    {
      id: "soft-fermi-problems",
      slug: "soft-fermi-problems",
      title: "Estimasi Fermi",
      domain: "softskill",
      stage: "navigator",
      phase: "v2.0",
      level: 2,
      description: "Berpikir kuantitatif berbasis orde besaran dan batas atas/bawah tanpa data presisi.",
      xp: 75,
      isAvailable: false,
      position: { x: 350, y: 200 },
    },
    // B: Data Literacy
    {
      id: "soft-graph-literacy",
      slug: "soft-graph-literacy",
      title: "Anatomi Grafik",
      domain: "softskill",
      stage: "explorer",
      phase: "v1.1",
      level: 1,
      description: "Membaca sumbu, skala linear vs logaritmik, dan mendeteksi grafik yang menyesatkan.",
      xp: 60,
      isAvailable: false,
      position: { x: 600, y: 50 },
    },
    {
      id: "soft-correlation-causation",
      slug: "soft-correlation-causation",
      title: "Korelasi vs Kausalitas",
      domain: "softskill",
      stage: "navigator",
      phase: "v1.1",
      level: 2,
      description: "Menghindari bias korelasi spurious dan memahami variabel perancu (confounding).",
      xp: 70,
      isAvailable: false,
      position: { x: 600, y: 200 },
    },
    // F: Learning Strategies
    {
      id: "soft-growth-mindset",
      slug: "soft-growth-mindset",
      title: "Growth Mindset",
      domain: "softskill",
      stage: "explorer",
      phase: "v1.1",
      level: 1,
      description: "Membangun ketahanan belajar matematika tanpa rasa cemas dan takut salah.",
      xp: 45,
      isAvailable: false,
      position: { x: 850, y: 50 },
    },
    {
      id: "soft-spaced-repetition",
      slug: "soft-spaced-repetition",
      title: "Recall Aktif & Feynman",
      domain: "softskill",
      stage: "navigator",
      phase: "v1.1",
      level: 2,
      description: "Teknik mengajarkan konsep dengan bahasa sederhana dan repetisi terencana.",
      xp: 65,
      isAvailable: false,
      position: { x: 850, y: 200 },
    },
    {
      id: "soft-ai-ethics",
      slug: "soft-ai-ethics",
      title: "Etika Kecerdasan Buatan",
      domain: "softskill",
      stage: "scholar",
      phase: "v2.0",
      level: 3,
      description: "Bias algoritma, transparansi model, dan tanggung jawab sosial pemodelan AI.",
      xp: 90,
      isAvailable: false,
      position: { x: 600, y: 350 },
    },
  ],
  edges: [
    { id: "e-arg-fallacy", source: "soft-argument-anatomy", target: "soft-fallacy-spotter" },
    { id: "e-decomp-fermi", source: "soft-decomposition", target: "soft-fermi-problems" },
    { id: "e-graph-corr", source: "soft-graph-literacy", target: "soft-correlation-causation" },
    { id: "e-corr-ai", source: "soft-correlation-causation", target: "soft-ai-ethics" },
    { id: "e-mindset-spaced", source: "soft-growth-mindset", target: "soft-spaced-repetition" },
  ],
};
