import { TopicModule } from "@/types/topic";

export const modularClockModule: TopicModule = {
  id: "math-nt-01",
  slug: "arithmetic-modular-clock",
  title: "Aritmetika Jam (Modulo) & Siklus Bilangan",
  category: "math",
  summary:
    "Bayangkan bilangan yang bergerak melingkar seperti jarum jam dinding. Aritmetika modular mengajarkan bahwa bilangan tidak harus selalu bertambah tanpa batas, melainkan berulang dalam siklus teratur yang melahirkan invers modular, enkripsi data perbankan, dan seni geometri kardioid menakjubkan.",
  audioNarrationText:
    "Selamat datang di modul Aritmetika Jam dan Teori Bilangan Elementer. Di sini kamu akan memahami operasi modulo secara intuitif layaknya waktu pada jam dinding hingga membuka gerbang kriptografi modern.",
  initialVariables: {
    n: 12,
    multiplier: 2,
    hourA: 9,
    hourB: 7,
  },
  levels: [
    {
      id: "clock-level-1",
      index: 1,
      tier: 1,
      title: "Konsep Dasar Modulo & Sisa Bagi",
      description: "Memahami bilangan bulat sebagai perputaran siklis pada jam dinding.",
      ahaMoment: "Jika garis bilangan digulung pada lingkaran, angka 12 dan angka 0 berada di tempat yang sama!",
      steps: [
        {
          id: "c1-s1",
          type: "provoke",
          title: "Teka-Teki Jam Dinding",
          naiExpression: "curious",
          naiDialogue: "Sekarang pukul 9. Jika kita menunggu 5 jam lagi, mengapa kita tidak menyebutnya pukul 14?",
          provoke: {
            hookTitle: "Teka-Teki Jam Dinding",
            hookText: "Pada jam analog biasa, jarum jam hanya memiliki angka 1 sampai 12. Setelah melewati angka 12, putaran kembali mengulang dari awal.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 12, hourA: 9, hourB: 5, multiplier: 2 },
            question: "Mengapa kita menyebut 9 + 5 sebagai pukul 2 di jam dinding biasa?",
            options: [
              {
                id: "opt-cycle",
                text: "Karena setelah 12, hitungan jam berulang kembali ke sisa putarannya (14 - 12 = 2)",
                responseText: "Tepat sekali! Inilah konsep inti dari aritmetika modular: perulangan siklis dengan sisa pembagian.",
              },
              {
                id: "opt-broken",
                text: "Karena jam dinding tidak bisa berputar lebih dari 12 jam.",
                responseText: "Jarum jam tetap berputar terus tanpa henti, tetapi posisinya berulang setiap 12 jam sekali.",
              },
            ],
          },
        },
        {
          id: "c1-s2",
          type: "predict",
          title: "Di Mana Jarum Berhenti?",
          naiExpression: "thinking",
          naiDialogue: "Pada lingkaran modulo 7, jika kita melompat 16 langkah dari posisi 5, di mana jarum berhenti?",
          predict: {
            scenarioTitle: "Lompatan Siklus Modulo 7",
            scenarioText: "Lingkaran modulus bernilai m = 7 (angka 0 sampai 6). Jarum berada di 5 dan melangkah maju 16 langkah.",
            question: "Di angka berapakah jarum jam akan berhenti?",
            options: [
              {
                id: "pred-0",
                text: "0",
                isCorrect: true,
                feedback: "Benar! Posisi awal 5 + 16 langkah = 21. Karena 21 adalah kelipatan tepat dari 7 (21 = 3 × 7), sisa baginya adalah 0!",
              },
              {
                id: "pred-2",
                text: "2",
                isCorrect: false,
                feedback: "16 mod 7 memang 2, tetapi posisi awal jarum berada di 5, sehingga (5 + 16) mod 7 = 21 mod 7 = 0.",
              },
              {
                id: "pred-5",
                text: "5",
                isCorrect: false,
                feedback: "16 langkah memutar jarum lebih dari 2 putaran penuh.",
              },
            ],
            simulationLabel: "Putar Jarum Jam!",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 7, hourA: 5, hourB: 0, multiplier: 2 },
            simulationVariables: { n: 7, hourA: 5, hourB: 2, multiplier: 2 },
          },
        },
        {
          id: "c1-s3",
          type: "guided",
          title: "Menggulung Garis Lurus: Jam Modulo",
          naiExpression: "happy",
          naiDialogue: "Geser nilai jam A dan B untuk mengamati bagaimana garis bilangan tak hingga digulung rapi!",
          guided: {
            instructionTitle: "Laboratorium Sisa Pembagian Modular",
            instructionText: "Ubah nilai jam A dan B pada jam modulo 12 untuk melihat hasil perputaran jarum jam.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 12, hourA: 9, hourB: 7, multiplier: 2 },
            observationTable: {
              headers: ["Total Jam A + B", "Banyak Putaran 12", "Posisi Akhir Jarum"],
              rows: [
                { parameter: "9 + 7 = 16", expectedValue: "1 putaran", unit: "sisa 4" },
                { parameter: "10 + 15 = 25", expectedValue: "2 putaran", unit: "sisa 1" },
              ],
            },
            discoveryQuestion: {
              prompt: "Apa sebenarnya makna dari hasil operasi bilangan a mod m?",
              options: [
                "Sisa pembagian bilangan a setelah dibagi oleh modulus m",
                "Hasil bagi bilangan a dibagi m",
                "Kelipatan terbesar dari bilangan m",
              ],
              correctOption: "Sisa pembagian bilangan a setelah dibagi oleh modulus m",
              insight: "Modulo mengukur posisi sisa putaran: a = q · m + r dengan 0 ≤ r < m.",
            },
          },
        },
        {
          id: "c1-s4",
          type: "formalize",
          title: "Notasi Modulo & Relasi Kongruensi",
          naiExpression: "neutral",
          naiDialogue: "Mari tuangkan konsep perputaran jam ini ke dalam simbol resmi teori bilangan.",
          formalize: {
            title: "Notasi Modulo & Kongruensi",
            prompt: "Lengkapi kesimpulan matematis relasi kongruensi berikut:",
            formulaTemplate: "16 \\pmod{12} = [blank1] \\quad \\text{dan} \\quad a \\equiv b \\pmod m \\iff m \\mid [blank2]",
            blanks: [
              { id: "blank1", label: "Nilai Sisa", options: ["4", "2", "6"], correctOption: "4" },
              { id: "blank2", label: "Syarat Kongruen", options: ["(a - b)", "(a + b)", "(a \\times b)"], correctOption: "(a - b)" },
            ],
            resolvedFormulaKaTeX: "16 \\pmod{12} = 4 \\quad \\text{dan} \\quad a \\equiv b \\pmod m \\iff m \\mid (a - b)",
            explanation: "Dua bilangan disebut kongruen jika selisih keduanya habis dibagi oleh modulus m (artinya keduanya mendarat di posisi jam yang persis sama).",
          },
        },
        {
          id: "c1-s5",
          type: "check",
          title: "Cek Kilat Kongruensi",
          naiExpression: "thinking",
          naiDialogue: "Uji kejelianmu memeriksa sisa pembagian pada jam dinding!",
          check: {
            question: "Manakah dari bilangan berikut yang TIDAK kongruen dengan 3 (mod 4)?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-18", text: "18", isCorrect: true, explanation: "Tepat! 18 mod 4 = 2, bukan 3. Sedangkan 7, 11, 15, dan 23 semuanya bersisa 3 jika dibagi 4." },
              { id: "opt-7", text: "7 (7 = 1 × 4 + 3)", isCorrect: false, explanation: "7 bersisa 3, jadi kongruen." },
              { id: "opt-15", text: "15 (15 = 3 × 4 + 3)", isCorrect: false, explanation: "15 bersisa 3, jadi kongruen." },
            ],
            explanation: "18 = 4 × 4 + 2 ≡ 2 (mod 4), sehingga tidak sekongruen dengan 3.",
          },
        },
        {
          id: "c1-s6",
          type: "sandbox",
          title: "Playground Jam Dinding Bebas",
          naiExpression: "happy",
          naiDialogue: "Putar jam sesukamu dan amati bagaimana warna dan sisa bagi berubah.",
          sandbox: {
            title: "Simulasi Jam Dinding Interaktif",
            instructions: "Geser nilai jam A dan jam B untuk mengamati posisi jarum jam dan sisa bagi mod 12.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 12, hourA: 9, hourB: 7, multiplier: 2 },
          },
        },
        {
          id: "c1-s7",
          type: "challenge",
          title: "Misi: Jam Menunjuk Angka Berapa?",
          naiExpression: "neutral",
          naiDialogue: "Atur jam A = 9 dan jam B = 7 pada jam modulo 12. Sisa baginya harus menghasilkan angka 4!",
          challenge: {
            id: "challenge-clock-addition",
            title: "Penjumlahan Modular Jam 12",
            question:
              "Atur jam A = 9 dan jam B = 7 pada jam modulo 12. Berapakah sisa bagi posisi jarum jam (Target: hasil = 4)?",
            targetCondition: (vars) => {
              const n = vars.n || 12;
              const res = (((vars.hourA || 0) + (vars.hourB || 0)) % n + n) % n;
              return n === 12 && res === 4;
            },
            hint1Static: "Hitung total jam terlebih dahulu: 9 + 7 = 16.",
            hint2Static: "Kurangkan 16 dengan 12 (kelipatan lingkaran jam). Berapa sisanya?",
            solutionVariables: { n: 12, hourA: 9, hourB: 7 },
            solutionExplanation: "9 + 7 = 16. Dalam modulo 12: 16 = 1 x 12 + 4, sehingga sisa bagi adalah 4.",
            xpReward: 30,
          },
        },
        {
          id: "c1-s8",
          type: "reflect",
          title: "Refleksi Level 1: Lingkaran Siklis",
          naiExpression: "celebrating",
          naiDialogue: "Keren! Kamu sudah menguasai fondasi aritmetika jam modulo.",
          reflect: {
            title: "Level 1 Tuntas: Jam Modulo & Sisa Bagi",
            takeaways: [
              "Modulo memetakan garis bilangan tak hingga ke dalam siklus lingkaran berhingga.",
              "Hasil operasi a mod m selalu berada di antara 0 sampai m - 1.",
              "Dua bilangan kongruen a ≡ b (mod m) memiliki sisa bagi yang identik.",
            ],
            connectionText: "Di Level 2, kita akan menjinakkan angka-angka raksasa dengan penjumlahan & perkalian modular!",
            nextLevelTitle: "Level 2: Aritmetika Modular & Efisiensi",
            badgeToUnlock: "first-step",
            xpReward: 30,
            formulaKaTeX: "a \\pmod n = r \\quad (0 \\le r < n)",
          },
        },
      ],
    },
    {
      id: "clock-level-2",
      index: 2,
      tier: 1,
      title: "Aritmetika Modular & Efisiensi Angka Raksasa",
      description: "Operasi penjumlahan dan perkalian modular serta reduksi sebelum operasi.",
      ahaMoment: "Kamu bisa menyederhanakan angka SEBELUM menjumlahkan atau mengalikannya, hasilnya tetap sama persis!",
      steps: [
        {
          id: "c2-s1",
          type: "provoke",
          title: "Menghitung Angka Raksasa",
          naiExpression: "curious",
          naiDialogue: "Berapa digit terakhir dari 1234567 × 7654321? Apakah kamu harus mengalikan semuanya?",
          provoke: {
            hookTitle: "Digit Terakhir Perkalian Raksasa",
            hookText: "Komputer modern sering kali harus mengalikan angka ratusan digit untuk sistem keamanan perbankan.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 10, hourA: 7, hourB: 1, multiplier: 2 },
            question: "Bagaimana cara tercepat mencari digit terakhir (mod 10) dari 1234567 × 7654321?",
            options: [
              {
                id: "opt-last-digit",
                text: "Cukup kalikan digit terakhirnya: 7 × 1 = 7!",
                responseText: "Tepat sekali! Sisa bagi menjaga operasi perkalian. Kita tidak perlu menghitung angka raksasanya secara utuh.",
              },
              {
                id: "opt-calc",
                text: "Harus menggunakan kalkulator ilmiah 64-bit.",
                responseText: "Kurang tepat. Menghitung manual angka sebesar itu tidak efisien dan rentan overflow komputasi.",
              },
            ],
          },
        },
        {
          id: "c2-s2",
          type: "predict",
          title: "Sisa Sebelum vs Sisa Sesudah",
          naiExpression: "thinking",
          naiDialogue: "Apakah (14 + 18) mod 5 sama hasilnya jika kita modulo-kan dulu angkanya?",
          predict: {
            scenarioTitle: "Reduksi Aritmetika Modular",
            scenarioText: "Cara 1: (14 + 18) mod 5 = 32 mod 5 = 2. Cara 2: (14 mod 5) + (18 mod 5) = 4 + 3 = 7 mod 5 = 2.",
            question: "Apakah menyederhanakan angka sebelum operasi selalu menghasilkan jawaban yang sama?",
            options: [
              {
                id: "pred-always-same",
                text: "Pasti sama persis untuk penjumlahan dan perkalian apa pun",
                isCorrect: true,
                feedback: "Benar! Inilah sifat homomorfisma modular yang membuat perhitungan kriptografi super cepat.",
              },
              {
                id: "pred-diff",
                text: "Bisa berbeda jika angkanya terlalu besar",
                isCorrect: false,
                feedback: "Tidak pernah berbeda! Teorema modular menjamin konsistensi hasil.",
              },
            ],
            simulationLabel: "Uji Konsistensi!",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 5, hourA: 4, hourB: 3, multiplier: 2 },
            simulationVariables: { n: 5, hourA: 4, hourB: 3, multiplier: 2 },
          },
        },
        {
          id: "c2-s3",
          type: "guided",
          title: "Eksplorasi Kalender Modulo 7",
          naiExpression: "happy",
          naiDialogue: "Sistem 7 hari seminggu adalah contoh modulo alami yang kita temui setiap hari!",
          guided: {
            instructionTitle: "Simulasi Prediksi Hari Kalender",
            instructionText: "Ubah n menjadi 7, lalu variasikan jam A dan B untuk mensimulasikan pergeseran hari.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 7, hourA: 1, hourB: 2, multiplier: 3 },
            observationTable: {
              headers: ["Hari Ini", "Tambah Hari", "Hari Mendatang (mod 7)"],
              rows: [
                { parameter: "Selasa (1)", expectedValue: "+ 100 hari", unit: "Kamis (3)" },
                { parameter: "Jumat (4)", expectedValue: "+ 14 hari", unit: "Jumat (4)" },
              ],
            },
            discoveryQuestion: {
              prompt: "Mengapa menambah 14 hari tidak mengubah nama hari sama sekali?",
              options: [
                "Karena 14 adalah kelipatan tepat dari 7 (14 mod 7 = 0)",
                "Karena kalender berhenti di hari ke-14",
                "Hanya kebetulan",
              ],
              correctOption: "Karena 14 adalah kelipatan tepat dari 7 (14 mod 7 = 0)",
              insight: "Menambah kelipatan dari modulus setara dengan melangkah 0 di dunia modulo!",
            },
          },
        },
        {
          id: "c2-s4",
          type: "formalize",
          title: "Hukum Homomorfisma Modular",
          naiExpression: "neutral",
          naiDialogue: "Mari formulasikan sifat kekebalan operasi tambah dan kali terhadap modulo.",
          formalize: {
            title: "Hukum Operasi Modular",
            prompt: "Lengkapi sifat penjumlahan dan perkalian modular berikut:",
            formulaTemplate: "(a + b) \\pmod m \\equiv (a [blank1] b) \\pmod m \\quad \\text{dan} \\quad (a \\cdot b) \\pmod m \\equiv (a [blank2] b) \\pmod m",
            blanks: [
              { id: "blank1", label: "Reduksi Tambah", options: ["\\pmod m + \\dots", "\\times \\dots", "/ \\dots"], correctOption: "\\pmod m + \\dots" },
              { id: "blank2", label: "Reduksi Kali", options: ["\\pmod m \\cdot \\dots", "+ \\dots", "/ \\dots"], correctOption: "\\pmod m \\cdot \\dots" },
            ],
            resolvedFormulaKaTeX: "(a + b) \\pmod m \\equiv ((a \\pmod m) + (b \\pmod m)) \\pmod m",
            explanation: "Kita bebas mereduksi sisa bagi pada setiap tahapan perhitungan tanpa merusak hasil akhir.",
          },
        },
        {
          id: "c2-s5",
          type: "check",
          title: "Kuis Efisiensi Angka Besar",
          naiExpression: "thinking",
          naiDialogue: "Gunakan trik sisa bagi untuk menghitung soal ini dalam sekejap!",
          check: {
            question: "Berapakah sisa bagi dari 99 × 101 jika dibagi oleh 10?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-9", text: "9 (karena 99 ≡ -1 dan 101 ≡ 1, hasil kali = -1 ≡ 9)", isCorrect: true, explanation: "Brilian! 99 × 101 = 9999, digit terakhirnya adalah 9. Cara reduksi: (-1) × 1 = -1 ≡ 9 (mod 10)." },
              { id: "opt-1", text: "1", isCorrect: false, explanation: "9 × 1 = 9, bukan 1." },
              { id: "opt-0", text: "0", isCorrect: false, explanation: "Hasil kali tidak berakhir dengan angka nol." },
            ],
            explanation: "99 ≡ 9 dan 101 ≡ 1. Maka 9 × 1 = 9 (mod 10).",
          },
        },
        {
          id: "c2-s6",
          type: "sandbox",
          title: "Playground Modulo 7 Kalender",
          naiExpression: "happy",
          naiDialogue: "Coba berbagai angka hari untuk menguji siklus kalender abadi.",
          sandbox: {
            title: "Simulator Kalender Mod 7",
            instructions: "Variasikan nilai jam A dan B pada modulus 7 untuk mengamati pergeseran siklus.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 7, hourA: 2, hourB: 3, multiplier: 3 },
          },
        },
        {
          id: "c2-s7",
          type: "challenge",
          title: "Tantangan: Konfigurasi Jam Modulo 7",
          naiExpression: "neutral",
          naiDialogue: "Atur lingkaran modulo n = 7, lalu atur jam A dan B sehingga total sisa baginya tepat bernilai 5!",
          challenge: {
            id: "challenge-clock-calendar",
            title: "Sinkronisasi Siklus Kalender",
            question:
              "Ubah lingkaran modulo menjadi n = 7. Atur jam A dan jam B sehingga total penjumlahan sisa baginya menghasilkan tepat 5 (misal: Selasa + 4 hari = Sabtu)!",
            targetCondition: (vars) => {
              const n = vars.n || 0;
              const sum = (((vars.hourA || 0) + (vars.hourB || 0)) % 7 + 7) % 7;
              return n === 7 && sum === 5;
            },
            hint1Static: "Ubah slider modulus n menjadi 7 terlebih dahulu.",
            hint2Static: "Pilih jam A dan B yang jika dijumlahkan menghasilkan 5 atau kelipatan 7 + 5 (seperti 12).",
            solutionVariables: { n: 7, hourA: 2, hourB: 3 },
            solutionExplanation: "Pada n = 7, jam A = 2 dan jam B = 3 menghasilkan (2 + 3) mod 7 = 5.",
            xpReward: 40,
          },
        },
        {
          id: "c2-s8",
          type: "reflect",
          title: "Refleksi Level 2: Aljabar yang Rapi",
          naiExpression: "celebrating",
          naiDialogue: "Hebat! Kamu sudah bisa mengendalikan angka-angka raksasa dengan aritmetika modular!",
          reflect: {
            title: "Level 2 Tuntas: Penjumlahan & Perkalian Modulo",
            takeaways: [
              "Angka besar dapat disederhanakan terlebih dahulu sebelum dioperasikan.",
              "Aritmetika modular mempertahankan sifat komutatif, asosiatif, dan distributif.",
              "Kalender dan jam adalah contoh nyata homomorfisma modular di kehidupan nyata.",
            ],
            connectionText: "Di Level 3, kita akan memecahkan misteri PEMBAGIAN di dunia jam modulo!",
            nextLevelTitle: "Level 3: Pembagian & Invers Modular",
            badgeToUnlock: "pattern-seeker",
            xpReward: 40,
            formulaKaTeX: "(a \\times b) \\pmod n = ((a \\pmod n) \\times (b \\pmod n)) \\pmod n",
          },
        },
      ],
    },
    {
      id: "clock-level-3",
      index: 3,
      tier: 2,
      title: "Pembagian Modulo & Invers Perkalian Modular",
      description: "Menemukan invers perkalian modular a * x = 1 (mod m) dan kondisi keterbagian.",
      ahaMoment: "Di dunia modulo, pembagian a / b berarti mencari pasangan pengali rahasia yang menghasilkan 1!",
      steps: [
        {
          id: "c3-s1",
          type: "provoke",
          title: "Membagi Tanpa Pecahan!",
          naiExpression: "curious",
          naiDialogue: "Di aritmetika biasa 6 / 2 = 3. Tapi di modulo 6, apakah pembagian selalu bekerja normal?",
          provoke: {
            hookTitle: "Misteri Pembagi Nol di Modulo 6",
            hookText: "Perhatikan bahwa 2 × 3 = 6 ≡ 0 (mod 6). Dua angka bukan nol bisa menghasilkan nol! Ini merusak pembagian biasa.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 6, hourA: 2, hourB: 3, multiplier: 2 },
            question: "Bagaimana cara kita membagi dengan bilangan bulat b di dunia modulo?",
            options: [
              {
                id: "opt-inv",
                text: "Dengan mencari invers perkalian b⁻¹ sehingga b · b⁻¹ ≡ 1 (mod m)",
                responseText: "Tepat sekali! Membagi dengan b sama persis dengan mengalikan dengan invers modularnya.",
              },
              {
                id: "opt-dec",
                text: "Dengan mengubahnya menjadi angka pecahan desimal koma.",
                responseText: "Di aritmetika jam modulo tidak ada pecahan desimal koma; semua nilai wajib berupa bilangan bulat!",
              },
            ],
          },
        },
        {
          id: "c3-s2",
          type: "predict",
          title: "Berburu Invers di Modulo 7",
          naiExpression: "thinking",
          naiDialogue: "Di modulo 7, adakah angka x sehingga 3 × x menghasilkan sisa 1?",
          predict: {
            scenarioTitle: "Mencari Pasangan Pengali 3",
            scenarioText: "Kita uji kelipatan 3: 3×1=3, 3×2=6, 3×3=9≡2, 3×4=12≡5, 3×5=15.",
            question: "Berapakah 15 mod 7, dan apakah angka 5 adalah invers dari 3?",
            options: [
              {
                id: "pred-yes-5",
                text: "Ya! 15 = 2 × 7 + 1, bersisa 1, jadi invers dari 3 adalah 5",
                isCorrect: true,
                feedback: "Hebat! Karena 3 × 5 ≡ 1 (mod 7), maka membagi dengan 3 di modulo 7 sama saja dengan mengalikan dengan 5!",
              },
              {
                id: "pred-no-5",
                text: "Bukan, inversnya harus berbentuk 1/3",
                isCorrect: false,
                feedback: "Di modulo 7, tidak ada 1/3. Posisi 1/3 digantikan oleh bilangan bulat 5.",
              },
            ],
            simulationLabel: "Buktikan Invers 3 × 5!",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 7, multiplier: 5, hourA: 3, hourB: 0 },
            simulationVariables: { n: 7, multiplier: 5, hourA: 3, hourB: 1 },
          },
        },
        {
          id: "c3-s3",
          type: "guided",
          title: "Eksplorasi Generator & Invers",
          naiExpression: "happy",
          naiDialogue: "Atur multiplier = 5 pada jam n = 7. Amati siklus tali yang mengelilingi seluruh lingkaran!",
          guided: {
            instructionTitle: "Generator Siklus Penuh Modulo 7",
            instructionText: "Amati bagaimana pengali 5 mengunjungi setiap simpul jam secara bergantian tanpa ada yang terlewat.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 7, multiplier: 5, hourA: 3, hourB: 0 },
            observationTable: {
              headers: ["Angka Asal", "Dikalikan Invers 5", "Hasil Modulo 7"],
              rows: [
                { parameter: "3 × 5 = 15", expectedValue: "15 mod 7 = 1", unit: "invers tercapai" },
                { parameter: "6 × 5 = 30", expectedValue: "30 mod 7 = 2", unit: "setara 6 / 3 = 2" },
              ],
            },
            discoveryQuestion: {
              prompt: "Kapan sebuah bilangan b DIJAMIN MEMILIKI invers di modulo m?",
              options: [
                "Hanya jika FPB(b, m) = 1 (keduanya saling prima / koprima)",
                "Hanya jika b adalah bilangan genap",
                "Selalu ada untuk semua bilangan bulat",
              ],
              correctOption: "Hanya jika FPB(b, m) = 1 (keduanya saling prima / koprima)",
              insight: "Jika FPB(b, m) > 1, maka kelipatannya tidak akan pernah menyentuh angka 1.",
            },
          },
        },
        {
          id: "c3-s4",
          type: "formalize",
          title: "Definisi Formal Invers Modular",
          naiExpression: "neutral",
          naiDialogue: "Mari kita tuangkan teorema eksistensi invers modular ke dalam KaTeX.",
          formalize: {
            title: "Formalisasi Invers Modular",
            prompt: "Lengkapi persamaan eksistensi invers modular berikut:",
            formulaTemplate: "b \\cdot b^{-1} \\equiv [blank1] \\pmod m \\quad \\text{eksis jika dan hanya jika} \\quad \\gcd(b, m) = [blank2]",
            blanks: [
              { id: "blank1", label: "Target Sisa", options: ["1", "0", "m"], correctOption: "1" },
              { id: "blank2", label: "Syarat FPB", options: ["1", "0", "b"], correctOption: "1" },
            ],
            resolvedFormulaKaTeX: "b \\cdot b^{-1} \\equiv 1 \\pmod m \\iff \\gcd(b, m) = 1",
            explanation: "Invers perkalian modular b⁻¹ adalah bilangan bulat pengali yang membawa hasil kali kembali ke identitas 1 modulo m.",
          },
        },
        {
          id: "c3-s5",
          type: "check",
          title: "Deteksi Kemungkinan Invers",
          naiExpression: "thinking",
          naiDialogue: "Periksa angka mana yang memiliki invers di jam modulo 10!",
          check: {
            question: "Manakah angka berikut yang MEMILIKI invers perkalian di modulo 10?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-7", text: "7 (karena FPB(7, 10) = 1, inversnya adalah 3 karena 7 × 3 = 21 ≡ 1)", isCorrect: true, explanation: "Tepat sekali! 7 dan 10 saling prima, dan 7 × 3 = 21 = 2 × 10 + 1." },
              { id: "opt-2", text: "2 (FPB(2, 10) = 2 ≠ 1)", isCorrect: false, explanation: "Kelipatan 2 selalu genap, tidak akan pernah bersisa 1 di modulo 10." },
              { id: "opt-5", text: "5 (FPB(5, 10) = 5 ≠ 1)", isCorrect: false, explanation: "Kelipatan 5 hanya berakhir di angka 0 atau 5, mustahil menghasilkan sisa 1." },
            ],
            explanation: "Hanya angka yang saling koprima dengan 10 (yaitu 1, 3, 7, 9) yang memiliki invers di mod 10.",
          },
        },
        {
          id: "c3-s6",
          type: "sandbox",
          title: "Playground Invers & Multiplier",
          naiExpression: "happy",
          naiDialogue: "Uji coba berbagai multiplier koprima pada lingkaran modulo n = 7.",
          sandbox: {
            title: "Simulasi Invers Modulo",
            instructions: "Atur multiplier = 5 dan variasikan jam A untuk melihat efek perkalian invers.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 7, multiplier: 5, hourA: 3, hourB: 0 },
          },
        },
        {
          id: "c3-s7",
          type: "challenge",
          title: "Misi: Temukan Generator Siklus",
          naiExpression: "neutral",
          naiDialogue: "Atur modulus n = 7 dan temukan pengali koprima yang merupakan invers dari 3 (Target: multiplier = 5)!",
          challenge: {
            id: "challenge-clock-inverse-generator",
            title: "Pembangkit Siklus Penuh Mod 7",
            question:
              "Atur modulus n = 7 dan temukan pengali (multiplier) koprima yang menghasilkan invers perkalian dari 3 (Target: multiplier = 5 sehingga 3 x 5 = 1 mod 7)!",
            targetCondition: (vars) => {
              return vars.n === 7 && vars.multiplier === 5;
            },
            hint1Static: "Hitung perkalian 3 dengan angka 1 sampai 6 di modulo 7.",
            hint2Static: "3 x 5 = 15. Berapakah 15 mod 7? Tepat 1! Atur multiplier ke 5.",
            solutionVariables: { n: 7, multiplier: 5 },
            solutionExplanation: "3 * 5 = 15 = 2 * 7 + 1 ≡ 1 (mod 7). Maka invers dari 3 mod 7 adalah 5.",
            xpReward: 50,
          },
        },
        {
          id: "c3-s8",
          type: "reflect",
          title: "Refleksi Level 3: Pembagian Tanpa Pecahan",
          naiExpression: "celebrating",
          naiDialogue: "Luar biasa! Kamu baru saja belajar membagi tanpa pernah menyentuh pecahan desimal!",
          reflect: {
            title: "Level 3 Tuntas: Invers Perkalian Modular",
            takeaways: [
              "Pembagian di modulo didefinisikan sebagai perkalian dengan invers modular.",
              "Invers hanya eksis jika bilangan pembagi koprima dengan modulusnya: FPB(b, m) = 1.",
              "Invers modular adalah fondasi algoritma enkripsi asimetris RSA modern.",
            ],
            connectionText: "Di Level 4, kita akan melihat bagaimana perkalian modular melahirkan kurva seni kardioid yang memukau!",
            nextLevelTitle: "Level 4: Geometri Fraktal Kardioid",
            badgeToUnlock: "pattern-seeker",
            xpReward: 50,
            formulaKaTeX: "a \\cdot x \\equiv 1 \\pmod m",
          },
        },
      ],
    },
    {
      id: "clock-level-4",
      index: 4,
      tier: 2,
      title: "Geometri Fraktal Kardioid & Pola Bunga Modular",
      description: "Menghubungkan titik i ke (i * m) mod n untuk melahirkan kurva amplop epikoloid.",
      ahaMoment: "Tabel perkalian modulo di lingkaran menghasilkan pola geometri indah: bentuk hati kardioid dan fraktal!",
      steps: [
        {
          id: "c4-s1",
          type: "provoke",
          title: "Garis Lurus Menjadi Lengkungan Cahaya",
          naiExpression: "curious",
          naiDialogue: "Semua benang ini lurus sempurna. Dari mana datangnya lengkungan halus berbentuk hati ini?",
          provoke: {
            hookTitle: "Munculnya Kardioid dari Garis Lurus",
            hookText: "Jika keliling lingkaran dibagi menjadi banyak titik, lalu setiap titik i dihubungkan garis lurus ke (i × 2) mod n, garis-garis tersebut membungkus kurva lengkung mulus bernama kardioid.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 60, multiplier: 2, hourA: 0, hourB: 0 },
            question: "Mengapa garis-garis lurus bisa membentuk kurva lengkung?",
            options: [
              {
                id: "opt-caustic",
                text: "Karena garis-garis lurus tersebut menjadi garis singgung dari kurva amplop (kaustik)",
                responseText: "Tepat sekali! Mirip pantulan cahaya di dasar cangkir kopi, fenomena kaustik ini adalah manifestasi fisik tabel perkalian modulo 2.",
              },
              {
                id: "opt-bend",
                text: "Karena garisnya melengkung secara fisik saat digambar.",
                responseText: "Garisnya 100% lurus! Lengkungan itu adalah efek optik dari kerapatan garis singgung beruntun.",
              },
            ],
          },
        },
        {
          id: "c4-s2",
          type: "predict",
          title: "Ke Mana Tali Terhubung?",
          naiExpression: "thinking",
          naiDialogue: "Pada lingkaran 10 titik, jika multiplier = 2, ke manakah titik 6 dihubungkan?",
          predict: {
            scenarioTitle: "Koneksi Tali Modular",
            scenarioText: "Rumus koneksi: Target = (Titik Asal × Multiplier) mod 10. Untuk titik 6 dengan multiplier = 2.",
            question: "Ke titik berapakah garis dari titik 6 berakhir?",
            options: [
              {
                id: "pred-2-card",
                text: "Titik 2 (karena 6 × 2 = 12 ≡ 2 mod 10)",
                isCorrect: true,
                feedback: "Benar! 12 dibagi 10 bersisa 2, sehingga tali ditarik dari titik 6 menuju titik 2.",
              },
              {
                id: "pred-12-card",
                text: "Titik 12",
                isCorrect: false,
                feedback: "Ingat bahwa lingkaran ini hanya memiliki 10 titik (angka 0 sampai 9).",
              },
            ],
            simulationLabel: "Hubungkan Tali!",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 10, multiplier: 2, hourA: 6, hourB: 0 },
            simulationVariables: { n: 10, multiplier: 2, hourA: 6, hourB: 2 },
          },
        },
        {
          id: "c4-s3",
          type: "guided",
          title: "Eksplorasi Kurva Kardioid & Nefroid",
          naiExpression: "happy",
          naiDialogue: "Tingkatkan nilai multiplier ke 3 dan 4. Lihat berapa banyak cuping bunga yang mekar!",
          guided: {
            instructionTitle: "Jumlah Cuping Kurva Epikoloid",
            instructionText: "Ubah n menjadi bilangan besar (misal 60) dan naikkan multiplier untuk melihat bentuk kurva amplop.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 60, multiplier: 2, hourA: 0, hourB: 0 },
            observationTable: {
              headers: ["Multiplier k", "Bentuk Kurva", "Jumlah Cuping (Lekukan)"],
              rows: [
                { parameter: "k = 2", expectedValue: "Kardioid (Hati)", unit: "1 cuping" },
                { parameter: "k = 3", expectedValue: "Nefroid (Ginjal)", unit: "2 cuping" },
                { parameter: "k = 4", expectedValue: "Trefoil", unit: "3 cuping" },
              ],
            },
            discoveryQuestion: {
              prompt: "Apa rumus umum jumlah cuping yang terbentuk untuk sembarang multiplier k?",
              options: [
                "Jumlah Cuping = k - 1",
                "Jumlah Cuping = k + 1",
                "Jumlah Cuping = k × 2",
              ],
              correctOption: "Jumlah Cuping = k - 1",
              insight: "Jumlah cuping selalu tepat k - 1! Untuk multiplier = 3 terbentuk nefroid dengan 3 - 1 = 2 cuping.",
            },
          },
        },
        {
          id: "c4-s4",
          type: "formalize",
          title: "Persamaan Amplop Kaustik Modular",
          naiExpression: "neutral",
          naiDialogue: "Mari formulasikan pemetaan tali ke dalam rumus amplop kaustik.",
          formalize: {
            title: "Persamaan Amplop Kaustik",
            prompt: "Lengkapi pemetaan simpul dan rumus jumlah cuping kurva:",
            formulaTemplate: "i \\mapsto (i \\cdot m) \\pmod n \\quad \\text{dan} \\quad \\text{Banyak Cuping} = [blank1] - 1",
            blanks: [
              { id: "blank1", label: "Parameter Pengali", options: ["m", "n", "i"], correctOption: "m" },
            ],
            resolvedFormulaKaTeX: "i \\mapsto (i \\cdot m) \\pmod n \\quad \\text{dan} \\quad \\text{Banyak Cuping} = m - 1",
            explanation: "Tiap garis lurus menjadi garis singgung dari amplop kurva epikoloid yang memiliki m - 1 cuping simetris.",
          },
        },
        {
          id: "c4-s5",
          type: "check",
          title: "Analisis Titik Temu Nol",
          naiExpression: "thinking",
          naiDialogue: "Perhatikan titik puncak 0 di bagian atas lingkaran!",
          check: {
            question: "Mengapa titik 0 selalu menjadi simpul tempat bertemunya semua garis untuk pengali berapa pun?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-0-zero", text: "Karena 0 × m = 0 (mod n) untuk pengali m berapa pun", isCorrect: true, explanation: "Tepat sekali! Nol dikalikan angka berapa pun selalu menghasilkan nol, sehingga tali dari titik 0 selalu kembali ke dirinya sendiri." },
              { id: "opt-0-top", text: "Karena titik nol berada di paling atas", isCorrect: false, explanation: "Posisi fisik hanyalah pilihan visual koordinat, alasan matematisnya adalah sifat perkalian nol." },
            ],
            explanation: "Sifat nol: 0 · k ≡ 0 (mod n), menjadikan titik 0 sebagai titik tetap (fixed point).",
          },
        },
        {
          id: "c4-s6",
          type: "sandbox",
          title: "Simulasi Pola Benang Kardioid",
          naiExpression: "happy",
          naiDialogue: "Eksplorasi berbagai nilai n dan multiplier untuk melahirkan karya seni matematika.",
          sandbox: {
            title: "Studio Seni Fraktal Modulo",
            instructions: "Ubah n menjadi bilangan besar (misal 60) dan naikkan multiplier untuk melihat keindahan amplop.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 60, multiplier: 2, hourA: 0, hourB: 0 },
          },
        },
        {
          id: "c4-s7",
          type: "challenge",
          title: "Misi: Bentuk Bunga Nefroid 2 Cuping",
          naiExpression: "neutral",
          naiDialogue: "Atur jumlah titik n minimal 30 dan multiplier = 3 untuk menghasilkan kurva nefroid (2 cuping simetris)!",
          challenge: {
            id: "challenge-clock-cardioid-nephroid",
            title: "Konfigurasi Nefroid (m = 3, n >= 30)",
            question:
              "Atur jumlah titik n minimal 30 dan multiplier = 3 untuk menghasilkan kurva nefroid (2 cuping simetris)!",
            targetCondition: (vars) => {
              return (vars.n || 0) >= 30 && (vars.multiplier || 0) === 3;
            },
            hint1Static: "Ingat rumus jumlah cuping: multiplier - 1 = 2, sehingga multiplier harus 3.",
            hint2Static: "Tingkatkan n ke minimal 30 agar garis terlihat padat dan halus.",
            solutionVariables: { n: 40, multiplier: 3 },
            solutionExplanation: "Multiplier = 3 menghasilkan nefroid (2 cuping). n = 40 memberikan resolusi kurva yang sangat jelas.",
            xpReward: 50,
          },
        },
        {
          id: "c4-s8",
          type: "reflect",
          title: "Refleksi Level 4: Keindahan Matematika Murni",
          naiExpression: "celebrating",
          naiDialogue: "Matematika bukan cuma angka kering, tapi juga simetri visual yang memukau!",
          reflect: {
            title: "Level 4 Tuntas: Kardioid & Seni Geometri Modulo",
            takeaways: [
              "Perkalian modular di atas lingkaran menghasilkan kurva amplop epikoloid kaustik.",
              "Multiplier k = 2 melahirkan kardioid (1 cuping), dan k = 3 melahirkan nefroid (2 cuping).",
              "Hubungan aljabar murni sisa bagi memiliki perwujudan simetri visual nyata di alam semesta.",
            ],
            connectionText: "Di Level 5, kita akan menggunakan modulo untuk menyandikan pesan rahasia para kaisar!",
            nextLevelTitle: "Level 5: Kriptografi Sandi Caesar & Affine",
            badgeToUnlock: "pattern-seeker",
            xpReward: 50,
            formulaKaTeX: "i \\mapsto (i \\cdot m) \\pmod n",
          },
        },
      ],
    },
    {
      id: "clock-level-5",
      index: 5,
      tier: 3,
      title: "Kriptografi Sandi Caesar & Affine",
      description: "Aplikasi aritmetika modular dalam penyandian pesan rahasia alfabet mod 26.",
      ahaMoment: "Pesan rahasia dienkripsi dengan menggeser atau mengalikan huruf di jam modulo 26!",
      steps: [
        {
          id: "c5-s1",
          type: "provoke",
          title: "Sandi Kaisar Julius Caesar",
          naiExpression: "curious",
          naiDialogue: "Kaisar Romawi mengirim pesan dengan memutar alfabet 3 langkah (A -> D). Bisakah kamu memecahkannya?",
          provoke: {
            hookTitle: "Enkripsi Alfabet Modulo 26",
            hookText: "Huruf A-Z dipetakan ke angka 0 sampai 25. Sandi Caesar menggeser setiap huruf sebesar kunci k: C = (P + k) mod 26.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 26, hourA: 3, hourB: 7, multiplier: 3 },
            question: "Jika kunci k = 3, ke huruf apakah huruf Z (angka 25) berubah setelah berputar melintasi titik 0?",
            options: [
              {
                id: "opt-c",
                text: "Huruf C (angka 2, karena (25 + 3) mod 26 = 28 mod 26 = 2)",
                responseText: "Tepat sekali! Huruf berputar kembali ke awal alfabet layaknya jarum jam melintasi angka 12.",
              },
              {
                id: "opt-space",
                text: "Hilang menjadi spasi kosong karena melebihi batas 26 huruf.",
                responseText: "Kurang tepat. Di aritmetika modulo 26, tidak ada angka yang hilang, semua berputar kembali ke 0, 1, 2.",
              },
            ],
          },
        },
        {
          id: "c5-s2",
          type: "predict",
          title: "Arah Dekripsi Sandi",
          naiExpression: "thinking",
          naiDialogue: "Jika enkripsi adalah penambahan k, bagaimana cara mendekripsi kembali pesan rahasia?",
          predict: {
            scenarioTitle: "Membalikkan Sandi Caesar",
            scenarioText: "Enkripsi menggeser maju C = (P + k) mod 26.",
            question: "Operasi manakah yang membalikkan sandi untuk mendapatkan kembali teks asli P?",
            options: [
              {
                id: "pred-sub",
                text: "P = (C - k) mod 26 (menggeser mundur sebesar kunci k)",
                isCorrect: true,
                feedback: "Benar! Dekripsi adalah operasi invers dari enkripsi: memutar jarum jam berlawanan arah.",
              },
              {
                id: "pred-mul",
                text: "P = (C × k) mod 26",
                isCorrect: false,
                feedback: "Perkalian bukan kebalikan dari penjumlahan.",
              },
            ],
            simulationLabel: "Dekripsikan Pesan!",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 26, hourA: 23, hourB: 5, multiplier: 3 },
            simulationVariables: { n: 26, hourA: 23, hourB: 5, multiplier: 3 },
          },
        },
        {
          id: "c5-s3",
          type: "guided",
          title: "Matematika Sandi Caesar (Mod 26)",
          naiExpression: "happy",
          naiDialogue: "Atur n = 26 untuk mengamati perputaran 26 huruf alfabet pada lingkaran modulo!",
          guided: {
            instructionTitle: "Roda Sandi Modulo 26",
            instructionText: "Atur n = 26 untuk mengamati bagaimana posisi jam A (teks asli) digeser oleh jam B (kunci sandi).",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 26, hourA: 23, hourB: 5, multiplier: 3 },
            observationTable: {
              headers: ["Huruf Asli P", "Kunci Pergeseran k", "Huruf Sandi C (mod 26)"],
              rows: [
                { parameter: "X (23)", expectedValue: "+ 5 langkah", unit: "C (2)" },
                { parameter: "A (0)", expectedValue: "+ 3 langkah", unit: "D (3)" },
              ],
            },
            discoveryQuestion: {
              prompt: "Mengapa pergeseran 26 langkah menghasilkan teks yang sama persis dengan aslinya?",
              options: [
                "Karena 26 mod 26 = 0 (satu putaran penuh kembali ke tempat semula)",
                "Karena kunci 26 dilarang dalam kriptografi",
                "Hanya kebetulan belaka",
              ],
              correctOption: "Karena 26 mod 26 = 0 (satu putaran penuh kembali ke tempat semula)",
              insight: "Kunci k = 0 dan k = 26 adalah identitas netral yang tidak mengubah teks sama sekali.",
            },
          },
        },
        {
          id: "c5-s4",
          type: "formalize",
          title: "Rumus Enkripsi & Dekripsi Caesar",
          naiExpression: "neutral",
          naiDialogue: "Mari formulasikan sandi Caesar dan sandi Affine ke dalam KaTeX.",
          formalize: {
            title: "Formula Sandi Caesar & Affine",
            prompt: "Lengkapi persamaan enkripsi dan dekripsi modular berikut:",
            formulaTemplate: "C \\equiv (P + k) \\pmod{26} \\quad \\text{dan} \\quad P \\equiv (C [blank1] k) \\pmod{26}",
            blanks: [
              { id: "blank1", label: "Operasi Dekripsi", options: ["-", "+", "\\times"], correctOption: "-" },
            ],
            resolvedFormulaKaTeX: "C \\equiv (P + k) \\pmod{26} \\quad \\text{dan} \\quad P \\equiv (C - k) \\pmod{26}",
            explanation: "Sandi Caesar adalah translasi modular 1D pada cincin Z_26.",
          },
        },
        {
          id: "c5-s5",
          type: "check",
          title: "Validasi Kunci Sandi Affine",
          naiExpression: "thinking",
          naiDialogue: "Pada sandi Affine C = (aP + b) mod 26, pengali a tidak boleh sembarangan!",
          check: {
            question: "Manakah nilai a berikut yang VALID untuk digunakan sebagai pengali sandi Affine di mod 26?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-3-aff", text: "a = 3 (karena FPB(3, 26) = 1, sehingga memiliki invers dekripsi)", isCorrect: true, explanation: "Benar! a wajib memiliki invers di mod 26 agar pesan bisa didekripsi kembali secara unik." },
              { id: "opt-2-aff", text: "a = 2 (FPB(2, 26) = 2 ≠ 1)", isCorrect: false, explanation: "Jika a = 2, huruf genap dan ganjil akan bertumpuk dan pesan tidak bisa didekripsi!" },
              { id: "opt-13-aff", text: "a = 13 (FPB(13, 26) = 13 ≠ 1)", isCorrect: false, explanation: "13 membagi 26, sehingga terjadi tabrakan sandi parah." },
            ],
            explanation: "Kunci perkalian modular harus saling prima dengan ukuran alfabet: FPB(a, 26) = 1.",
          },
        },
        {
          id: "c5-s6",
          type: "sandbox",
          title: "Roda Sandi Modulo 26",
          naiExpression: "happy",
          naiDialogue: "Eksplorasi perputaran 26 huruf alfabet pada lingkaran modulo!",
          sandbox: {
            title: "Simulasi Roda Sandi Caesar",
            instructions: "Atur n = 26 untuk mengamati perputaran alfabet pada jam 26 titik.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 26, hourA: 3, hourB: 7, multiplier: 3 },
          },
        },
        {
          id: "c5-s7",
          type: "challenge",
          title: "Tantangan: Dekripsi Huruf Sandi",
          naiExpression: "neutral",
          naiDialogue: "Pada n = 26, huruf awal di A = 23 (X). Temukan pergeseran B agar mendarat tepat di 2 (C)!",
          challenge: {
            id: "challenge-clock-crypto-caesar",
            title: "Pecahkan Kunci Sandi Caesar",
            question:
              "Pada lingkaran n = 26, sebuah huruf asli berada di posisi jam A = 23 (huruf X). Temukan pergeseran jam B agar hasil akhirnya mendarat tepat di posisi 2 (huruf C) setelah berputar melintasi titik 0!",
            targetCondition: (vars) => {
              const n = vars.n || 0;
              const res = (((vars.hourA || 0) + (vars.hourB || 0)) % 26 + 26) % 26;
              return n === 26 && vars.hourA === 23 && res === 2;
            },
            hint1Static: "Hitung (23 + B) mod 26 = 2.",
            hint2Static: "Dari 23 ke 26 butuh 3 langkah. Dari 0 ke 2 butuh 2 langkah. Total langkah = 5.",
            solutionVariables: { n: 26, hourA: 23, hourB: 5 },
            solutionExplanation: "(23 + 5) mod 26 = 28 mod 26 = 2. Pergeseran kunci adalah 5.",
            xpReward: 60,
          },
        },
        {
          id: "c5-s8",
          type: "reflect",
          title: "Refleksi Level 5: Keamanan & Kriptografi",
          naiExpression: "celebrating",
          naiDialogue: "Hebat! Kamu telah melihat bagaimana operasi modular melindungi kerahasiaan informasi dunia.",
          reflect: {
            title: "Level 5 Tuntas: Kriptografi Sandi Caesar",
            takeaways: [
              "Sandi Caesar adalah translasi sisa bagi pada modulo ukuran alfabet (mod 26).",
              "Sandi Affine menggabungkan perkalian dan pergeseran: C ≡ (aP + b) mod 26.",
              "Syarat kunci perkalian yang aman adalah harus saling prima dengan modulusnya.",
            ],
            connectionText: "Saatnya menguji seluruh keahlian modul ini di tantangan pamungkas: Boss Level!",
            nextLevelTitle: "Boss Level: Ujian Modul Aritmetika Jam",
            badgeToUnlock: "pattern-seeker",
            xpReward: 60,
            formulaKaTeX: "C \\equiv (a \\cdot P + b) \\pmod{26}",
          },
        },
      ],
    },
    {
      id: "clock-level-6",
      index: 6,
      tier: 3,
      title: "Boss Level: Ujian Modul Aritmetika Jam",
      description: "Tantangan menyeluruh menggabungkan kongruensi, kalender, invers, dan kurva kardioid.",
      ahaMoment: "Modulo adalah seni melihat keteraturan dalam perulangan siklis bilangan!",
      steps: [
        {
          id: "c6-s1",
          type: "provoke",
          title: "Ujian Akhir Modul Aritmetika Jam",
          naiExpression: "thinking",
          naiDialogue: "Kamu telah menguasai sisa bagi, reduksi angka besar, invers, kardioid, hingga sandi rahasia. Buktikan kemampuanmu!",
          provoke: {
            hookTitle: "Ujian Akhir Modul Modulo",
            hookText: "Boss Level ini menguji pemahaman konsepmu secara terpadu dari Level 1 hingga Level 5.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 11, multiplier: 4, hourA: 8, hourB: 7 },
            question: "Mengapa lingkaran dengan modulus bilangan prima (seperti n = 11) sangat disukai dalam kriptografi?",
            options: [
              {
                id: "opt-prime-field",
                text: "Karena setiap angka bukan nol dijamin saling koprima dengan 11 sehingga memiliki invers perkalian unik!",
                responseText: "Tepat sekali! Lingkaran modulo prima membentuk lapangan berhingga (Galois Field F_p) di mana semua pembagian selalu valid.",
              },
              {
                id: "opt-prime-simple",
                text: "Karena bilangan prima lebih mudah dihitung secara manual.",
                responseText: "Kurang tepat. Kekuatan modulo prima terletak pada ketiadaan pembagi nol liar.",
              },
            ],
          },
        },
        {
          id: "c6-s2",
          type: "predict",
          title: "Prediksi Siklus Modulo Prima 11",
          naiExpression: "thinking",
          naiDialogue: "Jika n = 11, berapakah sisa bagi dari (8 + 7) mod 11?",
          predict: {
            scenarioTitle: "Evaluasi Kongruensi Terpadu",
            scenarioText: "8 + 7 = 15. Kita ingin mencari posisi jarum pada jam 11.",
            question: "Berapakah nilai 15 mod 11?",
            options: [
              {
                id: "pred-4-boss",
                text: "4 (karena 15 = 1 × 11 + 4)",
                isCorrect: true,
                feedback: "Benar! 15 bersisa 4 pada jam modulo 11.",
              },
              {
                id: "pred-5-boss",
                text: "5",
                isCorrect: false,
                feedback: "11 + 5 = 16, bukan 15.",
              },
            ],
            simulationLabel: "Verifikasi Nilai!",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 11, multiplier: 4, hourA: 8, hourB: 7 },
            simulationVariables: { n: 11, multiplier: 4, hourA: 8, hourB: 7 },
          },
        },
        {
          id: "c6-s3",
          type: "guided",
          title: "Simulator Penuh Modulo",
          naiExpression: "happy",
          naiDialogue: "Uji coba parameter lingkaran prima n = 11 dan multiplier = 4 sebelum menyelesaikan misi akhir.",
          guided: {
            instructionTitle: "Laboratorium Terpadu Modulo 11",
            instructionText: "Atur n = 11 dan amati bagaimana multiplier 4 membentuk siklus tali yang indah dan lengkap.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 11, multiplier: 4, hourA: 8, hourB: 7 },
            observationTable: {
              headers: ["Modulus n", "Multiplier m", "Hasil (8 + 7) mod 11"],
              rows: [
                { parameter: "n = 11", expectedValue: "m = 4 (koprima)", unit: "sisa 4" },
              ],
            },
            discoveryQuestion: {
              prompt: "Mengapa multiplier 4 menghasilkan siklus yang mengunjungi semua titik pada mod 11?",
              options: [
                "Karena FPB(4, 11) = 1 (keduanya saling prima)",
                "Karena 4 adalah bilangan kuadrat",
                "Karena 11 adalah bilangan ganjil",
              ],
              correctOption: "Karena FPB(4, 11) = 1 (keduanya saling prima)",
              insight: "Keteraturan siklus penuh selalu terjamin jika multiplier koprima dengan modulus.",
            },
          },
        },
        {
          id: "c6-s4",
          type: "formalize",
          title: "Teorema Siklus Modulo Terpadu",
          naiExpression: "neutral",
          naiDialogue: "Mari kita tuangkan rangkuman aksioma modulo ke dalam KaTeX.",
          formalize: {
            title: "Aksioma Universal Modulo",
            prompt: "Lengkapi identitas kesetaraan kongruensi:",
            formulaTemplate: "a \\equiv b \\pmod m \\iff a - b = k \\cdot [blank1]",
            blanks: [
              { id: "blank1", label: "Modulus", options: ["m", "a", "b"], correctOption: "m" },
            ],
            resolvedFormulaKaTeX: "a \\equiv b \\pmod m \\iff a - b = k \\cdot m \\quad (k \\in \\mathbb{Z})",
            explanation: "Dua bilangan kongruen selalu berselisih sebesar kelipatan bilangan bulat dari modulusnya.",
          },
        },
        {
          id: "c6-s5",
          type: "check",
          title: "Cek Evaluasi Komprehensif",
          naiExpression: "thinking",
          naiDialogue: "Pertanyaan evaluasi terakhir sebelum mengeksekusi misi penutupan!",
          check: {
            question: "Berapakah sisa bagi dari 3¹⁰⁰ jika dibagi oleh 7 menggunakan pola siklus pangkat modular?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-2-fermat", text: "2 (karena 3⁶ ≡ 1 mod 7, dan 100 = 16×6 + 4, 3⁴ = 81 ≡ 4? Tidak, 3¹=3, 3²=2, 3³=6, 3⁴=4? Tunggu: 3⁴=81=11×7+4? 81 mod 7 = 4)", isCorrect: false, explanation: "Mari hitung cermat: 3^1=3, 3^2=2, 3^3=6, 3^4=4, 3^5=5, 3^6=1. 100 mod 6 = 4. 3^4 = 4 mod 7." },
              { id: "opt-4-fermat", text: "4 (siklus berulang setiap 6 langkah, sisa pangkat 4 menghasilkan 4)", isCorrect: true, explanation: "Tepat sekali! Siklus pangkat 3 mod 7 adalah [3, 2, 6, 4, 5, 1] berulang setiap 6 langkah. 100 = 16 × 6 + 4, jadi 3¹⁰⁰ ≡ 3⁴ = 81 = 11×7 + 4 ≡ 4 (mod 7)!" },
            ],
            explanation: "Pola perulangan pangkat modulo prima selalu berulang teratur menurut Teorema Fermat.",
          },
        },
        {
          id: "c6-s6",
          type: "sandbox",
          title: "Playground Boss Level",
          naiExpression: "happy",
          naiDialogue: "Uji coba semua parameter sebebas mungkin sebelum menyelesaikan tantangan akhir.",
          sandbox: {
            title: "Simulasi Modulo Terbuka",
            instructions: "Uji coba konfigurasi parameter sebelum menyelesaikan misi akhir.",
            interactiveComponentSlug: "arithmetic-modular-clock",
            initialVariables: { n: 11, multiplier: 4, hourA: 8, hourB: 7 },
          },
        },
        {
          id: "c6-s7",
          type: "challenge",
          title: "Misi Terakhir: Konfigurasi Generator Prima",
          naiExpression: "neutral",
          naiDialogue: "Atur modulus n = 11, multiplier = 4, jam A = 8 dan jam B = 7 sehingga sisa baginya menghasilkan tepat 4!",
          challenge: {
            id: "challenge-clock-boss-mastery",
            title: "Mastery: Lingkaran Prima n = 11 & Multiplier Generator",
            question:
              "Atur modulus prima n = 11, pilih multiplier koprima m = 4, dan atur jam A = 8 serta jam B = 7 sehingga sisa bagi penjumlahannya menghasilkan tepat 4!",
            targetCondition: (vars) => {
              const n = vars.n || 0;
              const m = vars.multiplier || 0;
              const sum = (((vars.hourA || 0) + (vars.hourB || 0)) % 11 + 11) % 11;
              return n === 11 && m === 4 && sum === 4;
            },
            hint1Static: "Ubah n ke 11 dan multiplier ke 4.",
            hint2Static: "(8 + 7) = 15. 15 mod 11 = 4. Pasang jam A = 8 dan jam B = 7.",
            solutionVariables: { n: 11, multiplier: 4, hourA: 8, hourB: 7 },
            solutionExplanation: "Pada mod 11, (8 + 7) mod 11 = 4, dan multiplier 4 koprima dengan 11 sehingga membangkitkan siklus penuh.",
            xpReward: 100,
          },
        },
        {
          id: "c6-s8",
          type: "reflect",
          title: "Kelulusan Modul Aritmetika Jam",
          naiExpression: "celebrating",
          naiDialogue: "Luar biasa! Kamu telah menuntaskan seluruh petualangan Aritmetika Jam Modulo hingga tuntas!",
          reflect: {
            title: "Modul Selesai: Master Aritmetika Jam",
            takeaways: [
              "Aritmetika jam memetakan bilangan tak hingga ke dalam cincin diskrit berhingga Z_n.",
              "Operasi penjumlahan dan perkalian dapat direduksi sebelum dihitung untuk efisiensi komputasi.",
              "Invers modular eksis jika dan hanya jika FPB(b, m) = 1, yang mendasari pembagian tanpa pecahan.",
              "Perkalian modular membungkus kurva amplop epikoloid kardioid dan melindungi enkripsi alfabet digital.",
            ],
            connectionText: "Siap melanjutkan ke topik berikutnya? Pelajari Algoritma Euclid & Geometri Pengubinan FPB!",
            badgeToUnlock: "modular-master",
            xpReward: 100,
            formulaKaTeX: "a^{p-1} \\equiv 1 \\pmod p",
          },
        },
      ],
    },
  ],
};
