import { TopicModule } from "@/types/topic";
import { isPrime, isCoprime } from "./engine";

export const primesCoprimeModule: TopicModule = {
  id: "math-primes-coprime",
  slug: "math-primes-coprime",
  title: "Faktorisasi Prima & Bilangan Koprima",
  category: "math",
  summary:
    "Menyelami partikel dasar pembentuk semesta aritmetika: bilangan prima sebagai atom bilangan bulat, saringan ritmis Eratosthenes, relasi koprima tanpa hambatan faktor bersama, hingga pilar enkripsi data perbankan dunia melalui fungsi Euler dan Teorema Fermat.",
  audioNarrationText:
    "Selamat datang di modul Faktorisasi Prima dan Koprima. Kamu akan membedah bilangan bulat hingga ke atom penyusun dasarnya dan memahami bagaimana bilangan prima mengamankan komunikasi digital dunia.",
  initialVariables: {
    numberN: 12,
    coprimeA: 8,
    coprimeB: 9,
    sieveLimit: 60,
    fermatBase: 3,
    fermatPrime: 7,
  },
  levels: [
    {
      id: "primes-level-1",
      index: 1,
      tier: 1,
      title: "Atom Bilangan & Teorema Dasar Aritmetika",
      description: "Menemukan bahwa bilangan prima adalah bilangan yang ubinnya hanya bisa disusun satu baris.",
      ahaMoment: "Bilangan prima adalah bilangan yang ubinnya HANYA bisa disusun menjadi 1 baris lurus panjang, mustahil dibuat menjadi persegi panjang lain!",
      steps: [
        {
          id: "p1-s1",
          type: "provoke",
          title: "Pabrik Cokelat Persegi Panjang",
          naiExpression: "curious",
          naiDialogue: "Kamu bisa menata 12 potong cokelat menjadi 2 × 6 atau 3 × 4. Bagaimana jika kamu hanya punya 7 cokelat?",
          provoke: {
            hookTitle: "Mengapa 7 Potong Cokelat Kaku?",
            hookText: "Coba susun 7 potong cokelat menjadi kisi 2 baris atau 3 baris. Selalu ada yang bolong! Satu-satunya cara menatanya adalah berbaris lurus 1 × 7.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 7, coprimeA: 8, coprimeB: 9 },
            question: "Mengapa angka 7 disebut angka yang 'kaku'?",
            options: [
              {
                id: "opt-prime-rigid",
                text: "Karena 7 adalah bilangan prima: hanya memiliki tepat 2 faktor pembagi (1 dan 7)",
                responseText: "Tepat sekali! Bilangan prima tidak bisa dipecah menjadi perkalian dua bilangan bulat yang lebih kecil.",
              },
              {
                id: "opt-odd-rigid",
                text: "Karena 7 adalah bilangan ganjil.",
                responseText: "Kurang tepat. Angka 9 juga ganjil, tapi bisa dibuat persegi 3 × 3!",
              },
            ],
          },
        },
        {
          id: "p1-s2",
          type: "predict",
          title: "Angka Mana yang Kaku?",
          naiExpression: "thinking",
          naiDialogue: "Di antara angka-angka 9, 11, 15, dan 21, manakah angka yang hanya punya 1 susunan baris lurus?",
          predict: {
            scenarioTitle: "Mendeteksi Atom Prima",
            scenarioText: "9 = 3 × 3, 15 = 3 × 5, 21 = 3 × 7.",
            question: "Angka manakah yang merupakan bilangan prima?",
            options: [
              {
                id: "pred-11",
                text: "11 (hanya bisa disusun 1 × 11)",
                isCorrect: true,
                feedback: "Benar! 11 tidak bisa dibagi oleh 2, 3, 5, atau angka lain selain 1 dan 11.",
              },
              {
                id: "pred-9",
                text: "9 (bisa dibuat persegi 3 × 3)",
                isCorrect: false,
                feedback: "9 = 3 × 3, jadi 9 adalah bilangan komposit.",
              },
              {
                id: "pred-15",
                text: "15",
                isCorrect: false,
                feedback: "15 = 3 × 5, memiliki 4 faktor (1, 3, 5, 15).",
              },
            ],
            simulationLabel: "Buktikan Balok 11!",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 11, coprimeA: 8, coprimeB: 9 },
            simulationVariables: { numberN: 11, coprimeA: 8, coprimeB: 9 },
          },
        },
        {
          id: "p1-s3",
          type: "guided",
          title: "Simulator Kisi Balok Faktor",
          naiExpression: "happy",
          naiDialogue: "Geser nilai N dan amati apakah balok bisa disusun menjadi kisi persegi panjang atau hanya satu baris lurus!",
          guided: {
            instructionTitle: "Laboratorium Balok Bilangan N",
            instructionText: "Amati bagaimana bilangan komposit membentuk banyak kisi, sedangkan bilangan prima hanya menghasilkan 1 baris memanjang.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 12, coprimeA: 8, coprimeB: 9 },
            observationTable: {
              headers: ["Nilai N", "Bentuk Kisi Persegi Panjang", "Status Bilangan"],
              rows: [
                { parameter: "N = 12", expectedValue: "1×12, 2×6, 3×4", unit: "Komposit" },
                { parameter: "N = 17", expectedValue: "Hanya 1×17", unit: "Prima" },
              ],
            },
            discoveryQuestion: {
              prompt: "Berapa banyak bilangan prima yang bernilai GENAP di seluruh semesta matematika?",
              options: [
                "Hanya satu, yaitu angka 2!",
                "Tak terhingga banyaknya",
                "Tidak ada sama sekali",
              ],
              correctOption: "Hanya satu, yaitu angka 2!",
              insight: "Angka 2 adalah bilangan prima paling unik: satu-satunya bilangan prima genap!",
            },
          },
        },
        {
          id: "p1-s4",
          type: "formalize",
          title: "Teorema Dasar Aritmetika",
          naiExpression: "neutral",
          naiDialogue: "Mari tuangkan konsep atom bilangan ini ke dalam formula Teorema Dasar Aritmetika.",
          formalize: {
            title: "Dekomposisi Prima Tunggal (DNA Bilangan)",
            prompt: "Lengkapi persamaan faktorisasi prima unik berikut:",
            formulaTemplate: "N = p_1^{a_1} \\cdot p_2^{a_2} \\dots p_k^{a_k} \\quad \\text{terurai secara } [blank1] \\text{ kecuali urutan faktornya}",
            blanks: [
              { id: "blank1", label: "Sifat Keunikan", options: ["unik (tunggal)", "berubah-ubah", "acak"], correctOption: "unik (tunggal)" },
            ],
            resolvedFormulaKaTeX: "N = \\prod_{i=1}^k p_i^{a_i} \\quad (p_i \\text{ prima unik})",
            explanation: "Setiap bilangan bulat positif lebih dari 1 memiliki sidik jari DNA faktorisasi prima yang tunggal dan abadi.",
          },
        },
        {
          id: "p1-s5",
          type: "check",
          title: "Cek Nalar Pohon Faktor",
          naiExpression: "thinking",
          naiDialogue: "Jika 60 diurai dari 6 × 10 atau dari 4 × 15, apakah atom prima di ujung rantingnya berbeda?",
          check: {
            question: "Apakah hasil akhir faktorisasi prima dari 60 bergantung pada cabang awal yang kita pilih?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-same-dna", text: "Pasti sama persis: 2² × 3 × 5!", isCorrect: true, explanation: "Tepat sekali! Teorema Dasar Aritmetika menjamin hasil akhir faktorisasi prima selalu tunggal." },
              { id: "opt-diff-dna", text: "Bisa berbeda tergantung cabang pohonnya", isCorrect: false, explanation: "Cabang awalnya boleh beda, tapi ujung ranting prima selalu menghasilkan atom yang persis sama." },
            ],
            explanation: "60 = 2 × 2 × 3 × 5 = 2² · 3 · 5 terlepas dari rute penguraian.",
          },
        },
        {
          id: "p1-s6",
          type: "sandbox",
          title: "Playground Balok Faktor Bebas",
          naiExpression: "happy",
          naiDialogue: "Ubah slider N untuk menguji bentuk balok berbagai bilangan prima dan komposit.",
          sandbox: {
            title: "Simulasi Balok N Bebas",
            instructions: "Geser nilai N untuk mengamati dekomposisi kisi dan pohon faktor.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 17, coprimeA: 8, coprimeB: 9 },
          },
        },
        {
          id: "p1-s7",
          type: "challenge",
          title: "Misi: Temukan Atom Prima N = 17",
          naiExpression: "neutral",
          naiDialogue: "Atur slider N ke sebuah bilangan prima antara 15 dan 20 yang hanya memiliki faktor 1 dan dirinya sendiri (Target: N = 17)!",
          challenge: {
            id: "challenge-prime-find17",
            title: "Konfigurasi Bilangan Prima N = 17",
            question:
              "Atur slider N ke sebuah bilangan prima antara 15 dan 20 yang hanya memiliki faktor pembagi 1 dan dirinya sendiri (Target: N = 17)!",
            targetCondition: (vars) => {
              const n = Math.round(vars.numberN || 0);
              return n === 17 && isPrime(n);
            },
            hint1Static: "Cari bilangan ganjil di atas 15 yang tidak habis dibagi 3.",
            hint2Static: "17 tidak habis dibagi 2 maupun 3. Geser slider N ke 17.",
            solutionVariables: { numberN: 17 },
            solutionExplanation: "17 adalah bilangan prima karena hanya bisa dibagi oleh 1 dan 17.",
            xpReward: 30,
          },
        },
        {
          id: "p1-s8",
          type: "reflect",
          title: "Refleksi Level 1: Atom Semesta Bilangan",
          naiExpression: "celebrating",
          naiDialogue: "Sama seperti semua materi tersusun dari atom kimia, semua bilangan tersusun dari bilangan prima!",
          reflect: {
            title: "Level 1 Tuntas: Atom Prima & Teorema Dasar",
            takeaways: [
              "Bilangan prima hanya bisa disusun menjadi satu baris lurus 1 × N.",
              "Teorema Dasar Aritmetika menyatakan setiap bilangan komposit memiliki dekomposisi prima yang unik.",
              "Angka 2 adalah satu-satunya bilangan prima genap di semesta matematika.",
            ],
            connectionText: "Di Level 2, kita akan belajar menyaring ratusan bilangan prima secara ritmis lewat Saringan Eratosthenes!",
            nextLevelTitle: "Level 2: Saringan Eratosthenes & Batas √N",
            badgeToUnlock: "prime-seeker",
            xpReward: 30,
            formulaKaTeX: "N = \\prod_{i} p_i^{a_i}",
          },
        },
      ],
    },
    {
      id: "primes-level-2",
      index: 2,
      tier: 1,
      title: "Saringan Eratosthenes & Batas Akar Kuadrat",
      description: "Menyaring kelipatan secara berirama hingga batas √N tanpa perlu menguji satu per satu.",
      ahaMoment: "Kita tidak perlu menguji keprimaan satu per satu: cukup eliminasi kelipatan secara ritmis sampai batas √N!",
      steps: [
        {
          id: "p2-s1",
          type: "provoke",
          title: "Mencari Jarum di Tumpukan Jerami",
          naiExpression: "curious",
          naiDialogue: "Bagaimana cara ilmuwan Yunani Kuno 2200 tahun lalu menemukan semua bilangan prima di bawah 100 tanpa kalkulator?",
          provoke: {
            hookTitle: "Saringan Ritmis 2200 Tahun Lalu",
            hookText: "Jika kita harus menguji pembagian satu per satu untuk 100 angka, itu sangat melelahkan. Eratosthenes memiliki ide brilian: menyaring kelipatannya!",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
            question: "Ketika kita mencoret semua kelipatan 2 (4, 6, 8, 10...), berapa persen angka di tabel yang langsung gugur?",
            options: [
              {
                id: "opt-half-drop",
                text: "50% dari tabel langsung gugur dalam satu langkah!",
                responseText: "Tepat sekali! Setengah dari seluruh angka di tabel langsung tereliminasi hanya dengan satu ritme kelipatan 2.",
              },
              {
                id: "opt-ten-drop",
                text: "Hanya 10% saja.",
                responseText: "Kurang tepat. Setiap angka kedua adalah bilangan genap, jadi separuh tabel langsung tereliminasi.",
              },
            ],
          },
        },
        {
          id: "p2-s2",
          type: "predict",
          title: "Batas Penyaringan: Kapan Kita Berhenti?",
          naiExpression: "thinking",
          naiDialogue: "Untuk tabel 1 sampai 100, apakah kita perlu mencoret kelipatan 11?",
          predict: {
            scenarioTitle: "Menentukan Batas √N",
            scenarioText: "Kelipatan terkecil dari 11 yang belum dicoret oleh angka sebelumnya (2, 3, 5, 7) adalah 11 × 11.",
            question: "Berapakah 11 × 11, dan apakah ia melebihi batas tabel 100?",
            options: [
              {
                id: "pred-121-over",
                text: "11 × 11 = 121 > 100, sehingga kelipatan 11 tidak perlu disaring lagi!",
                isCorrect: true,
                feedback: "Brilian! Untuk menguji angka hingga N = 100, kita CUKUP menyaring sampai prima ≤ √100 = 10 (hanya 2, 3, 5, dan 7)!",
              },
              {
                id: "pred-need-11",
                text: "Tetap harus diuji sampai angka 99",
                isCorrect: false,
                feedback: "Semua kelipatan 11 di bawah 100 (seperti 22, 33, 44...) sudah otomatis tercoret oleh faktor yang lebih kecil!",
              },
            ],
            simulationLabel: "Buktikan Batas Saringan!",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
            simulationVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
          },
        },
        {
          id: "p2-s3",
          type: "guided",
          title: "Eksplorasi Saringan Eratosthenes",
          naiExpression: "happy",
          naiDialogue: "Pilih tab Saringan Eratosthenes di kanvas untuk mengamati pola prima hijau terang!",
          guided: {
            instructionTitle: "Tabel Saringan Prima 1-60",
            instructionText: "Amati bagaimana kelipatan 2, 3, dan 5 disaring bertahap hingga menyisakan bilangan prima.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
            observationTable: {
              headers: ["Gelombang Saringan", "Prima Aktif", "Batas Kelipatan"],
              rows: [
                { parameter: "Gelombang 1", expectedValue: "Kelipatan 2", unit: "setengah gugur" },
                { parameter: "Gelombang 2", expectedValue: "Kelipatan 3", unit: "diagonal ritmis" },
                { parameter: "Gelombang 3", expectedValue: "Kelipatan 5 & 7", unit: "tabel bersih" },
              ],
            },
            discoveryQuestion: {
              prompt: "Mengapa bilangan komposit pasti memiliki faktor prima pembagi ≤ √N?",
              options: [
                "Karena jika kedua faktornya > √N, hasil kalinya akan melebihi N",
                "Karena akar kuadrat selalu bernilai bulat",
                "Hanya kebetulan aritmetika",
              ],
              correctOption: "Karena jika kedua faktornya > √N, hasil kalinya akan melebihi N",
              insight: "Jika N = a · b dan a > √N serta b > √N, maka a · b > N (kontradiksi). Maka salah satu faktor pasti ≤ √N!",
            },
          },
        },
        {
          id: "p2-s4",
          type: "formalize",
          title: "Batas Akar Kuadrat Uji Prima",
          naiExpression: "neutral",
          naiDialogue: "Mari tuangkan teorema batas akar kuadrat keprimaan ke dalam KaTeX.",
          formalize: {
            title: "Batas Uji Keprimaan √N",
            prompt: "Lengkapi teorema pengujian keprimaan berikut:",
            formulaTemplate: "N \\text{ komposit} \\implies \\exists p \\text{ prima sedemikian sehingga } p \\mid N \\text{ dan } p \\le [blank1]",
            blanks: [
              { id: "blank1", label: "Batas Atas", options: ["\\sqrt{N}", "N / 2", "N - 1"], correctOption: "\\sqrt{N}" },
            ],
            resolvedFormulaKaTeX: "N \\text{ komposit} \\implies \\exists p \\in \\mathbb{P}, \\quad p \\mid N \\quad \\text{dengan } p \\le \\sqrt{N}",
            explanation: "Untuk menguji apakah N prima, kita hanya perlu membagi dengan bilangan prima sampai batas √N. Ini menghemat 90% waktu komputasi.",
          },
        },
        {
          id: "p2-s5",
          type: "check",
          title: "Cek Batas Uji Prima 173",
          naiExpression: "thinking",
          naiDialogue: "Berapakah bilangan prima terbesar yang perlu kita uji untuk memeriksa keprimaan 173?",
          check: {
            question: "Untuk memeriksa apakah 173 adalah bilangan prima, prima terbesar apa yang perlu kita coba bagi?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-13-prime", text: "13 (karena 13² = 169 ≤ 173 dan 14² = 196 > 173)", isCorrect: true, explanation: "Tepat sekali! √173 ≈ 13.15. Kita hanya perlu menguji prima 2, 3, 5, 7, 11, dan 13." },
              { id: "opt-17-prime", text: "17", isCorrect: false, explanation: "17² = 289 > 173, terlalu besar." },
              { id: "opt-86-prime", text: "86 (separuh dari 173)", isCorrect: false, explanation: "Menguji sampai separuh sangat boros waktu; batas √N jauh lebih efisien." },
            ],
            explanation: "Batas prima terbesar adalah p ≤ √173 ≈ 13.15, yaitu prima 13.",
          },
        },
        {
          id: "p2-s6",
          type: "sandbox",
          title: "Playground Saringan Eratosthenes",
          naiExpression: "happy",
          naiDialogue: "Amati tampilan kisi saringan prima 1 sampai 60 secara langsung di kanvas.",
          sandbox: {
            title: "Simulasi Saringan Eratosthenes",
            instructions: "Pilih tab Saringan Eratosthenes di kanvas untuk mengamati pola prima hijau terang.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 29, coprimeA: 8, coprimeB: 9 },
          },
        },
        {
          id: "p2-s7",
          type: "challenge",
          title: "Misi: Deteksi Prima Kembar 29",
          naiExpression: "neutral",
          naiDialogue: "Atur slider N ke bilangan prima terbesar di bawah 30 yang membentuk pasangan prima kembar dengan 31 (Target: N = 29)!",
          challenge: {
            id: "challenge-prime-sieve29",
            title: "Targetkan Bilangan Prima N = 29",
            question:
              "Atur slider N ke bilangan prima terbesar di bawah 30 yang membentuk pasangan prima kembar dengan 31 (Target: N = 29)!",
            targetCondition: (vars) => {
              return Math.round(vars.numberN || 0) === 29;
            },
            hint1Static: "29 dan 31 memiliki selisih 2 (pasangan prima kembar).",
            hint2Static: "Geser slider N ke angka 29.",
            solutionVariables: { numberN: 29 },
            solutionExplanation: "29 adalah bilangan prima, dan (29, 31) adalah pasangan prima kembar.",
            xpReward: 40,
          },
        },
        {
          id: "p2-s8",
          type: "reflect",
          title: "Refleksi Level 2: Ritme Saringan",
          naiExpression: "celebrating",
          naiDialogue: "Hebat! Dengan saringan Eratosthenes, mencari ratusan bilangan prima menjadi sangat ritmis dan cepat!",
          reflect: {
            title: "Level 2 Tuntas: Saringan Eratosthenes & Batas √N",
            takeaways: [
              "Kita tidak perlu menguji keprimaan satu per satu, cukup eliminasi kelipatan secara ritmis.",
              "Batas pengujian keprimaan bilangan N selalu dibatasi oleh √N.",
              "Pasangan prima kembar seperti (29, 31) adalah prima yang berselisih tepat 2.",
            ],
            connectionText: "Di Level 3, kita akan mempelajari hubungan antara dua bilangan yang tidak berbagi faktor persekutuan: BILANGAN KOPRIMA!",
            nextLevelTitle: "Level 3: Bilangan Relatif Prima (Koprima)",
            badgeToUnlock: "pattern-seeker",
            xpReward: 40,
            formulaKaTeX: "d_{\\min} \\le \\sqrt{N}",
          },
        },
      ],
    },
    {
      id: "primes-level-3",
      index: 3,
      tier: 2,
      title: "Bilangan Koprima & Garis Pandang Kisi Koordinat",
      description: "Memahami hubungan dua bilangan yang tidak berbagi faktor persekutuan selain 1.",
      ahaMoment: "Dua bilangan tidak harus prima untuk menjadi saling prima (koprima): cukup jika mereka tidak berbagi satu pun faktor bersama!",
      steps: [
        {
          id: "p3-s1",
          type: "provoke",
          title: "Dua Komposit yang Saling Asing",
          naiExpression: "curious",
          naiDialogue: "Angka 8 (2³) dan 9 (3²) keduanya bukan prima. Tapi bisakah kamu menemukan faktor bersama di antara keduanya selain 1?",
          provoke: {
            hookTitle: "Mengapa 8 dan 9 Saling Prima?",
            hookText: "Faktor dari 8 adalah 1, 2, 4, 8. Faktor dari 9 adalah 1, 3, 9. Keduanya adalah bilangan komposit, tetapi satu-satunya faktor persekutuan mereka adalah 1.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 12, coprimeA: 8, coprimeB: 9 },
            question: "Disebut apakah pasangan dua bilangan yang memiliki FPB = 1?",
            options: [
              {
                id: "opt-coprime-def",
                text: "Bilangan Koprima (Relatively Prime)",
                responseText: "Tepat sekali! Koprima adalah relasi antara dua bilangan yang tidak berbagi pembagi bersama selain angka 1.",
              },
              {
                id: "opt-twin-def",
                text: "Bilangan Prima Kembar",
                responseText: "Prima kembar adalah dua bilangan prima yang berselisih 2 (seperti 3 dan 5, atau 11 dan 13).",
              },
            ],
          },
        },
        {
          id: "p3-s2",
          type: "predict",
          title: "Garis Pandang Kisi Bebas Hambatan",
          naiExpression: "thinking",
          naiDialogue: "Jika kamu berdiri di (0,0) menatap titik (8, 9) di grid kebun pohon, apakah pandanganmu terhalang pohon lain?",
          predict: {
            scenarioTitle: "Eksperimen Kebun Euclid (Orchard Problem)",
            scenarioText: "Sebuah titik koordinat integer (x, y) terlihat langsung dari (0,0) tanpa terhalang jika garis pandangnya tidak melewati titik integer lain.",
            question: "Apakah garis pandang ke titik (8, 9) terhalang atau bebas hambatan?",
            options: [
              {
                id: "pred-clear-view",
                text: "Bebas hambatan! Karena FPB(8, 9) = 1, tidak ada titik integer di antara (0,0) dan (8,9)",
                isCorrect: true,
                feedback: "Benar! Titik (4, 6) terhalang oleh (2, 3) karena FPB(4,6) = 2. Namun (8, 9) bebas hambatan karena koprima!",
              },
              {
                id: "pred-blocked-view",
                text: "Terhalang oleh titik tengah",
                isCorrect: false,
                feedback: "Titik tengah (4, 4.5) bukan koordinat bilangan bulat, jadi tidak ada pohon integer yang menghalangi.",
              },
            ],
            simulationLabel: "Uji Garis Pandang!",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 12, coprimeA: 8, coprimeB: 9 },
            simulationVariables: { numberN: 12, coprimeA: 8, coprimeB: 9 },
          },
        },
        {
          id: "p3-s3",
          type: "guided",
          title: "Simulator Garis Pandang Koprima",
          naiExpression: "happy",
          naiDialogue: "Pilih tab Garis Pandang Koprima, lalu ubah koordinat A dan B untuk melihat garis hijau (bebas) atau merah (terhalang)!",
          guided: {
            instructionTitle: "Visualisasi Kisi Resonansi Koprima",
            instructionText: "Atur nilai A dan B pada kanvas koordinat untuk mengamati bagaimana FPB menentukan status garis pandang.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 12, coprimeA: 8, coprimeB: 9 },
            observationTable: {
              headers: ["Koordinat (A, B)", "Nilai FPB(A, B)", "Status Garis Pandang"],
              rows: [
                { parameter: "(8, 9)", expectedValue: "FPB = 1", unit: "Garis Hijau (Koprima)" },
                { parameter: "(6, 8)", expectedValue: "FPB = 2", unit: "Garis Merah (Terhalang di 3,4)" },
              ],
            },
            discoveryQuestion: {
              prompt: "Kapan sebuah pecahan A/B berada dalam bentuk paling sederhana (tidak bisa disederhanakan lagi)?",
              options: [
                "Jika pembilang A dan penyebut B saling koprima: FPB(A, B) = 1",
                "Hanya jika pembilangnya bilangan prima",
                "Hanya jika penyebutnya bilangan ganjil",
              ],
              correctOption: "Jika pembilang A dan penyebut B saling koprima: FPB(A, B) = 1",
              insight: "Pecahan A/B tak tereduksi jika dan hanya jika A ⊥ B (saling koprima).",
            },
          },
        },
        {
          id: "p3-s4",
          type: "formalize",
          title: "Definisi Bilangan Koprima",
          naiExpression: "neutral",
          naiDialogue: "Mari tuangkan definisi relasi koprima ke dalam KaTeX.",
          formalize: {
            title: "Definisi Formal Relasi Koprima",
            prompt: "Lengkapi definisi formal dua bilangan saling koprima berikut:",
            formulaTemplate: "a \\perp b \\iff \\gcd(a, b) = [blank1] \\quad \\text{dan dua prima berbeda } p \\neq q \\implies \\gcd(p, q) = [blank2]",
            blanks: [
              { id: "blank1", label: "Nilai FPB", options: ["1", "0", "a \\cdot b"], correctOption: "1" },
              { id: "blank2", label: "FPB Dua Prima", options: ["1", "2", "p"], correctOption: "1" },
            ],
            resolvedFormulaKaTeX: "a \\perp b \\iff \\gcd(a, b) = 1 \\quad \\text{dan } p \\neq q \\implies \\gcd(p, q) = 1",
            explanation: "Dua bilangan disebut relatif prima jika tidak berbagi pembagi bersama selain 1. Dua bilangan prima berbeda selalu saling koprima.",
          },
        },
        {
          id: "p3-s5",
          type: "check",
          title: "Deteksi Pasangan Koprima",
          naiExpression: "thinking",
          naiDialogue: "Manakah dari pasangan bilangan berikut yang BUKAN merupakan pasangan koprima?",
          check: {
            question: "Manakah dari pasangan berikut yang BUKAN pasangan koprima?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-15-25", text: "(15, 25) karena keduanya habis dibagi 5 (FPB = 5 ≠ 1)", isCorrect: true, explanation: "Tepat sekali! 15 dan 25 berbagi faktor persekutuan 5, sehingga bukan koprima." },
              { id: "opt-14-15", text: "(14, 15)", isCorrect: false, explanation: "14 dan 15 adalah bilangan berurutan, sehingga FPB-nya selalu 1 (koprima)." },
              { id: "opt-9-28", text: "(9, 28)", isCorrect: false, explanation: "9 = 3² dan 28 = 2² × 7, tidak berbagi faktor bersama selain 1 (koprima)." },
            ],
            explanation: "FPB(15, 25) = 5 ≠ 1, jadi (15, 25) bukan pasangan koprima.",
          },
        },
        {
          id: "p3-s6",
          type: "sandbox",
          title: "Playground Garis Pandang Koprima",
          naiExpression: "happy",
          naiDialogue: "Atur koordinat A dan B di kanvas untuk mengeksplorasi garis pandang bebas hambatan.",
          sandbox: {
            title: "Simulasi Titik Pandang Koordinat",
            instructions: "Ubah koordinat A dan B untuk melihat garis pandang hijau atau merah.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 12, coprimeA: 7, coprimeB: 5 },
          },
        },
        {
          id: "p3-s7",
          type: "challenge",
          title: "Tantangan: Garis Pandang Bebas Koprima (A = 7, B = 5)",
          naiExpression: "neutral",
          naiDialogue: "Atur koordinat A = 7 dan koordinat B = 5 sehingga garis pandang berwarna hijau bebas hambatan (FPB = 1)!",
          challenge: {
            id: "challenge-prime-coprime-pair",
            title: "Konfigurasi Pasangan Koprima",
            question:
              "Atur koordinat A = 7 dan koordinat B = 5 sehingga garis pandang berwarna hijau bebas hambatan (FPB = 1)!",
            targetCondition: (vars) => {
              const a = Math.round(vars.coprimeA || 0);
              const b = Math.round(vars.coprimeB || 0);
              return a === 7 && b === 5 && isCoprime(a, b);
            },
            hint1Static: "Atur slider koordinat A ke 7 dan koordinat B ke 5.",
            hint2Static: "7 dan 5 adalah dua bilangan prima berbeda, sehingga dijamin 100% koprima.",
            solutionVariables: { coprimeA: 7, coprimeB: 5 },
            solutionExplanation: "FPB(7, 5) = 1. Garis pandang dari (0,0) ke (7,5) tidak terhalang oleh titik integer mana pun.",
            xpReward: 50,
          },
        },
        {
          id: "p3-s8",
          type: "reflect",
          title: "Refleksi Level 3: Harmoni Tanpa Faktor Bersama",
          naiExpression: "celebrating",
          naiDialogue: "Koprima adalah konsep relasional: tentang keharmonisan hubungan antara dua bilangan!",
          reflect: {
            title: "Level 3 Tuntas: Bilangan Relatif Prima (Koprima)",
            takeaways: [
              "Dua bilangan koprima tidak memiliki faktor persekutuan selain 1 (FPB = 1).",
              "Garis pandang dari (0,0) ke (A, B) bebas hambatan jika dan hanya jika A ⊥ B.",
              "Koprima adalah syarat mutlak pecahan paling sederhana dan eksistensi invers modular.",
            ],
            connectionText: "Di Level 4, kita akan menghitung berapa banyak bilangan yang koprima dengan n lewat FUNGSI TOTIENT EULER φ(n)!",
            nextLevelTitle: "Level 4: Fungsi Totient Euler & Fondasi RSA",
            badgeToUnlock: "pattern-seeker",
            xpReward: 50,
            formulaKaTeX: "\\gcd(a, b) = 1",
          },
        },
      ],
    },
    {
      id: "primes-level-4",
      index: 4,
      tier: 2,
      title: "Fungsi Totient Euler & Pondasi RSA",
      description: "Menghitung banyak bilangan yang koprima dengan n melalui fungsi phi(n).",
      ahaMoment: "Fungsi Euler φ(n) menghitung berapa banyak angka yang bersahabat (koprima) dengan n sebelum mencapainya!",
      steps: [
        {
          id: "p4-s1",
          type: "provoke",
          title: "Berapa Banyak Sahabat Angka 10?",
          naiExpression: "curious",
          naiDialogue: "Dari angka 1 sampai 10, jika kita coret semua angka yang punya faktor bersama dengan 10 (kelipatan 2 dan 5), berapa angka yang tersisa?",
          provoke: {
            hookTitle: "Menghitung Sahabat Bilangan n",
            hookText: "Deretan angka: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. Angka 2, 4, 6, 8, 10 (kelipatan 2) dan 5 (kelipatan 5) dicoret.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 10, coprimeA: 8, coprimeB: 9 },
            question: "Angka berapa sajakah yang tersisa (koprima dengan 10)?",
            options: [
              {
                id: "opt-4-left",
                text: "Tepat ada 4 angka: {1, 3, 7, 9}, sehingga φ(10) = 4",
                responseText: "Tepat sekali! Inilah fungsi Totient Euler: φ(n) menghitung banyak bilangan bulat positif k ≤ n yang memenuhi FPB(k, n) = 1.",
              },
              {
                id: "opt-2-left",
                text: "Hanya 2 angka saja.",
                responseText: "Kurang tepat. 1, 3, 7, dan 9 semuanya saling prima dengan 10.",
              },
            ],
          },
        },
        {
          id: "p4-s2",
          type: "predict",
          title: "Bagaimana Jika Angkanya Prima p?",
          naiExpression: "thinking",
          naiDialogue: "Jika p adalah bilangan prima 7, berapa banyak angka di bawah 7 yang koprima dengan 7?",
          predict: {
            scenarioTitle: "Totient Bilangan Prima",
            scenarioText: "Angka di bawah 7 adalah: 1, 2, 3, 4, 5, 6. Karena 7 prima, ia tidak punya faktor selain 1 dan 7.",
            question: "Berapakah nilai φ(7)?",
            options: [
              {
                id: "pred-6-prime",
                text: "6 angka (semua angka 1 sampai p - 1 koprima dengan p!)",
                isCorrect: true,
                feedback: "Benar! Untuk sembarang bilangan prima p, rumusnya sangat sederhana: φ(p) = p - 1.",
              },
              {
                id: "pred-3-prime",
                text: "3 angka",
                isCorrect: false,
                feedback: "Karena 7 prima, tidak ada satu pun angka di bawah 7 yang membagi 7.",
              },
            ],
            simulationLabel: "Buktikan φ(p) = p - 1!",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 7, coprimeA: 8, coprimeB: 9 },
            simulationVariables: { numberN: 7, coprimeA: 8, coprimeB: 9 },
          },
        },
        {
          id: "p4-s3",
          type: "guided",
          title: "Totient Perkalian Dua Prima: φ(p × q)",
          naiExpression: "happy",
          naiDialogue: "Geser N ke 15 (yaitu 3 × 5). Amati nilai totient Euler φ(15) pada HUD indikator!",
          guided: {
            instructionTitle: "Rumus Emas Kriptografi RSA",
            instructionText: "Pada matriks 3 × 5, kotak bersih yang tersisa selalu persis berukuran (p - 1) × (q - 1).",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 15, coprimeA: 8, coprimeB: 9 },
            observationTable: {
              headers: ["Modulus N = p × q", "Faktor Prima", "Nilai Totient φ(N) = (p-1)(q-1)"],
              rows: [
                { parameter: "N = 15", expectedValue: "3 × 5", unit: "φ(15) = (2)(4) = 8" },
                { parameter: "N = 77", expectedValue: "7 × 11", unit: "φ(77) = (6)(10) = 60" },
              ],
            },
            discoveryQuestion: {
              prompt: "Mengapa rumus φ(p · q) = (p - 1)(q - 1) menjadi rahasia keamanan enkripsi RSA?",
              options: [
                "Menghitung p × q sangat mudah, tetapi memfaktorkan kembali N menjadi p dan q untuk mencari φ(N) sangat sulit bagi peretas",
                "Karena RSA hanya bekerja pada angka di bawah 100",
                "Hanya kebetulan formula",
              ],
              correctOption: "Menghitung p × q sangat mudah, tetapi memfaktorkan kembali N menjadi p dan q untuk mencari φ(N) sangat sulit bagi peretas",
              insight: "Inilah fungsi pintu jebakan (trapdoor function) yang melindungi transaksi perbankan di seluruh dunia!",
            },
          },
        },
        {
          id: "p4-s4",
          type: "formalize",
          title: "Formula Fungsi Totient Euler",
          naiExpression: "neutral",
          naiDialogue: "Mari tuangkan rumus totient prima dan multiplikatif ke dalam KaTeX.",
          formalize: {
            title: "Formula Fungsi Euler φ(n)",
            prompt: "Lengkapi rumus totient prima dan produk prima berikut:",
            formulaTemplate: "\\phi(p) = [blank1] \\quad \\text{dan untuk } p, q \\text{ prima: } \\phi(p \\cdot q) = [blank2]",
            blanks: [
              { id: "blank1", label: "Totient Prima Tunggal", options: ["p - 1", "p", "p + 1"], correctOption: "p - 1" },
              { id: "blank2", label: "Totient Dua Prima", options: ["(p - 1)(q - 1)", "p \\cdot q - 1", "p + q"], correctOption: "(p - 1)(q - 1)" },
            ],
            resolvedFormulaKaTeX: "\\phi(p) = p - 1 \\quad \\text{dan} \\quad \\phi(p \\cdot q) = (p - 1)(q - 1)",
            explanation: "Fungsi Euler bersifat multiplikatif untuk bilangan yang saling koprima: φ(m · n) = φ(m) · φ(n).",
          },
        },
        {
          id: "p4-s5",
          type: "check",
          title: "Cek Hitung Cepat Totient",
          naiExpression: "thinking",
          naiDialogue: "Hitung nilai φ(77) menggunakan rumus perkalian dua prima!",
          check: {
            question: "Berapakah nilai dari φ(77)? (Petunjuk: 77 = 7 × 11)",
            checkType: "multiple_choice",
            options: [
              { id: "opt-60-totient", text: "60 (karena (7 - 1) × (11 - 1) = 6 × 10 = 60)", isCorrect: true, explanation: "Tepat sekali! φ(77) = 6 × 10 = 60 angka koprima." },
              { id: "opt-76-totient", text: "76", isCorrect: false, explanation: "76 hanya benar jika 77 adalah bilangan prima murni." },
              { id: "opt-70-totient", text: "70", isCorrect: false, explanation: "Periksa kembali perkalian 6 × 10." },
            ],
            explanation: "φ(77) = φ(7) · φ(11) = (7 - 1)(11 - 1) = 6 · 10 = 60.",
          },
        },
        {
          id: "p4-s6",
          type: "sandbox",
          title: "Playground Totient Euler",
          naiExpression: "happy",
          naiDialogue: "Geser N untuk melihat perubahan nilai totient Euler φ(N) di HUD indikator.",
          sandbox: {
            title: "Simulasi Totient Euler",
            instructions: "Geser N untuk melihat perubahan nilai totient Euler φ(N) di HUD indikator.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 15, coprimeA: 8, coprimeB: 9 },
          },
        },
        {
          id: "p4-s7",
          type: "challenge",
          title: "Misi: Temukan Bilangan dengan φ(N) = 8",
          naiExpression: "neutral",
          naiDialogue: "Atur N = 15 (hasil kali dua prima 3 dan 5) sehingga nilai totient Euler φ(15) = 8!",
          challenge: {
            id: "challenge-prime-totient15",
            title: "Konfigurasi Totient φ(15) = 8",
            question:
              "Atur N = 15 (hasil kali dua prima 3 dan 5). Berapakah nilai totient Euler φ(15) = (3 - 1)(5 - 1)? Target: N = 15!",
            targetCondition: (vars) => {
              return Math.round(vars.numberN || 0) === 15;
            },
            hint1Static: "15 = 3 x 5. Rumus totient: (3 - 1) x (5 - 1) = 2 x 4 = 8.",
            hint2Static: "Geser slider N ke angka 15.",
            solutionVariables: { numberN: 15 },
            solutionExplanation: "φ(15) = (3 - 1) * (5 - 1) = 2 * 4 = 8. Terdapat 8 angka koprima dengan 15: 1, 2, 4, 7, 8, 11, 13, 14.",
            xpReward: 50,
          },
        },
        {
          id: "p4-s8",
          type: "reflect",
          title: "Refleksi Level 4: Jantung Kriptografi Modern",
          naiExpression: "celebrating",
          naiDialogue: "Rumus sederhana φ(p · q) = (p - 1)(q - 1) adalah pilar algoritma keamanan data dunia!",
          reflect: {
            title: "Level 4 Tuntas: Fungsi Totient Euler & RSA",
            takeaways: [
              "Fungsi φ(n) menghitung banyaknya bilangan bulat positif ≤ n yang saling koprima dengan n.",
              "Untuk bilangan prima: φ(p) = p - 1.",
              "Untuk hasil kali dua bilangan prima: φ(p · q) = (p - 1)(q - 1).",
            ],
            connectionText: "Di Level 5, kita akan melengkapi perjalanan ini dengan TEOREMA KECIL FERMAT yang melegenda!",
            nextLevelTitle: "Level 5: Teorema Kecil Fermat & Kunci Publik",
            badgeToUnlock: "pattern-seeker",
            xpReward: 50,
            formulaKaTeX: "\\phi(p \\cdot q) = (p - 1)(q - 1)",
          },
        },
      ],
    },
    {
      id: "primes-level-5",
      index: 5,
      tier: 3,
      title: "Teorema Kecil Fermat & Kunci Publik",
      description: "Siklus perulangan pangkat modular a^(p-1) = 1 (mod p).",
      ahaMoment: "Jika kamu memangkatkan angka koprima sebanyak p - 1 kali di modulo prima p, hasilnya SELALU kembali ke 1!",
      steps: [
        {
          id: "p5-s1",
          type: "provoke",
          title: "Siklus Pangkat yang Ajaib",
          naiExpression: "curious",
          naiDialogue: "Mengapa angka berapa pun yang dipangkatkan 6 selalu menghasilkan sisa 1 di modulo 7?",
          provoke: {
            hookTitle: "Keteraturan Ajaib Pierre de Fermat",
            hookText: "Pada modulo prima p = 7: coba 3⁶ = 729 = 104 × 7 + 1 ≡ 1. Coba 5⁶ = 15625 = 2232 × 7 + 1 ≡ 1!",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 7, coprimeA: 3, coprimeB: 5 },
            question: "Apakah fenomena a^(p-1) ≡ 1 (mod p) selalu berlaku untuk semua bilangan prima p?",
            options: [
              {
                id: "opt-fermat-always",
                text: "Ya, selalu berlaku untuk setiap bilangan prima p dan a yang koprima dengan p!",
                responseText: "Tepat sekali! Ini adalah Teorema Kecil Fermat (1640) yang memungkinkan perulangan siklus kunci kriptografi.",
              },
              {
                id: "opt-fermat-coinc",
                text: "Hanya kebetulan pada angka 3 dan 5 saja.",
                responseText: "Bukan kebetulan! Ini adalah teorema universal yang telah terbukti secara matematis.",
              },
            ],
          },
        },
        {
          id: "p5-s2",
          type: "predict",
          title: "Sederhanakan Pangkat Raksasa",
          naiExpression: "thinking",
          naiDialogue: "Berapakah sisa pembagian 2¹⁰⁰ jika dibagi oleh prima 13?",
          predict: {
            scenarioTitle: "Aplikasi Teorema Fermat pada Pangkat 100",
            scenarioText: "Karena 13 adalah prima, maka menurut Fermat: 2¹² ≡ 1 (mod 13). 100 = 8 × 12 + 4.",
            question: "Berapakah sisa pembagian 2¹⁰⁰ mod 13?",
            options: [
              {
                id: "pred-3-fermat",
                text: "3 (karena 2¹⁰⁰ ≡ (2¹²)⁸ · 2⁴ ≡ 1⁸ · 16 ≡ 16 mod 13 = 3)",
                isCorrect: true,
                feedback: "Brilian! Pangkat 100 yang raksasa lenyap seketika menjadi 2⁴ = 16 ≡ 3 (mod 13). Sungguh luar biasa!",
              },
              {
                id: "pred-1-fermat",
                text: "1",
                isCorrect: false,
                feedback: "100 bukan kelipatan tepat dari 12, bersisa 4.",
              },
            ],
            simulationLabel: "Buktikan Pangkat Modular!",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 11, coprimeA: 3, coprimeB: 5 },
            simulationVariables: { numberN: 11, coprimeA: 3, coprimeB: 5 },
          },
        },
        {
          id: "p5-s3",
          type: "guided",
          title: "Playground Teorema Fermat",
          naiExpression: "happy",
          naiDialogue: "Atur N ke bilangan prima (seperti 7 atau 11) dan amati sifat keteraturan sisa bagi pangkatnya!",
          guided: {
            instructionTitle: "Simulator Siklus Fermat a^(p-1) ≡ 1",
            instructionText: "Untuk p = 11, pangkat siklus identitasnya adalah p - 1 = 10.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 11, coprimeA: 3, coprimeB: 5 },
            observationTable: {
              headers: ["Modulus Prima p", "Pangkat Siklus p - 1", "Sisa Bagi a^(p-1) mod p"],
              rows: [
                { parameter: "p = 7", expectedValue: "pangkat 6", unit: "≡ 1" },
                { parameter: "p = 11", expectedValue: "pangkat 10", unit: "≡ 1" },
              ],
            },
            discoveryQuestion: {
              prompt: "Apa syarat utama agar Teorema Kecil Fermat a^(p-1) ≡ 1 (mod p) berlaku?",
              options: [
                "p harus bilangan prima dan a tidak habis dibagi p (FPB(a, p) = 1)",
                "a harus bilangan genap",
                "p harus lebih besar dari 100",
              ],
              correctOption: "p harus bilangan prima dan a tidak habis dibagi p (FPB(a, p) = 1)",
              insight: "Syarat mutlaknya adalah p prima dan a saling koprima dengan p.",
            },
          },
        },
        {
          id: "p5-s4",
          type: "formalize",
          title: "Teorema Kecil Fermat (Fermat's Little Theorem)",
          naiExpression: "neutral",
          naiDialogue: "Mari formulasikan Teorema Kecil Fermat ke dalam KaTeX.",
          formalize: {
            title: "Teorema Kecil Fermat",
            prompt: "Lengkapi identitas teorema Fermat berikut:",
            formulaTemplate: "\\gcd(a, p) = 1 \\implies a^{[blank1]} \\equiv 1 \\pmod p \\quad \\text{atau} \\quad a^p \\equiv [blank2] \\pmod p",
            blanks: [
              { id: "blank1", label: "Pangkat Siklus", options: ["p - 1", "p", "p + 1"], correctOption: "p - 1" },
              { id: "blank2", label: "Bentuk Kalikan a", options: ["a", "1", "0"], correctOption: "a" },
            ],
            resolvedFormulaKaTeX: "a^{p-1} \\equiv 1 \\pmod p \\quad \\text{dan} \\quad a^p \\equiv a \\pmod p",
            explanation: "Teorema Fermat memungkinkan enkripsi eksponensial di mana eksponen dapat didekripsi kembali menggunakan invers totient.",
          },
        },
        {
          id: "p5-s5",
          type: "check",
          title: "Cek Nalar Fermat",
          naiExpression: "thinking",
          naiDialogue: "Berapakah sisa bagi dari 5⁴² jika dibagi oleh bilangan prima 43?",
          check: {
            question: "Berapakah sisa dari 5⁴² mod 43? (Ingat: 43 adalah bilangan prima!)",
            checkType: "multiple_choice",
            options: [
              { id: "opt-1-fermat-check", text: "1 (karena 43 prima, maka 5⁴² = 5^(43-1) ≡ 1 mod 43)", isCorrect: true, explanation: "Tepat sekali! Menurut Teorema Fermat, langsung bernilai 1 tanpa perlu menghitung sepeser pun." },
              { id: "opt-5-fermat-check", text: "5", isCorrect: false, explanation: "5 adalah hasil jika dipangkatkan 43 (mod 43), bukan pangkat 42." },
            ],
            explanation: "a^(p-1) ≡ 1 (mod p) -> 5^(43-1) = 5^42 ≡ 1 (mod 43).",
          },
        },
        {
          id: "p5-s6",
          type: "sandbox",
          title: "Playground Siklus Fermat",
          naiExpression: "happy",
          naiDialogue: "Atur N ke bilangan prima 11 dan amati siklus pangkatnya di kanvas.",
          sandbox: {
            title: "Simulasi Siklus Fermat",
            instructions: "Atur N ke bilangan prima 11 dan amati keteraturan sisa bagi pangkatnya.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 11, coprimeA: 3, coprimeB: 5 },
          },
        },
        {
          id: "p5-s7",
          type: "challenge",
          title: "Tantangan: Buktikan Fermat pada p = 11",
          naiExpression: "neutral",
          naiDialogue: "Atur slider N ke bilangan prima p = 11 untuk membuktikan bahwa a¹⁰ ≡ 1 (mod 11)!",
          challenge: {
            id: "challenge-prime-fermat11",
            title: "Konfigurasi Modulus Prima p = 11",
            question:
              "Atur slider N ke bilangan prima p = 11 untuk membuktikan bahwa a¹⁰ ≡ 1 (mod 11) bagi setiap angka yang koprima dengan 11!",
            targetCondition: (vars) => {
              return Math.round(vars.numberN || 0) === 11;
            },
            hint1Static: "Geser slider N ke bilangan prima 11.",
            hint2Static: "Menurut Teorema Fermat, pangkat siklusnya adalah p - 1 = 11 - 1 = 10.",
            solutionVariables: { numberN: 11 },
            solutionExplanation: "Untuk p = 11 prima, a^10 = 1 (mod 11) untuk setiap gcd(a, 11) = 1.",
            xpReward: 60,
          },
        },
        {
          id: "p5-s8",
          type: "reflect",
          title: "Refleksi Level 5: Mahakarya Pierre de Fermat",
          naiExpression: "celebrating",
          naiDialogue: "Menakjubkan! Kamu telah membuktikan Teorema Kecil Fermat yang melegenda!",
          reflect: {
            title: "Level 5 Tuntas: Teorema Kecil Fermat",
            takeaways: [
              "Untuk setiap bilangan prima p dan a yang koprima dengan p: a^(p-1) ≡ 1 (mod p).",
              "Siklus pangkat modular ini memungkinkan penyederhanaan pangkat eksponensial raksasa.",
              "Teorema Fermat adalah gerbang pengujian keprimaan cepat pada algoritma komputer modern.",
            ],
            connectionText: "Saatnya menuntaskan seluruh petualangan Teori Bilangan di Boss Level Pamungkas!",
            nextLevelTitle: "Boss Level: Ujian Modul Faktorisasi Prima",
            badgeToUnlock: "pattern-seeker",
            xpReward: 60,
            formulaKaTeX: "a^{p-1} \\equiv 1 \\pmod p",
          },
        },
      ],
    },
    {
      id: "primes-level-6",
      index: 6,
      tier: 3,
      title: "Boss Level: Ujian Modul Faktorisasi Prima & Koprima",
      description: "Ujian menyeluruh menguji atom prima, saringan Eratosthenes, relasi koprima, dan fungsi Euler.",
      ahaMoment: "Bilangan prima adalah fondasi kekal yang menopang seluruh struktur matematika modern!",
      steps: [
        {
          id: "p6-s1",
          type: "provoke",
          title: "Ujian Akhir Modul Teori Bilangan",
          naiExpression: "thinking",
          naiDialogue: "Kamu telah menyelesaikan kisi balok, saringan Eratosthenes, garis pandang koprima, fungsi Euler, hingga Teorema Fermat. Buktikan keahlianmu!",
          provoke: {
            hookTitle: "Ujian Akhir Teori Bilangan & Kriptografi",
            hookText: "Boss Level ini menguji seluruh penguasaan konsep faktorisasi prima dan koprima dari Level 1 sampai Level 5.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
            question: "Jika N = 2³ × 3² × 5, berapa banyak total faktor pembagi positif dari bilangan N?",
            options: [
              {
                id: "opt-24-factors",
                text: "24 faktor pembagi (karena (3+1) × (2+1) × (1+1) = 4 × 3 × 2 = 24)",
                responseText: "Brilian! Rumus kombinatorika kisi faktor (e_1 + 1)(e_2 + 1)...(e_k + 1) langsung menghitung seluruh faktor tanpa perlu mendaftar satu per satu!",
              },
              {
                id: "opt-6-factors",
                text: "Hanya 6 faktor",
                responseText: "Kurang tepat. 6 hanyalah jumlah eksponennya, bukan kombinasi faktornya.",
              },
            ],
          },
        },
        {
          id: "p6-s2",
          type: "predict",
          title: "Verifikasi Pasangan Koprima Master",
          naiExpression: "thinking",
          naiDialogue: "Apakah pasangan A = 9 dan B = 7 saling koprima?",
          predict: {
            scenarioTitle: "Uji Koprima Cepat",
            scenarioText: "9 = 3² dan 7 adalah bilangan prima.",
            question: "Berapakah FPB(9, 7)?",
            options: [
              {
                id: "pred-1-boss",
                text: "1 (keduanya saling koprima, garis pandang bebas hambatan)",
                isCorrect: true,
                feedback: "Benar! FPB(9, 7) = 1, sehingga garis pandang berwarna hijau terang.",
              },
              {
                id: "pred-3-boss",
                text: "3",
                isCorrect: false,
                feedback: "7 tidak habis dibagi 3.",
              },
            ],
            simulationLabel: "Buktikan Garis Pandang (9, 7)!",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
            simulationVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
          },
        },
        {
          id: "p6-s3",
          type: "guided",
          title: "Simulator Penuh Prima & Koprima",
          naiExpression: "happy",
          naiDialogue: "Eksplorasi hubungan antara bilangan prima N = 37 dan pasangan koprima (9, 7) di kanvas!",
          guided: {
            instructionTitle: "Laboratorium Terpadu Teori Bilangan",
            instructionText: "Atur N ke 37, koordinat A ke 9, dan koordinat B ke 7.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
            observationTable: {
              headers: ["Parameter", "Nilai", "Verifikasi Teorema"],
              rows: [
                { parameter: "N = 37", expectedValue: "Prima", unit: "φ(37) = 36" },
                { parameter: "A = 9, B = 7", expectedValue: "FPB = 1", unit: "Koprima Murni" },
              ],
            },
            discoveryQuestion: {
              prompt: "Berapakah nilai dari 2³⁶ mod 37 menurut Teorema Fermat?",
              options: [
                "Tepat bernilai 1",
                "Bernilai 2",
                "Bernilai 36",
              ],
              correctOption: "Tepat bernilai 1",
              insight: "Karena 37 prima, maka a^(37-1) = a^36 ≡ 1 (mod 37).",
            },
          },
        },
        {
          id: "p6-s4",
          type: "formalize",
          title: "Hukum Agung Semesta Aritmetika",
          naiExpression: "neutral",
          naiDialogue: "Mari kita tuangkan rangkuman universal teori bilangan prima ke dalam KaTeX.",
          formalize: {
            title: "Pondasi Abadi Aritmetika",
            prompt: "Lengkapi identitas teorema dasar bilangan:",
            formulaTemplate: "\\forall n > 1, \\quad n = \\prod_{i} p_i^{[blank1]} \\quad \\text{dan} \\quad a^{\\phi(n)} \\equiv [blank2] \\pmod n",
            blanks: [
              { id: "blank1", label: "Eksponen Prima", options: ["a_i", "1", "n"], correctOption: "a_i" },
              { id: "blank2", label: "Teorema Euler-Fermat", options: ["1", "0", "a"], correctOption: "1" },
            ],
            resolvedFormulaKaTeX: "\\forall n > 1, \\quad n = \\prod_{i} p_i^{a_i} \\quad \\text{dan} \\quad a^{\\phi(n)} \\equiv 1 \\pmod n",
            explanation: "Teorema Euler menggeneralisasi Teorema Fermat untuk sembarang modulus n: jika FPB(a, n) = 1, maka a^φ(n) ≡ 1 (mod n).",
          },
        },
        {
          id: "p6-s5",
          type: "check",
          title: "Cek Evaluasi Komprehensif",
          naiExpression: "thinking",
          naiDialogue: "Pertanyaan evaluasi terakhir sebelum mengeksekusi misi penutupan!",
          check: {
            question: "Manakah dari bilangan berikut yang merupakan bilangan prima?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-127-prime", text: "127 (tidak habis dibagi 2, 3, 5, 7, 11 karena √127 ≈ 11.27)", isCorrect: true, explanation: "Tepat sekali! 119 = 7 × 17, 133 = 7 × 19, 143 = 11 × 13. Hanya 127 yang prima murni!" },
              { id: "opt-119-prime", text: "119", isCorrect: false, explanation: "119 = 7 × 17, adalah bilangan komposit." },
              { id: "opt-143-prime", text: "143", isCorrect: false, explanation: "143 = 11 × 13, adalah bilangan komposit." },
            ],
            explanation: "Uji prima sampai √N membuktikan hanya 127 yang tidak memiliki faktor pembagi.",
          },
        },
        {
          id: "p6-s6",
          type: "sandbox",
          title: "Playground Boss Level",
          naiExpression: "happy",
          naiDialogue: "Uji coba konfigurasi parameter sebelum menyelesaikan misi akhir.",
          sandbox: {
            title: "Simulasi Bebas Boss Level",
            instructions: "Eksplorasi hubungan antara N, koordinat A, dan koordinat B.",
            interactiveComponentSlug: "math-primes-coprime",
            initialVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
          },
        },
        {
          id: "p6-s7",
          type: "challenge",
          title: "Misi Terakhir: Konfigurasi Prima & Koprima Master",
          naiExpression: "neutral",
          naiDialogue: "Atur N ke bilangan prima 37, koordinat A = 9, dan koordinat B = 7 (keduanya saling koprima dengan FPB = 1)!",
          challenge: {
            id: "challenge-prime-boss-mastery",
            title: "Mastery: Prima N = 37 & Pasangan Koprima (9, 7)",
            question:
              "Atur N ke bilangan prima 37, koordinat A = 9, dan koordinat B = 7 (keduanya saling koprima dengan FPB = 1)!",
            targetCondition: (vars) => {
              const n = Math.round(vars.numberN || 0);
              const a = Math.round(vars.coprimeA || 0);
              const b = Math.round(vars.coprimeB || 0);
              return n === 37 && a === 9 && b === 7 && isPrime(n) && isCoprime(a, b);
            },
            hint1Static: "Atur N ke 37, koordinat A ke 9, dan koordinat B ke 7.",
            hint2Static: "37 adalah prima atom. 9 dan 7 koprima karena FPB(9, 7) = 1.",
            solutionVariables: { numberN: 37, coprimeA: 9, coprimeB: 7 },
            solutionExplanation: "N = 37 adalah bilangan prima. Pasangan (9, 7) memiliki FPB = 1 sehingga garis pandang bebas hambatan.",
            xpReward: 100,
          },
        },
        {
          id: "p6-s8",
          type: "reflect",
          title: "Kelulusan Modul Faktorisasi Prima",
          naiExpression: "celebrating",
          naiDialogue: "Luar biasa! Kamu telah resmi menguasai Faktorisasi Prima & Bilangan Koprima hingga ke arsitektur kriptografi modern!",
          reflect: {
            title: "Modul Selesai: Master Bilangan Prima & Kriptografi",
            takeaways: [
              "Bilangan prima adalah partikel atom penyusun semesta aritmetika.",
              "Saringan Eratosthenes dan batas √N menyaring prima secara efisien.",
              "Koprima adalah relasi nir-faktor sekutu yang membentuk garis pandang bebas kisi koordinat.",
              "Fungsi Euler φ(n) dan Teorema Fermat adalah pilar pertahanan enkripsi informasi dunia.",
            ],
            connectionText: "Selamat! Kamu telah menuntaskan seluruh Fondasi Matematika 1A: Bilangan & Aritmetika!",
            badgeToUnlock: "prime-grandmaster",
            xpReward: 100,
            formulaKaTeX: "\\forall n > 1, \\quad n = \\prod_{i} p_i^{a_i}",
          },
        },
      ],
    },
  ],
};
