import { TopicModule } from "@/types/topic";

export const realNumbersModule: TopicModule = {
  id: "math-real-numbers-line",
  slug: "math-real-numbers-line",
  title: "Operasi Bilangan Riil & Garis Bilangan",
  category: "math",
  summary:
    "Mengubah angka dari sekadar hafalan mati di atas kertas menjadi entitas ruang geometris: posisi, perpindahan vektor 1D, faktor skala dilatasi, kerapatan pecahan tak hingga, dan penemuan bilangan irasional.",
  audioNarrationText:
    "Selamat datang di modul Operasi Bilangan Riil dan Garis Bilangan. Di sini kamu akan menjelajahi angka sebagai pergerakan spasial nyata di atas jalan raya bilangan tak hingga.",
  initialVariables: {
    point1: 3,
    point2: -4,
    scaleFactor: 2,
    sqrtN: 2,
    zoomLevel: 1,
    distribA: 3,
    distribB: 4,
    distribC: 2,
  },
  levels: [
    {
      id: "real-level-1",
      index: 1,
      tier: 1,
      title: "Garis Bilangan & Operasi Translasi",
      description: "Penjumlahan dan pengurangan sebagai perpindahan arah vektor 1 dimensi.",
      ahaMoment: "Menjumlahkan dan mengurangkan hanyalah melangkah maju atau mundur di jalan raya bilangan!",
      steps: [
        {
          id: "r1-s1",
          type: "provoke",
          title: "Di Mana Rumah Angka?",
          naiExpression: "curious",
          naiDialogue: "Jika pohon di posisi 0, di manakah kita meletakkan sumur 3 langkah ke kiri dan rumah 4 langkah ke kanan?",
          provoke: {
            hookTitle: "Di Mana Rumah Angka?",
            hookText: "Bayangkan sebuah garis jalan raya kosong. Titik acuan pohon kita tetapkan sebagai angka nol.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 0, point2: 0, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
            question: "Apa arti sebenarnya dari tanda minus (-) pada garis bilangan?",
            options: [
              {
                id: "opt-dir",
                text: "Tanda minus menunjukkan arah berlawanan (ke kiri) dari titik acuan nol.",
                responseText: "Tepat sekali! Tanda negatif bukan berarti ketiadaan, melainkan arah vektor yang berlawanan dari arah positif.",
              },
              {
                id: "opt-broken",
                text: "Tanda minus berarti angkanya rusak atau bernilai kosong.",
                responseText: "Kurang tepat. Bilangan negatif adalah posisi koordinat fisik yang sah dan nyata di sebelah kiri nol.",
              },
            ],
          },
        },
        {
          id: "r1-s2",
          type: "predict",
          title: "Maju atau Mundur?",
          naiExpression: "thinking",
          naiDialogue: "Jika plus artinya maju searah wajah dan minus artinya membalik badan, di manakah katak mendarat?",
          predict: {
            scenarioTitle: "Lompatan Katak 1D",
            scenarioText: "Katak sedang berada di angka 2. Operasi yang diminta adalah: 2 + (-5).",
            question: "Di angka berapakah katak akan mendarat setelah melompat?",
            options: [
              {
                id: "pred-p7",
                text: "+7",
                isCorrect: false,
                feedback: "Jika melangkah ke kanan katak mendarat di 7, tapi ini adalah penjumlahan dengan bilangan negatif!",
              },
              {
                id: "pred-m3",
                text: "-3",
                isCorrect: true,
                feedback: "Benar! Menambah -5 sama artinya dengan melangkah 5 langkah ke arah kiri: 2 - 5 = -3.",
              },
              {
                id: "pred-m7",
                text: "-7",
                isCorrect: false,
                feedback: "Terlalu jauh ke kiri. Katak mulai melompat dari posisi 2, bukan dari nol.",
              },
            ],
            simulationLabel: "Lompatkan Katak!",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 2, point2: 0, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
            simulationVariables: { point1: 2, point2: -3, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
          },
        },
        {
          id: "r1-s3",
          type: "guided",
          title: "Vektor Perpindahan 1D",
          naiExpression: "happy",
          naiDialogue: "Geser titik A dan B. Amati bagaimana perpindahan selalu menggeser posisi ke kiri atau kanan!",
          guided: {
            instructionTitle: "Eksplorasi Vektor Translasi",
            instructionText: "Geser slider titik A dan B untuk mengamati bagaimana selisih koordinat menentukan panjang dan arah vektor.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 3, point2: -4, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
            observationTable: {
              headers: ["Titik Awal A", "Perpindahan Δx", "Posisi Akhir B"],
              rows: [
                { parameter: "Awal = 3", expectedValue: "-4", unit: "posisi" },
                { parameter: "Awal = -5", expectedValue: "+3", unit: "posisi" },
              ],
            },
            discoveryQuestion: {
              prompt: "Apa akibat menjumlahkan bilangan negatif terhadap posisi titik di garis bilangan?",
              options: [
                "Selalu menggeser titik ke arah kiri",
                "Selalu menggeser titik ke arah kanan",
                "Titik diam di tempat",
              ],
              correctOption: "Selalu menggeser titik ke arah kiri",
              insight: "Operasi a + (-b) bernilai sama persis dengan pengurangan a - b, yaitu translasi ke arah kiri.",
            },
          },
        },
        {
          id: "r1-s4",
          type: "formalize",
          title: "Formalisasi Translasi & Jarak",
          naiExpression: "neutral",
          naiDialogue: "Mari kita tuangkan hasil eksplorasi spasialmu ke dalam rumus matematika formal.",
          formalize: {
            title: "Hukum Translasi & Definisi Jarak Mutlak",
            prompt: "Lengkapi kesimpulan operasi penjumlahan bilangan bertanda dan jarak dua titik:",
            formulaTemplate: "a + (-b) = a [blank1] b \\quad \\text{dan} \\quad d(A, B) = [blank2]",
            blanks: [
              { id: "blank1", label: "Tanda Operasi", options: ["-", "+", "\\times"], correctOption: "-" },
              { id: "blank2", label: "Definisi Jarak", options: ["|b - a|", "b + a", "b - a"], correctOption: "|b - a|" },
            ],
            resolvedFormulaKaTeX: "a + (-b) = a - b \\quad \\text{dan} \\quad d(A, B) = |b - a|",
            explanation: "Menjumlahkan negatif setara dengan pengurangan. Jarak fisik antara dua titik selalu non-negatif berkat nilai mutlak.",
          },
        },
        {
          id: "r1-s5",
          type: "check",
          title: "Cek Nalar Cepat",
          naiExpression: "thinking",
          naiDialogue: "Uji pemahamanmu sebelum mencoba tantangan kanvas berikutnya!",
          check: {
            question: "Mengurangkan bilangan negatif, misal 5 - (-3), setara dengan melangkah MAJU ke kanan sejauh 3 langkah.",
            checkType: "true_false",
            trueFalseAnswer: true,
            explanation: "Tepat! Tanda kurang berarti membalik badan (menghadap kiri); bilangan negatif berarti berjalan mundur. Berjalan mundur saat menghadap kiri menghasilkan gerakan maju ke kanan!",
          },
        },
        {
          id: "r1-s6",
          type: "sandbox",
          title: "Playground Translasi Garis",
          naiExpression: "happy",
          naiDialogue: "Silakan geser slider bebas untuk melihat visualisasi vektor di kanvas.",
          sandbox: {
            title: "Simulasi Bebas Garis Bilangan",
            instructions: "Geser titik A dan B untuk menguji berbagai kombinasi bilangan positif dan negatif.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 3, point2: -4, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
          },
        },
        {
          id: "r1-s7",
          type: "challenge",
          title: "Misi: Atur Jarak Tepat 9 Satuan",
          naiExpression: "neutral",
          naiDialogue: "Bantu tim SAR mencari koordinat sinyal: atur posisi A di 3 dan temukan titik B berjarak 9 di sebelah kiri!",
          challenge: {
            id: "challenge-real-distance",
            title: "Target Jarak |B - A| = 9",
            question:
              "Atur posisi titik A di 3 dan tentukan posisi titik B di sebelah kiri sehingga jarak |B - A| bernilai tepat 9 satuan (Target: B = -6)!",
            targetCondition: (vars) => {
              return vars.point1 === 3 && vars.point2 === -6;
            },
            hint1Static: "Dari angka 3, melangkah ke kiri sebanyak 9 langkah: 3 - 9 = ?",
            hint2Static: "Geser slider titik B hingga angka -6.",
            solutionVariables: { point1: 3, point2: -6 },
            solutionExplanation: "|-6 - 3| = |-9| = 9 satuan jarak.",
            xpReward: 30,
          },
        },
        {
          id: "r1-s8",
          type: "reflect",
          title: "Refleksi Level 1: Bilangan Adalah Ruang",
          naiExpression: "celebrating",
          naiDialogue: "Luar biasa! Kamu membuktikan bahwa tambah dan kurang adalah petunjuk arah di ruang 1 dimensi!",
          reflect: {
            title: "Level 1 Tuntas: Garis Bilangan & Translasi",
            takeaways: [
              "Angka nol adalah titik origin acuan, bukan sekadar kehampaan.",
              "Penjumlahan dengan bilangan negatif a + (-b) adalah translasi ke arah kiri.",
              "Jarak antara dua koordinat selalu bernilai mutlak non-negatif d = |b - a|.",
            ],
            connectionText: "Di Level 2, kita akan melipatgandakan panjang dan membalik arah garis lewat operasi PERKALIAN!",
            nextLevelTitle: "Level 2: Skala & Misteri (-1) × (-1)",
            badgeToUnlock: "line-walker",
            xpReward: 30,
            formulaKaTeX: "d(a, b) = |b - a|",
          },
        },
      ],
    },
    {
      id: "real-level-2",
      index: 2,
      tier: 1,
      title: "Skala, Dilatasi, & Misteri (-1) × (-1)",
      description: "Perkalian sebagai peregangan garis dan rotasi arah 180 derajat.",
      ahaMoment: "Perkalian adalah zoom/peregangan, dan tanda minus adalah rotasi 180°!",
      steps: [
        {
          id: "r2-s1",
          type: "provoke",
          title: "Mengapa Negatif Kali Negatif Jadi Positif?",
          naiExpression: "curious",
          naiDialogue: "Banyak orang menghafal rumus tanda. Bisakah kamu melihat alasannya secara kasat mata?",
          provoke: {
            hookTitle: "Mengapa Minus Kali Minus Menghasilkan Plus?",
            hookText: "Bayangkan dua cermin berhadapan. Membalik pandangan satu kali membuat kiri jadi kanan. Membalik sekali lagi mengembalikan ke pandangan asli.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 4, point2: 0, scaleFactor: 2, sqrtN: 2, zoomLevel: 1 },
            question: "Mengapa (-1) × (-1) menghasilkan bilangan positif?",
            options: [
              {
                id: "opt-rot",
                text: "Karena membalik arah 180° sebanyak dua kali mengembalikan kita menghadap ke arah asal (+)",
                responseText: "Tepat sekali! 180° + 180° = 360°, yang berarti kembali menghadap ke arah positif.",
              },
              {
                id: "opt-rule",
                text: "Karena sudah aturan hafalan dari buku cetak matematika.",
                responseText: "Kurang tepat. Di Nalar, kita mencari alasan fisis dan geometris di balik setiap aturan!",
              },
            ],
          },
        },
        {
          id: "r2-s2",
          type: "predict",
          title: "Efek Pengali Skala",
          naiExpression: "thinking",
          naiDialogue: "Perhatikan panah dari 0 ke 3. Jika dikalikan pengali k = -2, ke mana ia pergi?",
          predict: {
            scenarioTitle: "Dilatasi Skalar 1D",
            scenarioText: "Vektor awal memiliki panjang 3 satuan ke kanan. Kita kalikan dengan faktor skala k = -2.",
            question: "Apa yang terjadi pada panjang dan arah panah hasil transformasi?",
            options: [
              {
                id: "pred-len-dir",
                text: "Panjang melar menjadi 6, dan arahnya berbalik ke kiri",
                isCorrect: true,
                feedback: "Hebat! Angka 2 melipatgandakan panjangnya (3 × 2 = 6), dan tanda minus membalik arahnya ke kiri (-6).",
              },
              {
                id: "pred-len-same",
                text: "Panjang tetap 3, arah ke kiri",
                isCorrect: false,
                feedback: "Faktor 2 juga mengubah panjang bentangannya, bukan hanya arahnya.",
              },
              {
                id: "pred-dir-same",
                text: "Panjang menjadi 6, arah tetap ke kanan",
                isCorrect: false,
                feedback: "Tanda minus pada -2 harus membalikkan arah vektor 180° ke kiri!",
              },
            ],
            simulationLabel: "Jalankan Peregangan Skala!",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 3, point2: 0, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
            simulationVariables: { point1: 3, point2: -6, scaleFactor: -2, sqrtN: 2, zoomLevel: 1 },
          },
        },
        {
          id: "r2-s3",
          type: "guided",
          title: "Simulator Dilatasi 1D",
          naiExpression: "happy",
          naiDialogue: "Geser faktor skala k dari positif ke negatif. Lihat bagaimana garis melar dan berputar balik!",
          guided: {
            instructionTitle: "Laboratorium Skala Peregangan",
            instructionText: "Ubah faktor skala k dari 2 ke 1, lalu ke 0, dan ke -2 untuk mengamati efek geometrisnya.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 4, point2: 0, scaleFactor: -2, sqrtN: 2, zoomLevel: 1 },
            observationTable: {
              headers: ["Faktor Skala k", "Efek Panjang", "Efek Arah"],
              rows: [
                { parameter: "k = 1", expectedValue: "Tetap", unit: "arah kanan" },
                { parameter: "k = -1", expectedValue: "Tetap", unit: "terbalik ke kiri (180°)" },
                { parameter: "k = -2", expectedValue: "Melar 2x", unit: "terbalik ke kiri (180°)" },
              ],
            },
            discoveryQuestion: {
              prompt: "Apa makna geometris dari mengalikan bilangan dengan -1?",
              options: [
                "Rotasi 180° membalik arah tanpa mengubah panjang",
                "Memperkecil bilangan menjadi nol",
                "Menggeser posisi sejauh 1 langkah",
              ],
              correctOption: "Rotasi 180° membalik arah tanpa mengubah panjang",
              insight: "Mengalikan dengan -1 adalah refleksi terhadap titik nol (rotasi setengah lingkaran 180°).",
            },
          },
        },
        {
          id: "r2-s4",
          type: "formalize",
          title: "Aturan Tanda & Nilai Mutlak Hasil Kali",
          naiExpression: "neutral",
          naiDialogue: "Mari formulasikan hukum perkalian tanda berdasarkan rotasi spasial yang baru kamu amati.",
          formalize: {
            title: "Formalisasi Perkalian Skalar",
            prompt: "Lengkapi kaidah tanda perkalian bilangan riil berikut:",
            formulaTemplate: "(+) \\times (-) \\to [blank1] \\quad \\text{dan} \\quad (-) \\times (-) \\to [blank2]",
            blanks: [
              { id: "blank1", label: "Tanda (+)(-)", options: ["Arah Kiri (-)", "Arah Kanan (+)", "Nol"], correctOption: "Arah Kiri (-)" },
              { id: "blank2", label: "Tanda (-)(-)", options: ["Arah Kanan (+)", "Arah Kiri (-)", "Nol"], correctOption: "Arah Kanan (+)" },
            ],
            resolvedFormulaKaTeX: "(-a) \\cdot (-b) = +(a \\cdot b) \\quad \\text{dan} \\quad |a \\cdot b| = |a| \\cdot |b|",
            explanation: "Pembalikan arah dua kali selalu menghasilkan arah positif (+). Panjang hasil kali selalu sama dengan perkalian nilai mutlaknya.",
          },
        },
        {
          id: "r2-s5",
          type: "check",
          title: "Cek Kilat Skalar",
          naiExpression: "thinking",
          naiDialogue: "Hati-hati dengan jebakan tanda beruntun pada soal ini!",
          check: {
            question: "Jika x < 0 dan y < 0, di arah manakah posisi hasil kali -x · y berada di garis bilangan?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-neg", text: "Arah Negatif (Kiri)", isCorrect: true, explanation: "Tepat! Karena x < 0, maka -x adalah positif. Positif dikali y (negatif) menghasilkan bilangan negatif!" },
              { id: "opt-pos", text: "Arah Positif (Kanan)", isCorrect: false, explanation: "Ingat bahwa ada 3 tanda minus: -x adalah positif, tapi y tetap negatif, jadi (+)(-) = (-)." },
              { id: "opt-zero", text: "Tepat di titik Nol", isCorrect: false, explanation: "Karena x dan y bukan nol, hasil kalinya tidak nol." },
            ],
            explanation: "Periksa tanda bertahap: (-x) > 0, y < 0. Maka (-x) · y < 0 (berada di sebelah kiri nol).",
          },
        },
        {
          id: "r2-s6",
          type: "sandbox",
          title: "Playground Skala Bebas",
          naiExpression: "happy",
          naiDialogue: "Uji coba berbagai kombinasi titik awal dan faktor skala di kanvas ini.",
          sandbox: {
            title: "Simulasi Skala & Refleksi",
            instructions: "Atur titik A dan faktor skala k untuk mengamati bayangan dilatasi di garis bilangan.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 4, point2: 0, scaleFactor: -2, sqrtN: 2, zoomLevel: 1 },
          },
        },
        {
          id: "r2-s7",
          type: "challenge",
          title: "Tantangan: Skala Terbalik Menjadi -8",
          naiExpression: "neutral",
          naiDialogue: "Atur titik A = 4 dan faktor skala pengali k = -2 sehingga bayangannya tepat mendarat di -8!",
          challenge: {
            id: "challenge-real-scale-reflection",
            title: "Konfigurasi A = 4 dan k = -2",
            question:
              "Atur titik A = 4 dan faktor skala pengali k = -2 sehingga bayangan titik mendarat tepat di -8!",
            targetCondition: (vars) => {
              return vars.point1 === 4 && vars.scaleFactor === -2;
            },
            hint1Static: "Atur slider titik A ke 4.",
            hint2Static: "Geser faktor skala k ke nilai negatif -2.",
            solutionVariables: { point1: 4, scaleFactor: -2 },
            solutionExplanation: "4 * (-2) = -8.",
            xpReward: 40,
          },
        },
        {
          id: "r2-s8",
          type: "reflect",
          title: "Refleksi Level 2: Simetri Dua Arah",
          naiExpression: "celebrating",
          naiDialogue: "Hebat! Kamu tidak lagi sekadar menghafal rumus tanda perkalian!",
          reflect: {
            title: "Level 2 Tuntas: Skala, Dilatasi, & Tanda",
            takeaways: [
              "Perkalian adalah operasi dilatasi peregangan panjang dari titik origin.",
              "Tanda minus adalah operasi geometri pembalik arah 180°.",
              "Minus kali minus menghasilkan plus karena dua kali rotasi 180° menghasilkan 360° (kembali ke asal).",
            ],
            connectionText: "Di Level 3, kita akan menyelami samudra tak hingga di antara dua bilangan bulat lewat PECAHAN!",
            nextLevelTitle: "Level 3: Pecahan, Desimal, & Kerapatan",
            badgeToUnlock: "pattern-seeker",
            xpReward: 40,
            formulaKaTeX: "(-1) \\cdot (-1) = +1",
          },
        },
      ],
    },
    {
      id: "real-level-3",
      index: 3,
      tier: 2,
      title: "Pecahan, Desimal, & Kerapatan Tak Hingga",
      description: "Menjelajahi kontinuitas garis bilangan dan menemukan titik tengah pecahan.",
      ahaMoment: "Di antara dua bilangan sekecil apa pun, selalu ada samudra bilangan tak hingga!",
      steps: [
        {
          id: "r3-s1",
          type: "provoke",
          title: "Apakah Garis Bilangan Punya Lubang?",
          naiExpression: "curious",
          naiDialogue: "Jika kita melompat dari 0 ke 1, apakah kita melompati kehampaan, atau ada dunia lain di sana?",
          provoke: {
            hookTitle: "Apakah Garis Bilangan Berlubang?",
            hookText: "Pada penggaris biasa, kita hanya melihat bilangan bulat 0, 1, 2. Namun ruang fisik di antaranya dapat diperbesar tanpa henti.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 0, point2: 1, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
            question: "Berapa banyak bilangan yang terletak di antara 0 dan 1?",
            options: [
              {
                id: "opt-inf",
                text: "Tak terhingga banyaknya bilangan pecahan dan desimal",
                responseText: "Tepat sekali! Selalu ada bilangan baru seperti 1/2, 1/4, 1/8, 0.001 yang tak pernah habis.",
              },
              {
                id: "opt-ten",
                text: "Hanya ada 9 bilangan desimal (0.1 sampai 0.9)",
                responseText: "Kurang tepat. Di antara 0.1 dan 0.2 masih ada 0.11, 0.12, dan seterusnya tanpa batas!",
              },
            ],
          },
        },
        {
          id: "r3-s2",
          type: "predict",
          title: "Siapa di Tengah-Tengah?",
          naiExpression: "thinking",
          naiDialogue: "Bisakah kamu menemukan pecahan yang persis berada di antara 1/3 dan 1/2?",
          predict: {
            scenarioTitle: "Mencari Titik Tengah Pecahan",
            scenarioText: "Dua titik berada di 1/3 (≈ 0.333) dan 1/2 (= 0.500). Kita ingin mencari titik tengah M = (A + B) / 2.",
            question: "Pecahan berapakah yang berada persis di tengah-tengah 1/3 dan 1/2?",
            options: [
              {
                id: "pred-5-12",
                text: "5/12",
                isCorrect: true,
                feedback: "Benar! (1/3 + 1/2) / 2 = (2/6 + 3/6) / 2 = (5/6) / 2 = 5/12 ≈ 0.4167.",
              },
              {
                id: "pred-2-5",
                text: "2/5",
                isCorrect: false,
                feedback: "2/5 = 0.400, mendekati tapi bukan titik tengah eksak dari 1/3 dan 1/2.",
              },
              {
                id: "pred-none",
                text: "Tidak ada pecahan lagi di antaranya",
                isCorrect: false,
                feedback: "Garis bilangan memiliki sifat kerapatan; selalu ada pecahan di antara dua bilangan rasional!",
              },
            ],
            simulationLabel: "Buktikan Titik Tengah!",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 0, point2: 1, scaleFactor: 1, sqrtN: 2, zoomLevel: 1.5 },
            simulationVariables: { point1: 2, point2: 6, scaleFactor: 1, sqrtN: 2, zoomLevel: 2 },
          },
        },
        {
          id: "r3-s3",
          type: "guided",
          title: "Zoom Tak Hingga: Kerapatan Pecahan",
          naiExpression: "happy",
          naiDialogue: "Perbesar skala zoom kanvas untuk melihat pembagian garis mikro di antara bilangan!",
          guided: {
            instructionTitle: "Eksplorasi Sifat Kerapatan (Density)",
            instructionText: "Gunakan pengatur zoom untuk mengamati bagaimana setiap segmen dapat terus dibagi menjadi bagian yang lebih kecil.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 2, point2: 6, scaleFactor: 1, sqrtN: 2, zoomLevel: 1.5 },
            observationTable: {
              headers: ["Rentang Awal", "Pembagi", "Titik Tengah Dihasilkan"],
              rows: [
                { parameter: "0 sampai 1", expectedValue: "0.5 (1/2)", unit: "titik tengah" },
                { parameter: "0 sampai 0.5", expectedValue: "0.25 (1/4)", unit: "titik tengah" },
              ],
            },
            discoveryQuestion: {
              prompt: "Berapa kali kita bisa membagi dua jarak antara dua titik sebelum kehabisan tempat?",
              options: [
                "Tak terhingga kali tanpa pernah habis",
                "Maksimal 100 kali pembagian",
                "Hanya sampai skala milimeter",
              ],
              correctOption: "Tak terhingga kali tanpa pernah habis",
              insight: "Ruang bilangan rasional padat (dense): di antara sembarang dua bilangan riil a < b selalu ada bilangan ketiga c = (a+b)/2.",
            },
          },
        },
        {
          id: "r3-s4",
          type: "formalize",
          title: "Definisi Bilangan Rasional & Titik Tengah",
          naiExpression: "neutral",
          naiDialogue: "Mari formulasikan definisi himpunan bilangan rasional Q dan rumus titik tengahnya.",
          formalize: {
            title: "Formalisasi Bilangan Rasional",
            prompt: "Lengkapi definisi himpunan rasional dan rumus titik tengah berikut:",
            formulaTemplate: "\\mathbb{Q} = \\left\\{ \\frac{p}{q} \\mid p,q \\in \\mathbb{Z}, q \\neq [blank1] \\right\\} \\quad \\text{dan} \\quad x_{\\text{mid}} = [blank2]",
            blanks: [
              { id: "blank1", label: "Syarat Penyebut", options: ["0", "1", "-1"], correctOption: "0" },
              { id: "blank2", label: "Rumus Titik Tengah", options: ["\\frac{x_1 + x_2}{2}", "x_2 - x_1", "\\sqrt{x_1 x_2}"], correctOption: "\\frac{x_1 + x_2}{2}" },
            ],
            resolvedFormulaKaTeX: "\\mathbb{Q} = \\left\\{ \\frac{p}{q} \\mid p,q \\in \\mathbb{Z}, q \\neq 0 \\right\\} \\quad \\text{dan} \\quad x_{\\text{mid}} = \\frac{x_1 + x_2}{2}",
            explanation: "Bilangan rasional adalah rasio dua bilangan bulat dengan penyebut bukan nol. Rata-rata dua bilangan selalu menjadi titik tengah yang sah.",
          },
        },
        {
          id: "r3-s5",
          type: "check",
          title: "Cek Nalar Kerapatan",
          naiExpression: "thinking",
          naiDialogue: "Periksa kembali pemahamanmu tentang kepadatan bilangan desimal!",
          check: {
            question: "Berapa banyak bilangan rasional yang ada di antara 0.99 dan 1.00?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-inf-check", text: "Tak terhingga banyaknya (misal 0.991, 0.9905, ...)", isCorrect: true, explanation: "Benar! Tidak peduli seberapa rapat dua bilangan, selalu ada tak terhingga pecahan di antaranya." },
              { id: "opt-zero-check", text: "Nol buah, karena 0.99 langsung melompat ke 1.00", isCorrect: false, explanation: "0.99 dan 1.00 bukan bilangan bulat yang bersebelahan; ini adalah desimal kontinu." },
              { id: "opt-nine-check", text: "Tepat 9 buah", isCorrect: false, explanation: "9 buah hanya jika kita membatasi 3 desimal saja, padahal desimal bisa memiliki digit tak hingga." },
            ],
            explanation: "Sifat kerapatan menjamin tak terhingga bilangan rasional di antara sembarang interval terbuka sekecil apa pun.",
          },
        },
        {
          id: "r3-s6",
          type: "sandbox",
          title: "Playground Zoom Kerapatan",
          naiExpression: "happy",
          naiDialogue: "Eksplorasi posisi titik dan pembesaran zoom garis bilangan mikro!",
          sandbox: {
            title: "Simulasi Zoom Titik Pecahan",
            instructions: "Ubah slider zoomLevel dan posisi titik untuk mengamati pembagian desimal.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 2, point2: 6, scaleFactor: 1, sqrtN: 2, zoomLevel: 1.5 },
          },
        },
        {
          id: "r3-s7",
          type: "challenge",
          title: "Misi: Titik Tengah Simetris",
          naiExpression: "neutral",
          naiDialogue: "Atur titik A di -5 dan titik B di nilai simetris positif sehingga titik tengahnya persis berada di angka 0!",
          challenge: {
            id: "challenge-real-midpoint",
            title: "Temukan Titik Tengah Nol (M = 0)",
            question:
              "Atur titik A di -5 dan titik B di nilai simetris positif sehingga titik tengahnya persis berada di angka 0!",
            targetCondition: (vars) => {
              return vars.point1 === -5 && vars.point2 === 5;
            },
            hint1Static: "Agar titik tengah = 0, penjumlahan A + B harus bernilai 0.",
            hint2Static: "Lawan dari -5 adalah +5. Geser B ke 5.",
            solutionVariables: { point1: -5, point2: 5 },
            solutionExplanation: "(-5 + 5) / 2 = 0 / 2 = 0.",
            xpReward: 50,
          },
        },
        {
          id: "r3-s8",
          type: "reflect",
          title: "Refleksi Level 3: Samudra Kontinu",
          naiExpression: "celebrating",
          naiDialogue: "Selamat! Sekarang garis bilanganmu sudah padat terisi oleh pecahan tak hingga.",
          reflect: {
            title: "Level 3 Tuntas: Pecahan & Kerapatan",
            takeaways: [
              "Himpunan bilangan rasional Q dapat dinyatakan sebagai pecahan p/q (q ≠ 0).",
              "Sifat kerapatan memastikan tidak ada dua bilangan rasional yang 'bersebelahan langsung'.",
              "Titik tengah antara dua titik selalu dihitung dengan rata-rata aritmetika (a + b) / 2.",
            ],
            connectionText: "Namun... apakah semua titik di garis bilangan sudah terisi penuh oleh pecahan? Temukan jawabannya di Level 4!",
            nextLevelTitle: "Level 4: Penemuan Bilangan Irasional (√2)",
            badgeToUnlock: "fraction-diver",
            xpReward: 50,
            formulaKaTeX: "x_{\\text{mid}} = \\frac{x_1 + x_2}{2}",
          },
        },
      ],
    },
    {
      id: "real-level-4",
      index: 4,
      tier: 2,
      title: "Penemuan Bilangan Irasional (Akar Pythagoras)",
      description: "Menemukan titik nyata di garis bilangan yang tidak bisa ditulis sebagai pecahan biasa.",
      ahaMoment: "Ada titik di garis bilangan yang mustahil ditulis sebagai pecahan: selamat datang di bilangan irasional!",
      steps: [
        {
          id: "r4-s1",
          type: "provoke",
          title: "Misteri Diagonal Bujur Sangkar",
          naiExpression: "curious",
          naiDialogue: "Menurut Pythagoras, kuadrat garis miring bujur sangkar 1 × 1 adalah 2. Berapa panjang pastinya?",
          provoke: {
            hookTitle: "Mengapa √2 Mengguncang Yunani Kuno?",
            hookText: "Bujur sangkar 1 × 1 memiliki diagonal c² = 1² + 1² = 2. Ilmuwan kuno mencoba menulis panjang ini sebagai pecahan biasa p/q namun selalu gagal.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 0, point2: 0, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
            question: "Bisakah panjang diagonal √2 ditulis dalam pecahan biasa p/q?",
            options: [
              {
                id: "opt-no-ratio",
                text: "Mustahil! Angka desimalnya tak berujung dan tak pernah berpola (irasional).",
                responseText: "Tepat sekali! Penemuan ini mengguncang dunia karena membuktikan ada panjang fisik yang bukan pecahan rasional.",
              },
              {
                id: "opt-yes-ratio",
                text: "Pasti bisa, hanya saja kita butuh angka pecahan yang sangat besar.",
                responseText: "Kurang tepat. Telah terbukti secara matematis bahwa √2 tidak dapat dinyatakan dalam bentuk p/q!",
              },
            ],
          },
        },
        {
          id: "r4-s2",
          type: "predict",
          title: "Di Mana Posisi √2 di Garis Bilangan?",
          naiExpression: "thinking",
          naiDialogue: "Jika diagonal direbahkan dengan jangka ke garis bilangan, di antara dua bilangan bulat manakah ia mendarat?",
          predict: {
            scenarioTitle: "Rebahan Diagonal Bujur Sangkar",
            scenarioText: "Kita letakkan bujur sangkar 1 × 1 di garis bilangan dari 0 ke 1, lalu busur jangka menjatuhkan diagonalnya ke garis bilangan.",
            question: "Di antara dua bilangan manakah posisi ujung jangka tersebut mendarat?",
            options: [
              {
                id: "pred-1-2",
                text: "Antara 1 dan 2 (tepatnya sekitar 1.414)",
                isCorrect: true,
                feedback: "Benar! Karena 1² = 1 dan 2² = 4, maka nilai √2 berada di antara 1 dan 2 (sekitar 1.414).",
              },
              {
                id: "pred-2-3",
                text: "Antara 2 dan 3",
                isCorrect: false,
                feedback: "Terlalu besar. 2² = 4, padahal kuadrat diagonal ini hanyalah 2.",
              },
              {
                id: "pred-0-1",
                text: "Antara 0 dan 1",
                isCorrect: false,
                feedback: "Diagonal bujur sangkar selalu lebih panjang dari sisi tegaknya (sisi tegak = 1).",
              },
            ],
            simulationLabel: "Rebahkan Jangka!",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 0, point2: 0, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
            simulationVariables: { point1: 0, point2: 1.414, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
          },
        },
        {
          id: "r4-s3",
          type: "guided",
          title: "Simulator Busur Jangka Pythagoras",
          naiExpression: "happy",
          naiDialogue: "Ubah slider N akar kuadrat dan amati busur jangka ungu yang merebahkan nilai akar ke garis bilangan!",
          guided: {
            instructionTitle: "Menjatuhkan Hipotenusa ke Garis Bilangan",
            instructionText: "Ubah nilai N untuk melihat konstruksi geometri segitiga siku-siku dan posisi jatuhnya akar pada garis riil.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 0, point2: 0, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
            observationTable: {
              headers: ["Nilai N", "Segitiga Alas × Tinggi", "Posisi Jatuh √N"],
              rows: [
                { parameter: "N = 2", expectedValue: "1 × 1", unit: "≈ 1.414" },
                { parameter: "N = 5", expectedValue: "2 × 1", unit: "≈ 2.236" },
              ],
            },
            discoveryQuestion: {
              prompt: "Apakah titik √2 benar-benar ada secara fisik di garis bilangan?",
              options: [
                "Ya, memiliki lokasi koordinat yang nyata dan terukur",
                "Tidak, itu hanya bilangan imajiner",
                "Hanya ada jika dibulatkan",
              ],
              correctOption: "Ya, memiliki lokasi koordinat yang nyata dan terukur",
              insight: "Bilangan irasional memiliki lokasi koordinat fisik nyata yang menutup lubang-lubang mikroskopis pada garis bilangan.",
            },
          },
        },
        {
          id: "r4-s4",
          type: "formalize",
          title: "Definisi Bilangan Irasional & Bilangan Riil",
          naiExpression: "neutral",
          naiDialogue: "Sekarang garis bilangan menjadi utuh berkat gabungan rasional dan irasional.",
          formalize: {
            title: "Himpunan Bilangan Riil R",
            prompt: "Lengkapi kesimpulan klasifikasi bilangan dan gabungan kontinum berikut:",
            formulaTemplate: "\\sqrt{2} [blank1] \\mathbb{Q} \\quad \\text{dan} \\quad \\mathbb{R} = \\mathbb{Q} \\cup [blank2]",
            blanks: [
              { id: "blank1", label: "Keanggotaan Rasional", options: ["\\notin", "\\in", "="], correctOption: "\\notin" },
              { id: "blank2", label: "Himpunan Irasional", options: ["\\mathbb{I}", "\\mathbb{Z}", "\\mathbb{N}"], correctOption: "\\mathbb{I}" },
            ],
            resolvedFormulaKaTeX: "\\sqrt{2} \\notin \\mathbb{Q} \\quad \\text{dan} \\quad \\mathbb{R} = \\mathbb{Q} \\cup \\mathbb{I}",
            explanation: "Bilangan irasional tidak dapat ditulis sebagai p/q. Gabungan seluruh bilangan rasional dan irasional membentuk himpunan Bilangan Riil (R).",
          },
        },
        {
          id: "r4-s5",
          type: "check",
          title: "Cek Pemahaman Irasional",
          naiExpression: "thinking",
          naiDialogue: "Uji kejelianmu membedakan bilangan rasional dan irasional!",
          check: {
            question: "Penjumlahan bilangan rasional dan bilangan irasional, misalnya 3 + √2, selalu menghasilkan bilangan irasional.",
            checkType: "true_false",
            trueFalseAnswer: true,
            explanation: "Benar! Jika hasilnya rasional, maka √2 = rasional - 3 yang akan membuat √2 menjadi rasional (kontradiksi). Maka 3 + √2 pasti irasional.",
          },
        },
        {
          id: "r4-s6",
          type: "sandbox",
          title: "Playground Busur Akar Bilangan",
          naiExpression: "happy",
          naiDialogue: "Eksplorasi berbagai nilai N untuk melihat konstruksi spiral Theodorus di kanvas.",
          sandbox: {
            title: "Simulasi Rebahan Akar Kuadrat Bebas",
            instructions: "Ubah slider N dan amati panjang hipotenusa yang direbahkan ke garis bilangan.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 0, point2: 0, scaleFactor: 1, sqrtN: 2, zoomLevel: 1 },
          },
        },
        {
          id: "r4-s7",
          type: "challenge",
          title: "Tantangan: Rebahkan √5 ke Garis Bilangan",
          naiExpression: "neutral",
          naiDialogue: "Atur slider akar kuadrat ke N = 5 untuk merebahkan diagonal segitiga siku-siku 1 × 2 (Target: √5 ≈ 2.24)!",
          challenge: {
            id: "challenge-real-sqrt5",
            title: "Konfigurasi Akar Kuadrat N = 5",
            question:
              "Atur slider akar kuadrat ke N = 5 untuk merebahkan diagonal segitiga siku-siku 1 × 2 (Target: √5 ≈ 2.24)!",
            targetCondition: (vars) => {
              return vars.sqrtN === 5;
            },
            hint1Static: "1² + 2² = 1 + 4 = 5. Panjang diagonal adalah √5.",
            hint2Static: "Geser slider akar kuadrat ke angka 5.",
            solutionVariables: { sqrtN: 5 },
            solutionExplanation: "√5 ≈ 2.236067... berada di antara bilangan bulat 2 dan 3.",
            xpReward: 50,
          },
        },
        {
          id: "r4-s8",
          type: "reflect",
          title: "Refleksi Level 4: Garis Bilangan yang Utuh",
          naiExpression: "celebrating",
          naiDialogue: "Luar biasa! Sekarang garis bilanganmu tidak berlubang lagi!",
          reflect: {
            title: "Level 4 Tuntas: Penakluk Bilangan Irasional",
            takeaways: [
              "Bilangan irasional memiliki desimal tak hingga yang tidak pernah berulang periodik.",
              "Konstruksi busur jangka membuktikan bahwa bilangan irasional memiliki titik fisik nyata di garis 1D.",
              "Setiap titik di garis bilangan berkorespondensi satu-satu dengan satu bilangan riil R.",
            ],
            connectionText: "Di Level 5, kita akan membuktikan hukum-hukum aljabar dasar (komutatif & distributif) secara geometris!",
            nextLevelTitle: "Level 5: Geometri Sifat Aljabar",
            badgeToUnlock: "irrational-master",
            xpReward: 50,
            formulaKaTeX: "\\mathbb{R} = \\mathbb{Q} \\cup \\mathbb{I}",
          },
        },
      ],
    },
    {
      id: "real-level-5",
      index: 5,
      tier: 3,
      title: "Geometri Sifat Aljabar (Komutatif & Distributif)",
      description: "Membuktikan hukum aljabar dasar melalui penataan luas persegi panjang.",
      ahaMoment: "Hukum aljabar bukan aturan hafalan kertas, melainkan fakta bahwa memutar ubin tidak mengubah luasnya!",
      steps: [
        {
          id: "r5-s1",
          type: "provoke",
          title: "Mengapa 3 × 5 = 5 × 3?",
          naiExpression: "curious",
          naiDialogue: "Mengapa perkalian selalu bolak-balik sama? Apakah itu hanya kebetulan atau hukum alam?",
          provoke: {
            hookTitle: "Rotasi Persegi Panjang 2D",
            hookText: "Bayangkan sebuah ubin lantai berukuran 3 baris dan 5 kolom. Jika kita memutar ubin ini 90 derajat, ia menjadi 5 baris dan 3 kolom.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { point1: 0, point2: 0, scaleFactor: 1, sqrtN: 2, zoomLevel: 1, distribA: 3, distribB: 4, distribC: 2 },
            question: "Apakah jumlah total kotak berubah saat ubin diputar?",
            options: [
              {
                id: "opt-same-area",
                text: "Tidak berubah sama sekali! Luasnya tetap 15 kotak.",
                responseText: "Tepat sekali! Inilah bukti visual paling murni dari sifat komutatif a · b = b · a.",
              },
              {
                id: "opt-diff-area",
                text: "Berubah tergantung cara menghitungnya.",
                responseText: "Kurang tepat. Menghitung baris dulu atau kolom dulu tidak pernah mengubah jumlah fisik materi.",
              },
            ],
          },
        },
        {
          id: "r5-s2",
          type: "predict",
          title: "Membelah Kebun dengan Pagar",
          naiExpression: "thinking",
          naiDialogue: "Sebuah kebun berukuran a × (b + c) dibelah oleh pagar pemisah. Berapa jumlah luas kedua petak?",
          predict: {
            scenarioTitle: "Kebun Persegi Panjang Distributif",
            scenarioText: "Kebun besar memiliki panjang total (b + c) dan lebar a. Sebuah pagar memisahkan bagian b dan c.",
            question: "Manakah persamaan luas yang menggambarkan pembelahan kebun ini?",
            options: [
              {
                id: "pred-distrib",
                text: "a(b + c) = ab + ac",
                isCorrect: true,
                feedback: "Benar! Luas kebun utuh sama persis dengan luas petak pertama (ab) ditambah luas petak kedua (ac).",
              },
              {
                id: "pred-wrong-plus",
                text: "a(b + c) = ab + c",
                isCorrect: false,
                feedback: "Perhatikan bahwa lebar petak kedua juga harus a, sehingga luasnya adalah ac, bukan c saja.",
              },
            ],
            simulationLabel: "Buktikan Luas Kebun!",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { distribA: 3, distribB: 4, distribC: 2 },
            simulationVariables: { distribA: 3, distribB: 4, distribC: 2 },
          },
        },
        {
          id: "r5-s3",
          type: "guided",
          title: "Laboratorium Partisi Luas Geometris",
          naiExpression: "happy",
          naiDialogue: "Ubah parameter a, b, dan c untuk melihat pecahan petak luas aljabar di kanvas!",
          guided: {
            instructionTitle: "Eksplorasi Partisi Persegi Panjang",
            instructionText: "Atur parameter panjang a, b, dan c untuk melihat keselarasan antara aljabar simbolik dan luas bangun datar.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { distribA: 3, distribB: 4, distribC: 2 },
            observationTable: {
              headers: ["Parameter a, b, c", "Luas Utuh a(b+c)", "Jumlah Petak ab + ac"],
              rows: [
                { parameter: "a=3, b=4, c=2", expectedValue: "3 × (4 + 2) = 18", unit: "satuan luas" },
                { parameter: "a=4, b=3, c=5", expectedValue: "4 × (3 + 5) = 32", unit: "satuan luas" },
              ],
            },
            discoveryQuestion: {
              prompt: "Bagaimana cara menghitung 19 × 7 dengan cepat di luar kepala menggunakan sifat distributif?",
              options: [
                "Pecah menjadi (20 - 1) × 7 = 140 - 7 = 133",
                "Hitung bersusun panjang di atas kertas",
                "Gunakan pendekatan pembulatan kira-kira",
              ],
              correctOption: "Pecah menjadi (20 - 1) × 7 = 140 - 7 = 133",
              insight: "Sifat distributif mengubah perkalian rumit menjadi operasi mental cepat dan elegan.",
            },
          },
        },
        {
          id: "r5-s4",
          type: "formalize",
          title: "Aksioma Lapangan Bilangan Riil",
          naiExpression: "neutral",
          naiDialogue: "Mari kita rangkum aksioma dasar bilangan riil ke dalam formula universal.",
          formalize: {
            title: "Aksioma Komutatif & Distributif",
            prompt: "Lengkapi hukum dasar aljabar berikut:",
            formulaTemplate: "a \\cdot b = [blank1] \\quad \\text{dan} \\quad a(b + c) = [blank2]",
            blanks: [
              { id: "blank1", label: "Sifat Komutatif", options: ["b \\cdot a", "a + b", "b - a"], correctOption: "b \\cdot a" },
              { id: "blank2", label: "Sifat Distributif", options: ["ab + ac", "ab + c", "a + bc"], correctOption: "ab + ac" },
            ],
            resolvedFormulaKaTeX: "a \\cdot b = b \\cdot a \\quad \\text{dan} \\quad a(b + c) = ab + ac",
            explanation: "Sifat aljabar ini bukan sekadar aturan di atas kertas, melainkan perwujudan simetri rotasi dan partisi luas geometri 2D.",
          },
        },
        {
          id: "r5-s5",
          type: "check",
          title: "Cek Nalar Komprehensif",
          naiExpression: "thinking",
          naiDialogue: "Periksa apakah kamu dapat menerapkan sifat distributif secara langsung!",
          check: {
            question: "Berapakah hasil dari 25 × 12 jika diselesaikan dengan sifat distributif 25 × (10 + 2)?",
            checkType: "multiple_choice",
            options: [
              { id: "opt-300", text: "250 + 50 = 300", isCorrect: true, explanation: "Tepat sekali! 25 × 10 = 250, 25 × 2 = 50. 250 + 50 = 300." },
              { id: "opt-280", text: "280", isCorrect: false, explanation: "Periksa kembali penjumlahan 250 + 50." },
              { id: "opt-252", text: "252", isCorrect: false, explanation: "Ini kesalahan jika hanya menambahkan 2 tanpa mengalikannya dengan 25." },
            ],
            explanation: "25 × (10 + 2) = (25 × 10) + (25 × 2) = 250 + 50 = 300.",
          },
        },
        {
          id: "r5-s6",
          type: "sandbox",
          title: "Playground Geometri Aljabar",
          naiExpression: "happy",
          naiDialogue: "Eksplorasi parameter partisi kebun aljabar sebebas mungkin!",
          sandbox: {
            title: "Simulasi Partisi Luas Kebun",
            instructions: "Atur parameter a, b, dan c untuk melihat partisi persegi panjang secara real-time.",
            interactiveComponentSlug: "math-real-numbers-line",
            initialVariables: { distribA: 3, distribB: 4, distribC: 2 },
          },
        },
        {
          id: "r5-s7",
          type: "challenge",
          title: "Tantangan: Konfigurasi Luas Distributif Tepat 18",
          naiExpression: "neutral",
          naiDialogue: "Atur parameter a = 3, b = 4, dan c = 2 sehingga luas total kebun bernilai tepat 18 satuan!",
          challenge: {
            id: "challenge-real-distributive-area",
            title: "Konfigurasi Luas 3 × (4 + 2) = 18",
            question:
              "Atur parameter kebun aljabar menjadi a = 3, b = 4, dan c = 2 sehingga total luas petak bernilai tepat 18 satuan!",
            targetCondition: (vars) => {
              const a = vars.distribA ?? 3;
              const b = vars.distribB ?? 4;
              const c = vars.distribC ?? 2;
              return a === 3 && b === 4 && c === 2;
            },
            hint1Static: "Atur slider distribA ke 3.",
            hint2Static: "Atur slider distribB ke 4 dan distribC ke 2. Total luas: 3 * (4 + 2) = 18.",
            solutionVariables: { distribA: 3, distribB: 4, distribC: 2 },
            solutionExplanation: "3 * (4 + 2) = 3*4 + 3*2 = 12 + 6 = 18 satuan luas.",
            xpReward: 60,
          },
        },
        {
          id: "r5-s8",
          type: "reflect",
          title: "Refleksi Akhir: Penguasa Fondasi Real",
          naiExpression: "celebrating",
          naiDialogue: "Selamat! Kamu telah menyelesaikan seluruh petualangan Fondasi Bilangan Riil!",
          reflect: {
            title: "Modul Selesai: Master Bilangan Riil",
            takeaways: [
              "Bilangan adalah posisi dan perpindahan arah spasial di ruang kontinu.",
              "Perkalian adalah dilatasi skala dan pembalikan arah rotasi 180°.",
              "Kerapatan pecahan dan kelengkapan bilangan irasional menjadikan garis bilangan utuh sempurna.",
              "Hukum-hukum aljabar komutatif dan distributif terbukti secara geometris.",
            ],
            connectionText: "Siap melangkah ke topik berikutnya? Masuki dunia perulangan siklis di Aritmetika Jam (Modulo)!",
            badgeToUnlock: "real-numbers-master",
            xpReward: 60,
            formulaKaTeX: "a(b + c) = ab + ac",
          },
        },
      ],
    },
  ],
};
